In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import numpy as np
data=pd.read_table("/content/drive/MyDrive/ROCo/test/radiology/captions.txt")
data

      ROCO_00001                          Axial MRI (coronal view).
0     ROCO_00006   Coronal plain computed tomography image showi...
1     ROCO_00016   Axial source image from an intracranial magne...
2     ROCO_00025   The apical height, homogeneity, and the thick...
3     ROCO_00031            CTO of RCA (closure in the 2nd segment)
4     ROCO_00036   Venography shows a large amount of thrombogen...
...          ...                                                ...
8173  ROCO_81771   Damus–Kaye–Stansel shunt. Oblique coronal MIP...
8174  ROCO_81778   MRI pelvis post-radiation, axial STIR/T2W FSE...
8175  ROCO_81792   Fluoroscopic image showing attempts to grab t...
8176  ROCO_81796   Positron emission tomography–computed tomogra...
8177  ROCO_81798   Cholangiography showing the metallic stent pl...

[8178 rows x 2 columns]

In [4]:
data.columns=['label','caption']
data.head()

        label                                            caption
0  ROCO_00006   Coronal plain computed tomography image showi...
1  ROCO_00016   Axial source image from an intracranial magne...
2  ROCO_00025   The apical height, homogeneity, and the thick...
3  ROCO_00031            CTO of RCA (closure in the 2nd segment)
4  ROCO_00036   Venography shows a large amount of thrombogen...

In [5]:
captions = " ".join(data['caption'])
print(captions[:500])

 Coronal plain computed tomography image showing multiple large tumor masses with edge enhancement inside the abdominal cavity and liver.  Axial source image from an intracranial magnetic resonance angiogram reveals abnormal arterial signal elevation in the left more than right cavernous sinuses consistent with a carotid cavernous fistula, as indicated by the arrow.  The apical height, homogeneity, and the thickness of mineral trioxide aggregate plug  CTO of RCA (closure in the 2nd segment)  Ven

In [6]:
captions=captions.lower()

In [7]:
from nltk.corpus import stopwords
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [8]:
stop_words=set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [9]:
text_input = " ".join([word.lower() for word in captions.split() if word.lower() not in stop_words][:500])
text_input

"coronal plain computed tomography image showing multiple large tumor masses edge enhancement inside abdominal cavity liver. axial source image intracranial magnetic resonance angiogram reveals abnormal arterial signal elevation left right cavernous sinuses consistent carotid cavernous fistula, indicated arrow. apical height, homogeneity, thickness mineral trioxide aggregate plug cto rca (closure 2nd segment) venography shows large amount thrombogenesis femoropoplitea vein thrombolysis. postoperative decreased size cyst fetal aortic arch. solid arrow represents ascending aorta dotted arrow represents aortic arch distal ductus arteriosus. note aliasing ductal arch reflecting turbulent blood flow result external compression due mass-effect. abdominal computed tomography scan. arrow points likely cholecystocutaneous fistulous track. distension digestive avec niveaux hydro-aériques coliques et vacuité pelvienne panoramic x ray taken four years later showing unilocular radiolucent area left ramus. anteroposterior radiograph pelvis recent follow up. immediate postinjury magnetic resonance image demonstrating intact spinal cord canal cerebrospinal fluid signal surrounding spinal cord levels. arterial phase dynamic ct shows homogenous enhancement mass (arrow). level, normal right side adrenal gland visualized. angiogram showing pseudoaneurysm (arrow) formation proximal left superficial femoral artery. image ct fluoroscopic guidance rhizotomy demonstrates radiofrequency cannular tip junction superior articular process transverse process. bileteral styloid process elongation subject panoramic radiography. solid-cystic lesion thickened hyperechoic wall. region polycyclic solid structure wall lesion, color doppler (cdus) shows tortuous arterial vessels initial chest x-ray showing left tension pneumothorax shift mediastinum right, pleural effusion left, basal dorsolateral rib fractures. there's also air visible right diaphragm (arrow). large subcutaneous tributary pierces superficial fascia join lsv thigh region. brain magnetic resonance imaging (mri) gadolinium injection showed image axial (flair sequence) showing hyper-intensity lesions white matter frontal lobes. signal abnormality cortex. note mass effect ventricular cavities midline structures. dosimetric results obtained rapidarc. barium small bowel meal follow showing normal small large bowel. ct axial section shows multilocular expansile lytic lesion body mandible right side significant enhancing soft tissue matrix computed tomography obtained 3 weeks admission diagnosis aspiration pneumonia showed hepatic portal venous gas gas within wall stomach visualized portions upper abdomen postoperative day 1 chest radiograph reveals large left pneumothorax. left upper lobe squamous cell cancer showing broad, convex margin mediastinum ct (arrow); mediastinal pleural invasion surgery pathology (t2 tumor). ct scan thorax demonstrating necrotic paratracheal node. enhanced axial ct scan thorax, mediastinal window, 58-year-old female presented bilateral vocal cord immobility unknown etiology. positive serum anti-hu antibody, highly associated small cell lung carcinoma, led repeat ct scan. arrow demonstrates enlarged level 4r paratracheal lymph node central necrosis. see figure 2 pathologic description biopsy node. cortical bone changes rheumatoid arthritis classical radiography showing striation lamellation cortical bone phalanx. twelve-year-old boy presented nasopharyngeal angiofi broma diagnosed unilateral meningo-ophthalmic artery anomaly. computed tomography scan shows midline nasopharyngeal angiofi broma (black arrow), prominent right-side infiltration infratemporal fossa (white arrow). pelvis arthrogram showed defective ossification lateral acetabular corner, leaving significant cartilaginous anlage left anterior oblique common coronary artery branches critical disease proximal rca, mid/distal anomalous lcx. calculation inferior vena cava collapsibility index ([a–b]/b) (%) using ultrasonography ct guided core biopsy infracolic omental cake. initial radiograph shows right"

In [10]:
from textblob import TextBlob
TextBlob(text_input).correct()

TextBlob("corona plain computer cosmography image showing multiple large tumor masses edge enhancement inside abdominal cavity liver. animal source image intracranial magnetic resonance angiogram reveals abnormal arterial signal elevation left right cavernous sinuses consistent carotid cavernous fistula, indicated arrow. capital height, homogeneity, thickness mineral dioxide aggregate plug to sca (closure and segment) geography shows large amount thrombogenesis femoropoplitea vein thrombosis. postoperative decreased size cyst fatal aortic arch. solid arrow represents ascending aorta dotted arrow represents aortic arch distal ducts arterioles. note arising distal arch reflecting turbulent blood flow result external compression due mass-effect. abdominal computer cosmography scan. arrow points likely cholecystocutaneous fistulas track. distension digestive avec niveaux hydra-aériques cosaques et vacuité pelvienne panorama x ray taken four years later showing unilocular radiolucent area left rams. anteroposterior radiogram pelvis recent follow up. immediate postinjury magnetic resonance image demonstrating intact spinal cord canal cerebrospinal fluid signal surrounding spinal cord levels. arterial phase dynamic it shows homogeneous enhancement mass (arrow). level, normal right side adrenal gland visualized. angiogram showing pseudoaneurysm (arrow) formation proximal left superficial femoral artery. image it fluoroscopic guidance rhizotomy demonstrates radiofrequency cannula tip junction superior articular process transverse process. bilateral styled process elongation subject panorama radiography. solid-cystic lesion thickened hyperechoic wall. region polycyclic solid structure wall lesion, color copper (us) shows tortuous arterial vessels initial chest x-ray showing left tension pneumothorax shift mediastinum right, pleural effusion left, basal dorsolateral rib fractures. there's also air visible right diaphragm (arrow). large subcutaneous tributary pieces superficial fascia join is thigh region. brain magnetic resonance imagine (mr) gadolinium injection showed image animal (flair sequence) showing hyper-intensity lesions white matter frontal loves. signal abnormality cortex. note mass effect ventricular cavities midwife structures. dosimetric results obtained rapidarc. radium small bowel meal follow showing normal small large bowel. it animal section shows multilocular expansile lyric lesion body mandible right side significant enhancing soft tissue matrix computer cosmography obtained 3 weeks admission diagnosis aspiration pneumonia showed hepatic portal venous gas gas within wall stomach visualized portions upper abdomen postoperative day 1 chest radiogram reveals large left pneumothorax. left upper love squamous cell cancer showing broad, convex margin mediastinum it (arrow); mediastinal pleural invasion surgery pathology (to tumor). it scan thorax demonstrating necrotic paratracheal node. enhanced animal it scan thorax, mediastinal window, 58-year-old female presented bilateral vocal cord immobility unknown etiology. positive serum anti-he antibody, highly associated small cell lung carcinoma, led repeat it scan. arrow demonstrates enlarged level or paratracheal lymph node central necrosis. see figure 2 pathological description tipsy node. cortical bone changes rheumatoid arthritis classical radiography showing station lamentation cortical bone phalanx. twelve-year-old boy presented nasopharyngeal angioma aroma diagnosed unilateral meaning-ophthalmic artery animal. computer cosmography scan shows midwife nasopharyngeal angioma aroma (black arrow), prominent right-side infiltration infratemporal fossa (white arrow). pelvis arthrogram showed defective ossification lateral acetabular corner, leaving significant cartilaginous bandage left anterior oblique common coronary artery branches critical disease proximal sca, mid/distal anomalies lax. calculation inferior vena cava collapsibility index ([a–b]/b) (%) using ultrasonography it guided core tipsy infracolic omental cake. initial radiogram shows right")

In [11]:
from nltk.tokenize import sent_tokenize
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [12]:
sent_tokenize(text_input)

['coronal plain computed tomography image showing multiple large tumor masses edge enhancement inside abdominal cavity liver.',
 'axial source image intracranial magnetic resonance angiogram reveals abnormal arterial signal elevation left right cavernous sinuses consistent carotid cavernous fistula, indicated arrow.',
 'apical height, homogeneity, thickness mineral trioxide aggregate plug cto rca (closure 2nd segment) venography shows large amount thrombogenesis femoropoplitea vein thrombolysis.',
 'postoperative decreased size cyst fetal aortic arch.',
 'solid arrow represents ascending aorta dotted arrow represents aortic arch distal ductus arteriosus.',
 'note aliasing ductal arch reflecting turbulent blood flow result external compression due mass-effect.',
 'abdominal computed tomography scan.',
 'arrow points likely cholecystocutaneous fistulous track.',
 'distension digestive avec niveaux hydro-aériques coliques et vacuité pelvienne panoramic x ray taken four years later showing unilocular radiolucent area left ramus.',
 'anteroposterior radiograph pelvis recent follow up.',
 'immediate postinjury magnetic resonance image demonstrating intact spinal cord canal cerebrospinal fluid signal surrounding spinal cord levels.',
 'arterial phase dynamic ct shows homogenous enhancement mass (arrow).',
 'level, normal right side adrenal gland visualized.',
 'angiogram showing pseudoaneurysm (arrow) formation proximal left superficial femoral artery.',
 'image ct fluoroscopic guidance rhizotomy demonstrates radiofrequency cannular tip junction superior articular process transverse process.',
 'bileteral styloid process elongation subject panoramic radiography.',
 'solid-cystic lesion thickened hyperechoic wall.',
 'region polycyclic solid structure wall lesion, color doppler (cdus) shows tortuous arterial vessels initial chest x-ray showing left tension pneumothorax shift mediastinum right, pleural effusion left, basal dorsolateral rib fractures.',
 "there's also air visible right diaphragm (arrow).",
 'large subcutaneous tributary pierces superficial fascia join lsv thigh region.',
 'brain magnetic resonance imaging (mri) gadolinium injection showed image axial (flair sequence) showing hyper-intensity lesions white matter frontal lobes.',
 'signal abnormality cortex.',
 'note mass effect ventricular cavities midline structures.',
 'dosimetric results obtained rapidarc.',
 'barium small bowel meal follow showing normal small large bowel.',
 'ct axial section shows multilocular expansile lytic lesion body mandible right side significant enhancing soft tissue matrix computed tomography obtained 3 weeks admission diagnosis aspiration pneumonia showed hepatic portal venous gas gas within wall stomach visualized portions upper abdomen postoperative day 1 chest radiograph reveals large left pneumothorax.',
 'left upper lobe squamous cell cancer showing broad, convex margin mediastinum ct (arrow); mediastinal pleural invasion surgery pathology (t2 tumor).',
 'ct scan thorax demonstrating necrotic paratracheal node.',
 'enhanced axial ct scan thorax, mediastinal window, 58-year-old female presented bilateral vocal cord immobility unknown etiology.',
 'positive serum anti-hu antibody, highly associated small cell lung carcinoma, led repeat ct scan.',
 'arrow demonstrates enlarged level 4r paratracheal lymph node central necrosis.',
 'see figure 2 pathologic description biopsy node.',
 'cortical bone changes rheumatoid arthritis classical radiography showing striation lamellation cortical bone phalanx.',
 'twelve-year-old boy presented nasopharyngeal angiofi broma diagnosed unilateral meningo-ophthalmic artery anomaly.',
 'computed tomography scan shows midline nasopharyngeal angiofi broma (black arrow), prominent right-side infiltration infratemporal fossa (white arrow).',
 'pelvis arthrogram showed defective ossification lateral acetabular corner, leaving significant cartilaginous anlage left anterior oblique common coronary artery branches critical disease proximal rca, mid/distal anomalous lcx.',
 'calculation inferior vena cava collapsibility index ([a–b]/b) (%) using ultrasonography ct guided core biopsy infracolic omental cake.',
 'initial radiograph shows right']

In [13]:
from nltk.tokenize import wordpunct_tokenize
wordpunct_tokenize(text_input)

['coronal',
 'plain',
 'computed',
 'tomography',
 'image',
 'showing',
 'multiple',
 'large',
 'tumor',
 'masses',
 'edge',
 'enhancement',
 'inside',
 'abdominal',
 'cavity',
 'liver',
 '.',
 'axial',
 'source',
 'image',
 'intracranial',
 'magnetic',
 'resonance',
 'angiogram',
 'reveals',
 'abnormal',
 'arterial',
 'signal',
 'elevation',
 'left',
 'right',
 'cavernous',
 'sinuses',
 'consistent',
 'carotid',
 'cavernous',
 'fistula',
 ',',
 'indicated',
 'arrow',
 '.',
 'apical',
 'height',
 ',',
 'homogeneity',
 ',',
 'thickness',
 'mineral',
 'trioxide',
 'aggregate',
 'plug',
 'cto',
 'rca',
 '(',
 'closure',
 '2nd',
 'segment',
 ')',
 'venography',
 'shows',
 'large',
 'amount',
 'thrombogenesis',
 'femoropoplitea',
 'vein',
 'thrombolysis',
 '.',
 'postoperative',
 'decreased',
 'size',
 'cyst',
 'fetal',
 'aortic',
 'arch',
 '.',
 'solid',
 'arrow',
 'represents',
 'ascending',
 'aorta',
 'dotted',
 'arrow',
 'represents',
 'aortic',
 'arch',
 'distal',
 'ductus',
 'arteriosus',
 '.',
 'note',
 'aliasing',
 'ductal',
 'arch',
 'reflecting',
 'turbulent',
 'blood',
 'flow',
 'result',
 'external',
 'compression',
 'due',
 'mass',
 '-',
 'effect',
 '.',
 'abdominal',
 'computed',
 'tomography',
 'scan',
 '.',
 'arrow',
 'points',
 'likely',
 'cholecystocutaneous',
 'fistulous',
 'track',
 '.',
 'distension',
 'digestive',
 'avec',
 'niveaux',
 'hydro',
 '-',
 'aériques',
 'coliques',
 'et',
 'vacuité',
 'pelvienne',
 'panoramic',
 'x',
 'ray',
 'taken',
 'four',
 'years',
 'later',
 'showing',
 'unilocular',
 'radiolucent',
 'area',
 'left',
 'ramus',
 '.',
 'anteroposterior',
 'radiograph',
 'pelvis',
 'recent',
 'follow',
 'up',
 '.',
 'immediate',
 'postinjury',
 'magnetic',
 'resonance',
 'image',
 'demonstrating',
 'intact',
 'spinal',
 'cord',
 'canal',
 'cerebrospinal',
 'fluid',
 'signal',
 'surrounding',
 'spinal',
 'cord',
 'levels',
 '.',
 'arterial',
 'phase',
 'dynamic',
 'ct',
 'shows',
 'homogenous',
 'enhancement',
 'mass',
 '(',
 'arrow',
 ').',
 'level',
 ',',
 'normal',
 'right',
 'side',
 'adrenal',
 'gland',
 'visualized',
 '.',
 'angiogram',
 'showing',
 'pseudoaneurysm',
 '(',
 'arrow',
 ')',
 'formation',
 'proximal',
 'left',
 'superficial',
 'femoral',
 'artery',
 '.',
 'image',
 'ct',
 'fluoroscopic',
 'guidance',
 'rhizotomy',
 'demonstrates',
 'radiofrequency',
 'cannular',
 'tip',
 'junction',
 'superior',
 'articular',
 'process',
 'transverse',
 'process',
 '.',
 'bileteral',
 'styloid',
 'process',
 'elongation',
 'subject',
 'panoramic',
 'radiography',
 '.',
 'solid',
 '-',
 'cystic',
 'lesion',
 'thickened',
 'hyperechoic',
 'wall',
 '.',
 'region',
 'polycyclic',
 'solid',
 'structure',
 'wall',
 'lesion',
 ',',
 'color',
 'doppler',
 '(',
 'cdus',
 ')',
 'shows',
 'tortuous',
 'arterial',
 'vessels',
 'initial',
 'chest',
 'x',
 '-',
 'ray',
 'showing',
 'left',
 'tension',
 'pneumothorax',
 'shift',
 'mediastinum',
 'right',
 ',',
 'pleural',
 'effusion',
 'left',
 ',',
 'basal',
 'dorsolateral',
 'rib',
 'fractures',
 '.',
 'there',
 "'",
 's',
 'also',
 'air',
 'visible',
 'right',
 'diaphragm',
 '(',
 'arrow',
 ').',
 'large',
 'subcutaneous',
 'tributary',
 'pierces',
 'superficial',
 'fascia',
 'join',
 'lsv',
 'thigh',
 'region',
 '.',
 'brain',
 'magnetic',
 'resonance',
 'imaging',
 '(',
 'mri',
 ')',
 'gadolinium',
 'injection',
 'showed',
 'image',
 'axial',
 '(',
 'flair',
 'sequence',
 ')',
 'showing',
 'hyper',
 '-',
 'intensity',
 'lesions',
 'white',
 'matter',
 'frontal',
 'lobes',
 '.',
 'signal',
 'abnormality',
 'cortex',
 '.',
 'note',
 'mass',
 'effect',
 'ventricular',
 'cavities',
 'midline',
 'structures',
 '.',
 'dosimetric',
 'results',
 'obtained',
 'rapidarc',
 '.',
 'barium',
 'small',
 'bowel',
 'meal',
 'follow',
 'showing',
 'normal',
 'small',
 'large',
 'bowel',
 '.',
 'ct',
 'axial',
 'section',
 'shows',
 'multilocular',
 'expansile',
 'lytic',
 'lesion',
 'body',
 'mandible',
 'right',
 'side',
 'significant',
 'enhancing',
 'soft',
 'tissue',
 'matrix',
 'computed',
 'tomography',
 'obtained',
 '3',
 'weeks',
 'admission',
 'diagnosis',
 'aspiration',
 'pneumonia',
 'showed',
 'hepatic',
 'portal',
 'venous',
 'gas',
 'gas',
 'within',
 'wall',
 'stomach',
 'visualized',
 'portions',
 'upper',
 'abdomen',
 'postoperative',
 'day',
 '1',
 'chest',
 'radiograph',
 'reveals',
 'large',
 'left',
 'pneumothorax',
 '.',
 'left',
 'upper',
 'lobe',
 'squamous',
 'cell',
 'cancer',
 'showing',
 'broad',
 ',',
 'convex',
 'margin',
 'mediastinum',
 'ct',
 '(',
 'arrow',
 ');',
 'mediastinal',
 'pleural',
 'invasion',
 'surgery',
 'pathology',
 '(',
 't2',
 'tumor',
 ').',
 'ct',
 'scan',
 'thorax',
 'demonstrating',
 'necrotic',
 'paratracheal',
 'node',
 '.',
 'enhanced',
 'axial',
 'ct',
 'scan',
 'thorax',
 ',',
 'mediastinal',
 'window',
 ',',
 '58',
 '-',
 'year',
 '-',
 'old',
 'female',
 'presented',
 'bilateral',
 'vocal',
 'cord',
 'immobility',
 'unknown',
 'etiology',
 '.',
 'positive',
 'serum',
 'anti',
 '-',
 'hu',
 'antibody',
 ',',
 'highly',
 'associated',
 'small',
 'cell',
 'lung',
 'carcinoma',
 ',',
 'led',
 'repeat',
 'ct',
 'scan',
 '.',
 'arrow',
 'demonstrates',
 'enlarged',
 'level',
 '4r',
 'paratracheal',
 'lymph',
 'node',
 'central',
 'necrosis',
 '.',
 'see',
 'figure',
 '2',
 'pathologic',
 'description',
 'biopsy',
 'node',
 '.',
 'cortical',
 'bone',
 'changes',
 'rheumatoid',
 'arthritis',
 'classical',
 'radiography',
 'showing',
 'striation',
 'lamellation',
 'cortical',
 'bone',
 'phalanx',
 '.',
 'twelve',
 '-',
 'year',
 '-',
 'old',
 'boy',
 'presented',
 'nasopharyngeal',
 'angiofi',
 'broma',
 'diagnosed',
 'unilateral',
 'meningo',
 '-',
 'ophthalmic',
 'artery',
 'anomaly',
 '.',
 'computed',
 'tomography',
 'scan',
 'shows',
 'midline',
 'nasopharyngeal',
 'angiofi',
 'broma',
 '(',
 'black',
 'arrow',
 '),',
 'prominent',
 'right',
 '-',
 'side',
 'infiltration',
 'infratemporal',
 'fossa',
 '(',
 'white',
 'arrow',
 ').',
 'pelvis',
 'arthrogram',
 'showed',
 'defective',
 'ossification',
 'lateral',
 'acetabular',
 'corner',
 ',',
 'leaving',
 'significant',
 'cartilaginous',
 'anlage',
 'left',
 'anterior',
 'oblique',
 'common',
 'coronary',
 'artery',
 'branches',
 'critical',
 'disease',
 'proximal',
 'rca',
 ',',
 'mid',
 '/',
 'distal',
 'anomalous',
 'lcx',
 '.',
 'calculation',
 'inferior',
 'vena',
 'cava',
 'collapsibility',
 'index',
 '([',
 'a',
 '–',
 'b',
 ']/',
 'b',
 ')',
 '(%)',
 'using',
 'ultrasonography',
 'ct',
 'guided',
 'core',
 'biopsy',
 'infracolic',
 'omental',
 'cake',
 '.',
 'initial',
 'radiograph',
 'shows',
 'right']

In [14]:
from nltk.tokenize import TreebankWordTokenizer
tokenizer=TreebankWordTokenizer()
tokenizer.tokenize(text_input)

['coronal',
 'plain',
 'computed',
 'tomography',
 'image',
 'showing',
 'multiple',
 'large',
 'tumor',
 'masses',
 'edge',
 'enhancement',
 'inside',
 'abdominal',
 'cavity',
 'liver.',
 'axial',
 'source',
 'image',
 'intracranial',
 'magnetic',
 'resonance',
 'angiogram',
 'reveals',
 'abnormal',
 'arterial',
 'signal',
 'elevation',
 'left',
 'right',
 'cavernous',
 'sinuses',
 'consistent',
 'carotid',
 'cavernous',
 'fistula',
 ',',
 'indicated',
 'arrow.',
 'apical',
 'height',
 ',',
 'homogeneity',
 ',',
 'thickness',
 'mineral',
 'trioxide',
 'aggregate',
 'plug',
 'cto',
 'rca',
 '(',
 'closure',
 '2nd',
 'segment',
 ')',
 'venography',
 'shows',
 'large',
 'amount',
 'thrombogenesis',
 'femoropoplitea',
 'vein',
 'thrombolysis.',
 'postoperative',
 'decreased',
 'size',
 'cyst',
 'fetal',
 'aortic',
 'arch.',
 'solid',
 'arrow',
 'represents',
 'ascending',
 'aorta',
 'dotted',
 'arrow',
 'represents',
 'aortic',
 'arch',
 'distal',
 'ductus',
 'arteriosus.',
 'note',
 'aliasing',
 'ductal',
 'arch',
 'reflecting',
 'turbulent',
 'blood',
 'flow',
 'result',
 'external',
 'compression',
 'due',
 'mass-effect.',
 'abdominal',
 'computed',
 'tomography',
 'scan.',
 'arrow',
 'points',
 'likely',
 'cholecystocutaneous',
 'fistulous',
 'track.',
 'distension',
 'digestive',
 'avec',
 'niveaux',
 'hydro-aériques',
 'coliques',
 'et',
 'vacuité',
 'pelvienne',
 'panoramic',
 'x',
 'ray',
 'taken',
 'four',
 'years',
 'later',
 'showing',
 'unilocular',
 'radiolucent',
 'area',
 'left',
 'ramus.',
 'anteroposterior',
 'radiograph',
 'pelvis',
 'recent',
 'follow',
 'up.',
 'immediate',
 'postinjury',
 'magnetic',
 'resonance',
 'image',
 'demonstrating',
 'intact',
 'spinal',
 'cord',
 'canal',
 'cerebrospinal',
 'fluid',
 'signal',
 'surrounding',
 'spinal',
 'cord',
 'levels.',
 'arterial',
 'phase',
 'dynamic',
 'ct',
 'shows',
 'homogenous',
 'enhancement',
 'mass',
 '(',
 'arrow',
 ')',
 '.',
 'level',
 ',',
 'normal',
 'right',
 'side',
 'adrenal',
 'gland',
 'visualized.',
 'angiogram',
 'showing',
 'pseudoaneurysm',
 '(',
 'arrow',
 ')',
 'formation',
 'proximal',
 'left',
 'superficial',
 'femoral',
 'artery.',
 'image',
 'ct',
 'fluoroscopic',
 'guidance',
 'rhizotomy',
 'demonstrates',
 'radiofrequency',
 'cannular',
 'tip',
 'junction',
 'superior',
 'articular',
 'process',
 'transverse',
 'process.',
 'bileteral',
 'styloid',
 'process',
 'elongation',
 'subject',
 'panoramic',
 'radiography.',
 'solid-cystic',
 'lesion',
 'thickened',
 'hyperechoic',
 'wall.',
 'region',
 'polycyclic',
 'solid',
 'structure',
 'wall',
 'lesion',
 ',',
 'color',
 'doppler',
 '(',
 'cdus',
 ')',
 'shows',
 'tortuous',
 'arterial',
 'vessels',
 'initial',
 'chest',
 'x-ray',
 'showing',
 'left',
 'tension',
 'pneumothorax',
 'shift',
 'mediastinum',
 'right',
 ',',
 'pleural',
 'effusion',
 'left',
 ',',
 'basal',
 'dorsolateral',
 'rib',
 'fractures.',
 'there',
 "'s",
 'also',
 'air',
 'visible',
 'right',
 'diaphragm',
 '(',
 'arrow',
 ')',
 '.',
 'large',
 'subcutaneous',
 'tributary',
 'pierces',
 'superficial',
 'fascia',
 'join',
 'lsv',
 'thigh',
 'region.',
 'brain',
 'magnetic',
 'resonance',
 'imaging',
 '(',
 'mri',
 ')',
 'gadolinium',
 'injection',
 'showed',
 'image',
 'axial',
 '(',
 'flair',
 'sequence',
 ')',
 'showing',
 'hyper-intensity',
 'lesions',
 'white',
 'matter',
 'frontal',
 'lobes.',
 'signal',
 'abnormality',
 'cortex.',
 'note',
 'mass',
 'effect',
 'ventricular',
 'cavities',
 'midline',
 'structures.',
 'dosimetric',
 'results',
 'obtained',
 'rapidarc.',
 'barium',
 'small',
 'bowel',
 'meal',
 'follow',
 'showing',
 'normal',
 'small',
 'large',
 'bowel.',
 'ct',
 'axial',
 'section',
 'shows',
 'multilocular',
 'expansile',
 'lytic',
 'lesion',
 'body',
 'mandible',
 'right',
 'side',
 'significant',
 'enhancing',
 'soft',
 'tissue',
 'matrix',
 'computed',
 'tomography',
 'obtained',
 '3',
 'weeks',
 'admission',
 'diagnosis',
 'aspiration',
 'pneumonia',
 'showed',
 'hepatic',
 'portal',
 'venous',
 'gas',
 'gas',
 'within',
 'wall',
 'stomach',
 'visualized',
 'portions',
 'upper',
 'abdomen',
 'postoperative',
 'day',
 '1',
 'chest',
 'radiograph',
 'reveals',
 'large',
 'left',
 'pneumothorax.',
 'left',
 'upper',
 'lobe',
 'squamous',
 'cell',
 'cancer',
 'showing',
 'broad',
 ',',
 'convex',
 'margin',
 'mediastinum',
 'ct',
 '(',
 'arrow',
 ')',
 ';',
 'mediastinal',
 'pleural',
 'invasion',
 'surgery',
 'pathology',
 '(',
 't2',
 'tumor',
 ')',
 '.',
 'ct',
 'scan',
 'thorax',
 'demonstrating',
 'necrotic',
 'paratracheal',
 'node.',
 'enhanced',
 'axial',
 'ct',
 'scan',
 'thorax',
 ',',
 'mediastinal',
 'window',
 ',',
 '58-year-old',
 'female',
 'presented',
 'bilateral',
 'vocal',
 'cord',
 'immobility',
 'unknown',
 'etiology.',
 'positive',
 'serum',
 'anti-hu',
 'antibody',
 ',',
 'highly',
 'associated',
 'small',
 'cell',
 'lung',
 'carcinoma',
 ',',
 'led',
 'repeat',
 'ct',
 'scan.',
 'arrow',
 'demonstrates',
 'enlarged',
 'level',
 '4r',
 'paratracheal',
 'lymph',
 'node',
 'central',
 'necrosis.',
 'see',
 'figure',
 '2',
 'pathologic',
 'description',
 'biopsy',
 'node.',
 'cortical',
 'bone',
 'changes',
 'rheumatoid',
 'arthritis',
 'classical',
 'radiography',
 'showing',
 'striation',
 'lamellation',
 'cortical',
 'bone',
 'phalanx.',
 'twelve-year-old',
 'boy',
 'presented',
 'nasopharyngeal',
 'angiofi',
 'broma',
 'diagnosed',
 'unilateral',
 'meningo-ophthalmic',
 'artery',
 'anomaly.',
 'computed',
 'tomography',
 'scan',
 'shows',
 'midline',
 'nasopharyngeal',
 'angiofi',
 'broma',
 '(',
 'black',
 'arrow',
 ')',
 ',',
 'prominent',
 'right-side',
 'infiltration',
 'infratemporal',
 'fossa',
 '(',
 'white',
 'arrow',
 ')',
 '.',
 'pelvis',
 'arthrogram',
 'showed',
 'defective',
 'ossification',
 'lateral',
 'acetabular',
 'corner',
 ',',
 'leaving',
 'significant',
 'cartilaginous',
 'anlage',
 'left',
 'anterior',
 'oblique',
 'common',
 'coronary',
 'artery',
 'branches',
 'critical',
 'disease',
 'proximal',
 'rca',
 ',',
 'mid/distal',
 'anomalous',
 'lcx.',
 'calculation',
 'inferior',
 'vena',
 'cava',
 'collapsibility',
 'index',
 '(',
 '[',
 'a–b',
 ']',
 '/b',
 ')',
 '(',
 '%',
 ')',
 'using',
 'ultrasonography',
 'ct',
 'guided',
 'core',
 'biopsy',
 'infracolic',
 'omental',
 'cake.',
 'initial',
 'radiograph',
 'shows',
 'right']

In [16]:
from nltk.stem import PorterStemmer

In [17]:
stemming=PorterStemmer()

In [18]:
for word in captions:
  print(word+"---"+stemming.stem(word))

Streaming output truncated to the last 5000 lines.
:---:
 ---
n---n
o---o
t---t
e---e
 ---
p---p
e---e
r---r
i---i
v---v
e---e
n---n
t---t
r---r
i---i
c---c
u---u
l---l
a---a
r---r
 ---
h---h
y---y
p---p
e---e
r---r
i---i
n---n
t---t
e---e
n---n
s---s
i---i
t---t
i---i
e---e
s---s
 ---
i---i
n---n
 ---
r---r
e---e
l---l
a---a
t---t
i---i
o---o
n---n
 ---
w---w
i---i
t---t
h---h
 ---
c---c
s---s
f---f
 ---
r---r
e---e
s---s
o---o
r---r
p---p
t---t
i---i
o---o
n---n
.---.
 ---
 ---
r---r
a---a
d---d
i---i
o---o
g---g
r---r
a---a
p---p
h---h
 ---
s---s
h---h
o---o
w---w
i---i
n---n
g---g
 ---
t---t
r---r
o---o
n---n
z---z
o---o
 ---
t---t
y---y
p---p
e---e
 ---
v---v
 ---
t---t
r---r
a---a
n---n
s---s
t---t
r---r
o---o
c---c
h---h
a---a
n---n
t---t
e---e
r---r
i---i
c---c
 ---
f---f
r---r
a---a
c---c
t---t
u---u
r---r
e---e
.---.
 ---
 ---
m---m
a---a
g---g
n---n
e---e
t---t
i---i
c---c
 ---
r---r
e---e
s---s
o---o
n---n
a---a
n---n
c---c
e---e
 ---
i---i
m---m
a---a
g---g
e---e
.---.
p---p
r---r
e---e
o---o
p---p
e---e
r---r
a---a
t---t
i---i
v---v
e---e
 ---
m---m
a---a
g---g
n---n
e---e
t---t
i---i
c---c
 ---
r---r
e---e
s---s
o---o
n---n
a---a
n---n
c---c
e---e
 ---
i---i
m---m
a---a
g---g
i---i
n---n
g---g
 ---
s---s
h---h
o---o
w---w
e---e
d---d
 ---
a---a
 ---
w---w
e---e
l---l
l---l
-----
c---c
i---i
r---r
c---c
u---u
m---m
s---s
c---c
r---r
i---i
b---b
e---e
d---d
,---,
 ---
u---u
n---n
i---i
l---l
o---o
c---c
u---u
l---l
a---a
r---r
 ---
1---1
8---8
 ---
c---c
m---m
×---×
1---1
4---4
 ---
c---c
m---m
×---×
8---8
 ---
c---c
m---m
 ---
c---c
y---y
s---s
t---t
i---i
c---c
 ---
l---l
e---e
s---s
i---i
o---o
n---n
 ---
w---w
i---i
t---t
h---h
o---o
u---u
t---t
 ---
s---s
k---k
u---u
l---l
l---l
 ---
o---o
r---r
 ---
b---b
r---r
a---a
i---i
n---n
 ---
i---i
n---n
v---v
o---o
l---l
v---v
e---e
m---m
e---e
n---n
t---t
.---.
 ---
 ---
f---f
i---i
g---g
u---u
r---r
e---e
 ---
1---1
:---:
c---c
e---e
c---c
t---t
 ---
a---a
b---b
d---d
o---o
m---m
e---e
n---n
 ---
i---i
n---n
 ---
c---c
a---a
s---s
e---e
 ---
1---1
 ---
s---s
h---h
o---o
w---w
i---i
n---n
g---g
 ---
t---t
h---h
e---e
 ---
l---l
a---a
r---r
g---g
e---e
 ---
r---r
i---i
g---g
h---h
t---t
 ---
r---r
e---e
n---n
a---a
l---l
 ---
t---t
u---u
m---m
o---o
u---u
r---r
 ---
w---w
i---i
t---t
h---h
 ---
n---n
e---e
c---c
r---r
o---o
t---t
i---i
c---c
 ---
a---a
r---r
e---e
a---a
s---s
,---,
 ---
a---a
b---b
u---u
t---t
t---t
i---i
n---n
g---g
 ---
t---t
h---h
e---e
 ---
l---l
i---i
v---v
e---e
r---r
.---.
 ---
 ---
s---s
a---a
g---g
i---i
t---t
t---t
a---a
l---l
 ---
v---v
i---i
e---e
w---w
 ---
o---o
f---f
 ---
c---c
o---o
m---m
p---p
u---u
t---t
e---e
d---d
 ---
t---t
o---o
m---m
o---o
g---g
r---r
a---a
p---p
h---h
y---y
 ---
s---s
c---c
a---a
n---n
 ---
o---o
f---f
 ---
p---p
l---l
a---a
n---n
 ---
1---1
 ---
s---s
h---h
o---o
w---w
i---i
n---n
g---g
 ---
i---i
n---n
t---t
e---e
r---r
r---r
e---e
l---l
a---a
t---t
i---i
o---o
n---n
s---s
h---h
i---i
p---p
 ---
o---o
f---f
 ---
c---c
o---o
n---n
t---t
o---o
u---u
r---r
e---e
d---d
 ---
v---v
o---o
l---l
u---u
m---m
e---e
s---s
 ---
e---e
.---.
g---g
.---.
 ---
h---h
i---i
g---g
h---h
r---r
i---i
s---s
k---k
 ---
c---c
l---l
i---i
n---n
i---i
c---c
a---a
l---l
 ---
t---t
a---a
r---r
g---g
e---e
t---t
 ---
v---v
o---o
l---l
u---u
m---m
e---e
 ---
(---(
h---h
r---r
-----
c---c
t---t
v---v
)---)
 ---
(---(
b---b
r---r
o---o
w---w
n---n
)---)
,---,
 ---
i---i
n---n
t---t
e---e
r---r
m---m
e---e
d---d
i---i
a---a
t---t
e---e
 ---
r---r
i---i
s---s
k---k
 ---
c---c
l---l
i---i
n---n
i---i
c---c
a---a
l---l
 ---
t---t
a---a
r---r
g---g
e---e
t---t
 ---
v---v
o---o
l---l
u---u
m---m
e---e
 ---
(---(
i---i
r---r
-----
c---c
t---t
v---v
)---)
 ---
(---(
o---o
r---r
a---a
n---n
g---g
e---e
)---)
,---,
 ---
r---r
e---e
c---c
t---t
u---u
m---m
 ---
(---(
y---y
e---e
l---l
l---l
o---o
w---w
)---)
,---,
 ---
s---s
i---i
g---g
m---m
o---o
i---i
d---d
 ---
c---c
o---o
l---l
o---o
n---n
 ---
(---(
p---p
i---i
n---n
k---k
)---)
,---,
 ---
b---b
l---l
a---a
d---d
d---d
e---e
r---r
 ---
(---(
b---b
l---l
u---u
e---e
)---)
,---,
 ---
a---a
n---n
d---d
 ---
u---u
r---r
e---e
t---t
h---h
r---r
a---a
 ---
(---(
v---v
i---i
o---o
l---l
e---e
t---t
)---)
 ---
 ---
a---a
r---r
t---t
e---e
r---r
i---i
a---a
l---l
 ---
s---s
p---p
i---i
n---n
 ---
l---l
a---a
b---b
e---e
l---l
i---i
n---n
g---g
 ---
(---(
a---a
s---s
l---l
)---)
 ---
i---i
m---m
a---a
g---g
e---e
 ---
i---i
n---n
 ---
a---a
 ---
h---h
e---e
a---a
l---l
t---t
h---h
y---y
 ---
v---v
o---o
l---l
u---u
n---n
t---t
e---e
e---e
r---r
 ---
(---(
s---s
a---a
g---g
i---i
t---t
t---t
a---a
l---l
 ---
o---o
r---r
i---i
e---e
n---n
t---t
a---a
t---t
i---i
o---o
n---n
,---,
 ---
r---r
i---i
g---g
h---h
t---t
 ---
l---l
u---u
n---n
g---g
)---)
.---.
 ---
t---t
h---h
e---e
 ---
s---s
p---p
a---a
t---t
i---i
a---a
l---l
 ---
r---r
e---e
s---s
o---o
l---l
u---u
t---t
i---i
o---o
n---n
 ---
i---i
s---s
 ---
3---3
.---.
9---9
 ---
×---×
 ---
3---3
.---.
9---9
 ---
×---×
 ---
1---1
0---0
 ---
m---m
m---m
,---,
 ---
w---w
h---h
i---i
c---c
h---h
 ---
a---a
l---l
l---l
o---o
w---w
s---s
 ---
f---f
o---o
r---r
 ---
v---v
i---i
s---s
u---u
a---a
l---l
i---i
s---s
a---a
t---t
i---i
o---o
n---n
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
m---m
a---a
j---j
o---o
r---r
 ---
a---a
n---n
d---d
 ---
m---m
i---i
n---n
o---o
r---r
 ---
f---f
i---i
s---s
s---s
u---u
r---r
e---e
.---.
 ---
o---o
n---n
 ---
t---t
h---h
e---e
 ---
o---o
t---t
h---h
e---e
r---r
 ---
h---h
a---a
n---n
d---d
 ---
t---t
h---h
e---e
 ---
s---s
i---i
g---g
n---n
a---a
l---l
-----
t---t
o---o
-----
n---n
o---o
i---i
s---s
e---e
 ---
r---r
a---a
t---t
i---i
o---o
 ---
i---i
s---s
 ---
l---l
o---o
w---w
,---,
 ---
m---m
a---a
k---k
i---i
n---n
g---g
 ---
a---a
n---n
 ---
d---d
e---e
t---t
a---a
i---i
l---l
e---e
d---d
 ---
e---e
v---v
a---a
l---l
u---u
a---a
t---t
i---i
o---o
n---n
 ---
d---d
i---i
f---f
f---f
i---i
c---c
u---u
l---l
t---t
 ---
 ---
a---a
x---x
i---i
a---a
l---l
 ---
c---c
t---t
 ---
a---a
f---f
t---t
e---e
r---r
 ---
i---i
n---n
t---t
r---r
a---a
v---v
e---e
n---n
o---o
u---u
s---s
 ---
c---c
o---o
n---n
t---t
r---r
a---a
s---s
t---t
 ---
i---i
n---n
j---j
e---e
c---c
t---t
i---i
o---o
n---n
:---:
 ---
h---h
e---e
t---t
e---e
r---r
o---o
g---g
e---e
n---n
e---e
o---o
u---u
s---s
 ---
e---e
x---x
p---p
a---a
n---n
s---s
i---i
v---v
e---e
 ---
p---p
r---r
o---o
c---c
e---e
s---s
s---s
 ---
o---o
n---n
 ---
t---t
h---h
e---e
 ---
l---l
e---e
f---f
t---t
 ---
r---r
e---e
t---t
r---r
o---o
p---p
h---h
a---a
r---r
y---y
n---n
g---g
e---e
a---a
l---l
 ---
r---r
e---e
g---g
i---i
o---o
n---n
 ---
i---i
n---n
v---v
o---o
l---l
v---v
i---i
n---n
g---g
 ---
t---t
h---h
e---e
 ---
i---i
p---p
s---s
i---i
l---l
a---a
t---t
e---e
r---r
a---a
l---l
 ---
c---c
a---a
r---r
o---o
t---t
i---i
d---d
 ---
s---s
p---p
a---a
c---c
e---e
.---.
 ---
 ---
c---c
o---o
r---r
o---o
n---n
a---a
l---l
 ---
r---r
e---e
f---f
o---o
r---r
m---m
a---a
t---t
t---t
e---e
d---d
 ---
i---i
m---m
a---a
g---g
e---e
 ---
o---o
f---f
 ---
u---u
n---n
e---e
n---n
h---h
a---a
n---n
c---c
e---e
d---d
 ---
c---c
t---t
 ---
s---s
c---c
a---a
n---n
 ---
s---s
h---h
o---o
w---w
i---i
n---n
g---g
 ---
t---t
h---h
e---e
 ---
t---t
y---y
p---p
i---i
c---c
a---a
l---l
 ---
l---l
o---o
w---w
 ---
d---d
e---e
n---n
s---s
i---i
t---t
y---y
 ---
a---a
n---n
d---d
 ---
n---n
e---e
g---g
a---a
t---t
i---i
v---v
e---e
 ---
a---a
t---t
t---t
e---e
n---n
u---u
a---a
t---t
i---i
o---o
n---n
 ---
(---(
–---–
1---1
9---9
 ---
h---h
u---u
)---)
 ---
o---o
f---f
 ---
a---a
 ---
r---r
i---i
g---g
h---h
t---t
 ---
a---a
d---d
r---r
e---e
n---n
a---a
l---l
 ---
m---m
a---a
s---s
s---s
 ---
w---w
i---i
t---t
h---h
 ---
h---h
y---y
p---p
e---e
r---r
d---d
e---e
n---n
s---s
e---e
 ---
f---f
o---o
c---c
i---i
 ---
o---o
f---f
 ---
c---c
a---a
l---l
c---c
i---i
f---f
i---i
c---c
a---a
t---t
i---i
o---o
n---n
.---.
 ---
 ---
c---c
t---t
 ---
s---s
c---c
a---a
n---n
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
a---a
b---b
d---d
o---o
m---m
e---e
n---n
 ---
o---o
n---n
 ---
p---p
a---a
t---t
i---i
e---e
n---n
t---t
 ---
p---p
r---r
e---e
s---s
e---e
n---n
t---t
a---a
t---t
i---i
o---o
n---n
 ---
d---d
e---e
m---m
o---o
n---n
s---s
t---t
r---r
a---a
t---t
i---i
n---n
g---g
 ---
p---p
n---n
e---e
u---u
m---m
o---o
b---b
i---i
l---l
i---i
a---a
 ---
a---a
n---n
d---d
 ---
p---p
n---n
e---e
u---u
m---m
o---o
p---p
e---e
r---r
i---i
t---t
o---o
n---n
e---e
u---u
m---m
 ---
a---a
n---n
t---t
e---e
r---r
i---i
o---o
r---r
 ---
t---t
o---o
 ---
t---t
h---h
e---e
 ---
l---l
i---i
v---v
e---e
r---r
 ---
 ---
2---2
2---2
-----
o---o
l---l
d---d
-----
y---y
e---e
a---a
r---r
 ---
m---m
a---a
l---l
e---e
 ---
w---w
i---i
t---t
h---h
 ---
p---p
a---a
i---i
n---n
 ---
a---a
n---n
d---d
 ---
t---t
e---e
n---n
d---d
e---e
r---r
n---n
e---e
s---s
s---s
 ---
i---i
n---n
 ---
t---t
h---h
e---e
 ---
r---r
i---i
g---g
h---h
t---t
 ---
m---m
a---a
x---x
i---i
l---l
l---l
a---a
r---r
y---y
 ---
l---l
a---a
t---t
e---e
r---r
a---a
l---l
 ---
i---i
n---n
c---c
i---i
s---s
o---o
r---r
 ---
d---d
i---i
a---a
g---g
n---n
o---o
s---s
e---e
d---d
 ---
w---w
i---i
t---t
h---h
 ---
d---d
e---e
n---n
s---s
 ---
i---i
n---n
v---v
a---a
g---g
i---i
n---n
a---a
t---t
u---u
s---s
 ---
t---t
y---y
p---p
e---e
 ---
2---2
 ---
i---i
n---n
 ---
t---t
o---o
o---o
t---t
h---h
 ---
2---2
2---2
 ---
a---a
n---n
d---d
 ---
d---d
o---o
u---u
b---b
l---l
e---e
 ---
d---d
e---e
n---n
s---s
 ---
i---i
n---n
v---v
a---a
g---g
i---i
n---n
a---a
t---t
u---u
s---s
 ---
i---i
n---n
 ---
t---t
o---o
o---o
t---t
h---h
 ---
1---1
2---2
.---.
 ---
i---i
n---n
t---t
r---r
a---a
-----
o---o
r---r
a---a
l---l
 ---
r---r
a---a
d---d
i---i
o---o
g---g
r---r
a---a
p---p
h---h
 ---
o---o
f---f
 ---
t---t
o---o
o---o
t---t
h---h
 ---
1---1
2---2
 ---
s---s
h---h
o---o
w---w
s---s
 ---
t---t
h---h
e---e
 ---
d---d
o---o
u---u
b---b
l---l
e---e
 ---
d---d
e---e
n---n
s---s
 ---
i---i
n---n
v---v
a---a
g---g
i---i
n---n
a---a
t---t
u---u
s---s
 ---
a---a
n---n
d---d
 ---
t---t
h---h
e---e
 ---
p---p
r---r
e---e
s---s
e---e
n---n
c---c
e---e
 ---
o---o
f---f
 ---
t---t
w---w
o---o
 ---
e---e
n---n
a---a
m---m
e---e
l---l
 ---
l---l
i---i
n---n
e---e
d---d
 ---
i---i
n---n
v---v
a---a
g---g
i---i
n---n
a---a
t---t
i---i
o---o
n---n
s---s
 ---
(---(
a---a
r---r
r---r
o---o
w---w
s---s
)---)
.---.
 ---
 ---
l---l
a---a
t---t
e---e
r---r
a---a
l---l
 ---
v---v
i---i
e---e
w---w
 ---
s---s
h---h
o---o
w---w
i---i
n---n
g---g
 ---
s---s
i---i
n---n
g---g
l---l
e---e
 ---
f---f
e---e
m---m
u---u
r---r
 ---
a---a
n---n
d---d
 ---
t---t
i---i
b---b
i---i
a---a
 ---
 ---
a---a
n---n
g---g
i---i
o---o
g---g
r---r
a---a
m---m
 ---
o---o
f---f
 ---
l---l
e---e
f---f
t---t
 ---
a---a
n---n
t---t
e---e
r---r
i---i
o---o
r---r
 ---
d---d
e---e
s---s
c---c
e---e
n---n
d---d
i---i
n---n
g---g
 ---
c---c
o---o
r---r
o---o
n---n
a---a
r---r
y---y
 ---
a---a
r---r
t---t
e---e
r---r
y---y
 ---
d---d
e---e
m---m
o---o
n---n
s---s
t---t
r---r
a---a
t---t
i---i
n---n
g---g
 ---
8---8
0---0
%---%
 ---
s---s
t---t
e---e
n---n
o---o
s---s
i---i
s---s
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
p---p
r---r
o---o
x---x
i---i
m---m
a---a
l---l
 ---
s---s
e---e
g---g
m---m
e---e
n---n
t---t
 ---
(---(
b---b
l---l
a---a
c---c
k---k
 ---
a---a
r---r
r---r
o---o
w---w
)---)
.---.
 ---
 ---
c---c
t---t
 ---
i---i
m---m
a---a
g---g
i---i
n---n
g---g
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
b---b
a---a
l---l
l---l
o---o
o---o
n---n
i---i
n---n
g---g
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
c---c
y---y
s---s
t---t
 ---
a---a
f---f
t---t
e---e
r---r
 ---
b---b
i---i
r---r
t---t
h---h
.---.
 ---
 ---
x---x
-----
r---r
a---a
y---y
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
a---a
n---n
k---k
l---l
e---e
 ---
i---i
n---n
 ---
l---l
a---a
t---t
e---e
r---r
a---a
l---l
 ---
v---v
i---i
e---e
w---w
 ---
s---s
h---h
o---o
w---w
s---s
 ---
t---t
h---h
e---e
 ---
a---a
n---n
g---g
l---l
e---e
 ---
o---o
f---f
 ---
g---g
i---i
s---s
s---s
a---a
n---n
e---e
.---.
 ---
 ---
f---f
o---o
l---l
l---l
o---o
w---w
-----
u---u
p---p
 ---
r---r
a---a
d---d
i---i
o---o
g---g
r---r
a---a
p---p
h---h
 ---
a---a
t---t
 ---
3---3
 ---
y---y
e---e
a---a
r---r
s---s
 ---
a---a
n---n
d---d
 ---
6---6
 ---
m---m
o---o
n---n
t---t
h---h
s---s
 ---
p---p
o---o
s---s
t---t
-----
s---s
u---u
r---r
g---g
e---e
r---r
y---y
.---.
 ---
t---t
h---h
e---e
 ---
r---r
a---a
d---d
i---i
o---o
g---g
r---r
a---a
p---p
h---h
 ---
s---s
h---h
o---o
w---w
s---s
 ---
g---g
o---o
o---o
d---d
 ---
r---r
e---e
m---m
o---o
d---d
e---e
l---l
i---i
n---n
g---g
 ---
a---a
n---n
d---d
 ---
n---n
o---o
 ---
i---i
n---n
v---v
o---o
l---l
v---v
e---e
m---m
e---e
n---n
t---t
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
h---h
i---i
p---p
 ---
j---j
o---o
i---i
n---n
t---t
.---.
 ---
 ---
c---c
o---o
n---n
t---t
r---r
a---a
s---s
t---t
 ---
r---r
a---a
d---d
i---i
o---o
g---g
r---r
a---a
p---p
h---h
y---y
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
b---b
i---i
l---l
i---i
a---a
r---r
y---y
 ---
t---t
r---r
a---a
c---c
t---t
 ---
b---b
y---y
 ---
p---p
t---t
g---g
b---b
d---d
 ---
s---s
h---h
o---o
w---w
e---e
d---d
 ---
g---g
a---a
l---l
l---l
b---b
l---l
a---a
d---d
d---d
e---e
r---r
 ---
s---s
t---t
o---o
n---n
e---e
s---s
 ---
(---(
a---a
r---r
r---r
o---o
w---w
h---h
e---e
a---a
d---d
)---)
 ---
a---a
n---n
d---d
 ---
c---c
o---o
m---m
m---m
o---o
n---n
 ---
b---b
i---i
l---l
e---e
 ---
d---d
u---u
c---c
t---t
 ---
s---s
t---t
o---o
n---n
e---e
s---s
 ---
(---(
a---a
r---r
r---r
o---o
w---w
)---)
.---.
 ---
 ---
c---c
o---o
m---m
p---p
e---e
n---n
s---s
a---a
t---t
e---e
d---d
 ---
c---c
o---o
n---n
g---g
e---e
n---n
i---i
t---t
a---a
l---l
 ---
s---s
c---c
o---o
l---l
i---i
o---o
s---s
i---i
s---s
 ---
–---–
 ---
2---2
 ---
a---a
l---l
t---t
e---e
r---r
n---n
a---a
n---n
t---t
 ---
h---h
e---e
m---m
i---i
v---v
e---e
r---r
t---t
e---e
b---b
r---r
a---a
e---e
:---:
 ---
t---t
6---6
 ---
a---a
n---n
d---d
 ---
t---t
9---9
 ---
w---w
i---i
t---t
h---h
 ---
2---2
 ---
n---n
o---o
r---r
m---m
a---a
l---l
 ---
v---v
e---e
r---r
t---t
e---e
b---b
r---r
a---a
e---e
 ---
b---b
e---e
t---t
w---w
e---e
e---e
n---n
 ---
t---t
h---h
e---e
m---m
 ---
 ---
m---m
a---a
m---m
m---m
o---o
g---g
r---r
a---a
p---p
h---h
y---y
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
l---l
e---e
f---f
t---t
 ---
b---b
r---r
e---e
a---a
s---s
t---t
 ---
s---s
h---h
o---o
w---w
i---i
n---n
g---g
 ---
a---a
 ---
c---c
o---o
n---n
f---f
i---i
n---n
e---e
d---d
 ---
d---d
e---e
n---n
s---s
i---i
t---t
y---y
 ---
i---i
n---n
 ---
t---t
h---h
e---e
 ---
r---r
e---e
t---t
r---r
o---o
a---a
r---r
e---e
o---o
l---l
a---a
r---r
 ---
a---a
r---r
e---e
a---a
.---.
 ---
 ---
c---c
h---h
e---e
s---s
t---t
 ---
x---x
-----
r---r
a---a
y---y
 ---
s---s
h---h
o---o
w---w
i---i
n---n
g---g
 ---
t---t
h---h
e---e
 ---
p---p
o---o
r---r
t---t
 ---
i---i
n---n
 ---
c---c
o---o
r---r
r---r
e---e
c---c
t---t
 ---
p---p
o---o
s---s
i---i
t---t
i---i
o---o
n---n
 ---
w---w
h---h
i---i
l---l
e---e
 ---
t---t
h---h
e---e
 ---
c---c
a---a
t---t
h---h
e---e
t---t
e---e
r---r
 ---
i---i
s---s
 ---
n---n
o---o
t---t
 ---
s---s
h---h
o---o
w---w
n---n
 ---
h---h
e---e
r---r
e---e
.---.
 ---
t---t
h---h
e---e
 ---
c---c
a---a
t---t
h---h
e---e
t---t
e---e
r---r
 ---
h---h
a---a
d---d
 ---
m---m
o---o
v---v
e---e
d---d
 ---
i---i
n---n
 ---
t---t
h---h
e---e
 ---
r---r
i---i
g---g
h---h
t---t
 ---
a---a
t---t
r---r
i---i
u---u
m---m
,---,
 ---
f---f
r---r
o---o
m---m
 ---
w---w
h---h
e---e
r---r
e---e
 ---
i---i
t---t
 ---
w---w
a---a
s---s
 ---
r---r
e---e
m---m
o---o
v---v
e---e
d---d
 ---
f---f
l---l
u---u
o---o
r---r
o---o
s---s
c---c
o---o
p---p
i---i
c---c
a---a
l---l
l---l
y---y
.---.
 ---
 ---
b---b
a---a
r---r
i---i
u---u
m---m
 ---
e---e
s---s
o---o
p---p
h---h
a---a
g---g
o---o
g---g
r---r
a---a
m---m
 ---
s---s
h---h
o---o
w---w
i---i
n---n
g---g
 ---
m---m
a---a
r---r
k---k
e---e
d---d
 ---
l---l
u---u
m---m
i---i
n---n
a---a
l---l
 ---
n---n
a---a
r---r
r---r
o---o
w---w
i---i
n---n
g---g
 ---
a---a
t---t
 ---
t---t
h---h
e---e
 ---
g---g
a---a
s---s
t---t
r---r
o---o
e---e
s---s
o---o
p---p
h---h
a---a
g---g
e---e
a---a
l---l
 ---
j---j
u---u
n---n
c---c
t---t
i---i
o---o
n---n
 ---
w---w
i---i
t---t
h---h
 ---
b---b
i---i
r---r
d---d
 ---
b---b
e---e
a---a
k---k
 ---
c---c
o---o
n---n
f---f
i---i
g---g
u---u
r---r
a---a
t---t
i---i
o---o
n---n
,---,
 ---
c---c
o---o
n---n
s---s
i---i
s---s
t---t
e---e
n---n
t---t
 ---
w---w
i---i
t---t
h---h
 ---
a---a
c---c
h---h
a---a
l---l
a---a
s---s
i---i
a---a
.---.
 ---
 ---
u---u
n---n
e---e
n---n
h---h
a---a
n---n
c---c
e---e
d---d
 ---
c---c
t---t
:---:
 ---
s---s
e---e
v---v
e---e
r---r
e---e
 ---
s---s
c---c
o---o
l---l
i---i
o---o
s---s
i---i
s---s
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
l---l
u---u
m---m
b---b
a---a
r---r
 ---
s---s
p---p
i---i
n---n
e---e
 ---
a---a
n---n
d---d
 ---
d---d
i---i
s---s
p---p
l---l
a---a
c---c
e---e
m---m
e---e
n---n
t---t
 ---
a---a
n---n
d---d
 ---
h---h
o---o
r---r
i---i
z---z
o---o
n---n
t---t
a---a
l---l
 ---
t---t
o---o
r---r
s---s
i---i
o---o
n---n
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
l---l
e---e
f---f
t---t
 ---
k---k
i---i
d---d
n---n
e---e
y---y
 ---
t---t
o---o
 ---
t---t
h---h
e---e
 ---
m---m
i---i
d---d
l---l
i---i
n---n
e---e
 ---
(---(
f---f
i---i
n---n
e---e
 ---
a---a
r---r
r---r
o---o
w---w
)---)
.---.
 ---
m---m
a---a
r---r
k---k
e---e
d---d
 ---
d---d
i---i
l---l
a---a
t---t
a---a
t---t
i---i
o---o
n---n
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
p---p
e---e
l---l
v---v
i---i
c---c
a---a
l---l
i---i
c---c
e---e
a---a
l---l
 ---
s---s
y---y
s---s
t---t
e---e
m---m
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
l---l
e---e
f---f
t---t
 ---
k---k
i---i
d---d
n---n
e---e
y---y
 ---
(---(
t---t
h---h
i---i
c---c
k---k
 ---
a---a
r---r
r---r
o---o
w---w
)---)
;---;
 ---
n---n
o---o
 ---
d---d
i---i
l---l
a---a
t---t
e---e
d---d
 ---
u---u
r---r
e---e
t---t
e---e
r---r
.---.
 ---
n---n
o---o
r---r
m---m
a---a
l---l
 ---
p---p
o---o
s---s
i---i
t---t
i---i
o---o
n---n
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
r---r
i---i
g---g
h---h
t---t
 ---
k---k
i---i
d---d
n---n
e---e
y---y
;---;
 ---
n---n
o---o
 ---
d---d
i---i
l---l
a---a
t---t
a---a
t---t
i---i
o---o
n---n
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
e---e
x---x
c---c
r---r
e---e
t---t
o---o
r---r
y---y
 ---
s---s
y---y
s---s
t---t
e---e
m---m
.---.
 ---
 ---
t---t
r---r
a---a
n---n
s---s
t---t
h---h
o---o
r---r
a---a
c---c
i---i
c---c
 ---
e---e
c---c
h---h
o---o
c---c
a---a
r---r
d---d
i---i
o---o
g---g
r---r
a---a
m---m
:---:
 ---
a---a
p---p
i---i
c---c
a---a
l---l
 ---
f---f
o---o
u---u
r---r
‐---‐
c---c
h---h
a---a
m---m
b---b
e---e
r---r
 ---
v---v
i---i
e---e
w---w
 ---
w---w
i---i
t---t
h---h
 ---
f---f
o---o
c---c
u---u
s---s
 ---
o---o
n---n
 ---
t---t
h---h
e---e
 ---
r---r
i---i
g---g
h---h
t---t
 ---
a---a
t---t
r---r
i---i
u---u
m---m
.---.
 ---
 ---
a---a
n---n
 ---
a---a
x---x
i---i
a---a
l---l
 ---
t---t
2---2
 ---
m---m
r---r
i---i
 ---
s---s
h---h
o---o
w---w
i---i
n---n
g---g
 ---
t---t
h---h
e---e
 ---
f---f
a---a
t---t
t---t
y---y
 ---
a---a
t---t
r---r
o---o
p---p
h---h
y---y
 ---
a---a
n---n
d---d
 ---
r---r
e---e
t---t
r---r
a---a
c---c
t---t
i---i
o---o
n---n
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
r---r
i---i
g---g
h---h
t---t
 ---
i---i
l---l
i---i
o---o
-----
p---p
s---s
o---o
a---a
s---s
 ---
t---t
e---e
n---n
d---d
o---o
n---n
 ---
(---(
a---a
r---r
r---r
o---o
w---w
)---)
 ---
a---a
l---l
l---l
 ---
t---t
h---h
e---e
 ---
w---w
a---a
y---y
 ---
t---t
o---o
 ---
t---t
h---h
e---e
 ---
l---l
e---e
v---v
e---e
l---l
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
s---s
a---a
c---c
r---r
o---o
-----
i---i
l---l
i---i
a---a
c---c
 ---
j---j
o---o
i---i
n---n
t---t
.---.
 ---
 ---
c---c
r---r
a---a
n---n
i---i
a---a
l---l
 ---
c---c
o---o
m---m
p---p
u---u
t---t
e---e
d---d
 ---
t---t
o---o
m---m
o---o
g---g
r---r
a---a
p---p
h---h
y---y
 ---
s---s
h---h
o---o
w---w
s---s
 ---
l---l
o---o
c---c
a---a

In [19]:
from nltk.stem import RegexpStemmer

In [22]:
reg_stemmer=RegexpStemmer("tion$|e$|s$|able$|graphy$")

In [23]:
reg_stemmer.stem("calculation")

'calcula'

In [24]:
from nltk.stem import SnowballStemmer

In [25]:
snowballstemmer=SnowballStemmer('english')

In [26]:
for word in captions:
  print(word+"---"+snowballstemmer.stem(word))

Streaming output truncated to the last 5000 lines.
:---:
 ---
n---n
o---o
t---t
e---e
 ---
p---p
e---e
r---r
i---i
v---v
e---e
n---n
t---t
r---r
i---i
c---c
u---u
l---l
a---a
r---r
 ---
h---h
y---y
p---p
e---e
r---r
i---i
n---n
t---t
e---e
n---n
s---s
i---i
t---t
i---i
e---e
s---s
 ---
i---i
n---n
 ---
r---r
e---e
l---l
a---a
t---t
i---i
o---o
n---n
 ---
w---w
i---i
t---t
h---h
 ---
c---c
s---s
f---f
 ---
r---r
e---e
s---s
o---o
r---r
p---p
t---t
i---i
o---o
n---n
.---.
 ---
 ---
r---r
a---a
d---d
i---i
o---o
g---g
r---r
a---a
p---p
h---h
 ---
s---s
h---h
o---o
w---w
i---i
n---n
g---g
 ---
t---t
r---r
o---o
n---n
z---z
o---o
 ---
t---t
y---y
p---p
e---e
 ---
v---v
 ---
t---t
r---r
a---a
n---n
s---s
t---t
r---r
o---o
c---c
h---h
a---a
n---n
t---t
e---e
r---r
i---i
c---c
 ---
f---f
r---r
a---a
c---c
t---t
u---u
r---r
e---e
.---.
 ---
 ---
m---m
a---a
g---g
n---n
e---e
t---t
i---i
c---c
 ---
r---r
e---e
s---s
o---o
n---n
a---a
n---n
c---c
e---e
 ---
i---i
m---m
a---a
g---g
e---e
.---.
p---p
r---r
e---e
o---o
p---p
e---e
r---r
a---a
t---t
i---i
v---v
e---e
 ---
m---m
a---a
g---g
n---n
e---e
t---t
i---i
c---c
 ---
r---r
e---e
s---s
o---o
n---n
a---a
n---n
c---c
e---e
 ---
i---i
m---m
a---a
g---g
i---i
n---n
g---g
 ---
s---s
h---h
o---o
w---w
e---e
d---d
 ---
a---a
 ---
w---w
e---e
l---l
l---l
-----
c---c
i---i
r---r
c---c
u---u
m---m
s---s
c---c
r---r
i---i
b---b
e---e
d---d
,---,
 ---
u---u
n---n
i---i
l---l
o---o
c---c
u---u
l---l
a---a
r---r
 ---
1---1
8---8
 ---
c---c
m---m
×---×
1---1
4---4
 ---
c---c
m---m
×---×
8---8
 ---
c---c
m---m
 ---
c---c
y---y
s---s
t---t
i---i
c---c
 ---
l---l
e---e
s---s
i---i
o---o
n---n
 ---
w---w
i---i
t---t
h---h
o---o
u---u
t---t
 ---
s---s
k---k
u---u
l---l
l---l
 ---
o---o
r---r
 ---
b---b
r---r
a---a
i---i
n---n
 ---
i---i
n---n
v---v
o---o
l---l
v---v
e---e
m---m
e---e
n---n
t---t
.---.
 ---
 ---
f---f
i---i
g---g
u---u
r---r
e---e
 ---
1---1
:---:
c---c
e---e
c---c
t---t
 ---
a---a
b---b
d---d
o---o
m---m
e---e
n---n
 ---
i---i
n---n
 ---
c---c
a---a
s---s
e---e
 ---
1---1
 ---
s---s
h---h
o---o
w---w
i---i
n---n
g---g
 ---
t---t
h---h
e---e
 ---
l---l
a---a
r---r
g---g
e---e
 ---
r---r
i---i
g---g
h---h
t---t
 ---
r---r
e---e
n---n
a---a
l---l
 ---
t---t
u---u
m---m
o---o
u---u
r---r
 ---
w---w
i---i
t---t
h---h
 ---
n---n
e---e
c---c
r---r
o---o
t---t
i---i
c---c
 ---
a---a
r---r
e---e
a---a
s---s
,---,
 ---
a---a
b---b
u---u
t---t
t---t
i---i
n---n
g---g
 ---
t---t
h---h
e---e
 ---
l---l
i---i
v---v
e---e
r---r
.---.
 ---
 ---
s---s
a---a
g---g
i---i
t---t
t---t
a---a
l---l
 ---
v---v
i---i
e---e
w---w
 ---
o---o
f---f
 ---
c---c
o---o
m---m
p---p
u---u
t---t
e---e
d---d
 ---
t---t
o---o
m---m
o---o
g---g
r---r
a---a
p---p
h---h
y---y
 ---
s---s
c---c
a---a
n---n
 ---
o---o
f---f
 ---
p---p
l---l
a---a
n---n
 ---
1---1
 ---
s---s
h---h
o---o
w---w
i---i
n---n
g---g
 ---
i---i
n---n
t---t
e---e
r---r
r---r
e---e
l---l
a---a
t---t
i---i
o---o
n---n
s---s
h---h
i---i
p---p
 ---
o---o
f---f
 ---
c---c
o---o
n---n
t---t
o---o
u---u
r---r
e---e
d---d
 ---
v---v
o---o
l---l
u---u
m---m
e---e
s---s
 ---
e---e
.---.
g---g
.---.
 ---
h---h
i---i
g---g
h---h
r---r
i---i
s---s
k---k
 ---
c---c
l---l
i---i
n---n
i---i
c---c
a---a
l---l
 ---
t---t
a---a
r---r
g---g
e---e
t---t
 ---
v---v
o---o
l---l
u---u
m---m
e---e
 ---
(---(
h---h
r---r
-----
c---c
t---t
v---v
)---)
 ---
(---(
b---b
r---r
o---o
w---w
n---n
)---)
,---,
 ---
i---i
n---n
t---t
e---e
r---r
m---m
e---e
d---d
i---i
a---a
t---t
e---e
 ---
r---r
i---i
s---s
k---k
 ---
c---c
l---l
i---i
n---n
i---i
c---c
a---a
l---l
 ---
t---t
a---a
r---r
g---g
e---e
t---t
 ---
v---v
o---o
l---l
u---u
m---m
e---e
 ---
(---(
i---i
r---r
-----
c---c
t---t
v---v
)---)
 ---
(---(
o---o
r---r
a---a
n---n
g---g
e---e
)---)
,---,
 ---
r---r
e---e
c---c
t---t
u---u
m---m
 ---
(---(
y---y
e---e
l---l
l---l
o---o
w---w
)---)
,---,
 ---
s---s
i---i
g---g
m---m
o---o
i---i
d---d
 ---
c---c
o---o
l---l
o---o
n---n
 ---
(---(
p---p
i---i
n---n
k---k
)---)
,---,
 ---
b---b
l---l
a---a
d---d
d---d
e---e
r---r
 ---
(---(
b---b
l---l
u---u
e---e
)---)
,---,
 ---
a---a
n---n
d---d
 ---
u---u
r---r
e---e
t---t
h---h
r---r
a---a
 ---
(---(
v---v
i---i
o---o
l---l
e---e
t---t
)---)
 ---
 ---
a---a
r---r
t---t
e---e
r---r
i---i
a---a
l---l
 ---
s---s
p---p
i---i
n---n
 ---
l---l
a---a
b---b
e---e
l---l
i---i
n---n
g---g
 ---
(---(
a---a
s---s
l---l
)---)
 ---
i---i
m---m
a---a
g---g
e---e
 ---
i---i
n---n
 ---
a---a
 ---
h---h
e---e
a---a
l---l
t---t
h---h
y---y
 ---
v---v
o---o
l---l
u---u
n---n
t---t
e---e
e---e
r---r
 ---
(---(
s---s
a---a
g---g
i---i
t---t
t---t
a---a
l---l
 ---
o---o
r---r
i---i
e---e
n---n
t---t
a---a
t---t
i---i
o---o
n---n
,---,
 ---
r---r
i---i
g---g
h---h
t---t
 ---
l---l
u---u
n---n
g---g
)---)
.---.
 ---
t---t
h---h
e---e
 ---
s---s
p---p
a---a
t---t
i---i
a---a
l---l
 ---
r---r
e---e
s---s
o---o
l---l
u---u
t---t
i---i
o---o
n---n
 ---
i---i
s---s
 ---
3---3
.---.
9---9
 ---
×---×
 ---
3---3
.---.
9---9
 ---
×---×
 ---
1---1
0---0
 ---
m---m
m---m
,---,
 ---
w---w
h---h
i---i
c---c
h---h
 ---
a---a
l---l
l---l
o---o
w---w
s---s
 ---
f---f
o---o
r---r
 ---
v---v
i---i
s---s
u---u
a---a
l---l
i---i
s---s
a---a
t---t
i---i
o---o
n---n
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
m---m
a---a
j---j
o---o
r---r
 ---
a---a
n---n
d---d
 ---
m---m
i---i
n---n
o---o
r---r
 ---
f---f
i---i
s---s
s---s
u---u
r---r
e---e
.---.
 ---
o---o
n---n
 ---
t---t
h---h
e---e
 ---
o---o
t---t
h---h
e---e
r---r
 ---
h---h
a---a
n---n
d---d
 ---
t---t
h---h
e---e
 ---
s---s
i---i
g---g
n---n
a---a
l---l
-----
t---t
o---o
-----
n---n
o---o
i---i
s---s
e---e
 ---
r---r
a---a
t---t
i---i
o---o
 ---
i---i
s---s
 ---
l---l
o---o
w---w
,---,
 ---
m---m
a---a
k---k
i---i
n---n
g---g
 ---
a---a
n---n
 ---
d---d
e---e
t---t
a---a
i---i
l---l
e---e
d---d
 ---
e---e
v---v
a---a
l---l
u---u
a---a
t---t
i---i
o---o
n---n
 ---
d---d
i---i
f---f
f---f
i---i
c---c
u---u
l---l
t---t
 ---
 ---
a---a
x---x
i---i
a---a
l---l
 ---
c---c
t---t
 ---
a---a
f---f
t---t
e---e
r---r
 ---
i---i
n---n
t---t
r---r
a---a
v---v
e---e
n---n
o---o
u---u
s---s
 ---
c---c
o---o
n---n
t---t
r---r
a---a
s---s
t---t
 ---
i---i
n---n
j---j
e---e
c---c
t---t
i---i
o---o
n---n
:---:
 ---
h---h
e---e
t---t
e---e
r---r
o---o
g---g
e---e
n---n
e---e
o---o
u---u
s---s
 ---
e---e
x---x
p---p
a---a
n---n
s---s
i---i
v---v
e---e
 ---
p---p
r---r
o---o
c---c
e---e
s---s
s---s
 ---
o---o
n---n
 ---
t---t
h---h
e---e
 ---
l---l
e---e
f---f
t---t
 ---
r---r
e---e
t---t
r---r
o---o
p---p
h---h
a---a
r---r
y---y
n---n
g---g
e---e
a---a
l---l
 ---
r---r
e---e
g---g
i---i
o---o
n---n
 ---
i---i
n---n
v---v
o---o
l---l
v---v
i---i
n---n
g---g
 ---
t---t
h---h
e---e
 ---
i---i
p---p
s---s
i---i
l---l
a---a
t---t
e---e
r---r
a---a
l---l
 ---
c---c
a---a
r---r
o---o
t---t
i---i
d---d
 ---
s---s
p---p
a---a
c---c
e---e
.---.
 ---
 ---
c---c
o---o
r---r
o---o
n---n
a---a
l---l
 ---
r---r
e---e
f---f
o---o
r---r
m---m
a---a
t---t
t---t
e---e
d---d
 ---
i---i
m---m
a---a
g---g
e---e
 ---
o---o
f---f
 ---
u---u
n---n
e---e
n---n
h---h
a---a
n---n
c---c
e---e
d---d
 ---
c---c
t---t
 ---
s---s
c---c
a---a
n---n
 ---
s---s
h---h
o---o
w---w
i---i
n---n
g---g
 ---
t---t
h---h
e---e
 ---
t---t
y---y
p---p
i---i
c---c
a---a
l---l
 ---
l---l
o---o
w---w
 ---
d---d
e---e
n---n
s---s
i---i
t---t
y---y
 ---
a---a
n---n
d---d
 ---
n---n
e---e
g---g
a---a
t---t
i---i
v---v
e---e
 ---
a---a
t---t
t---t
e---e
n---n
u---u
a---a
t---t
i---i
o---o
n---n
 ---
(---(
–---–
1---1
9---9
 ---
h---h
u---u
)---)
 ---
o---o
f---f
 ---
a---a
 ---
r---r
i---i
g---g
h---h
t---t
 ---
a---a
d---d
r---r
e---e
n---n
a---a
l---l
 ---
m---m
a---a
s---s
s---s
 ---
w---w
i---i
t---t
h---h
 ---
h---h
y---y
p---p
e---e
r---r
d---d
e---e
n---n
s---s
e---e
 ---
f---f
o---o
c---c
i---i
 ---
o---o
f---f
 ---
c---c
a---a
l---l
c---c
i---i
f---f
i---i
c---c
a---a
t---t
i---i
o---o
n---n
.---.
 ---
 ---
c---c
t---t
 ---
s---s
c---c
a---a
n---n
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
a---a
b---b
d---d
o---o
m---m
e---e
n---n
 ---
o---o
n---n
 ---
p---p
a---a
t---t
i---i
e---e
n---n
t---t
 ---
p---p
r---r
e---e
s---s
e---e
n---n
t---t
a---a
t---t
i---i
o---o
n---n
 ---
d---d
e---e
m---m
o---o
n---n
s---s
t---t
r---r
a---a
t---t
i---i
n---n
g---g
 ---
p---p
n---n
e---e
u---u
m---m
o---o
b---b
i---i
l---l
i---i
a---a
 ---
a---a
n---n
d---d
 ---
p---p
n---n
e---e
u---u
m---m
o---o
p---p
e---e
r---r
i---i
t---t
o---o
n---n
e---e
u---u
m---m
 ---
a---a
n---n
t---t
e---e
r---r
i---i
o---o
r---r
 ---
t---t
o---o
 ---
t---t
h---h
e---e
 ---
l---l
i---i
v---v
e---e
r---r
 ---
 ---
2---2
2---2
-----
o---o
l---l
d---d
-----
y---y
e---e
a---a
r---r
 ---
m---m
a---a
l---l
e---e
 ---
w---w
i---i
t---t
h---h
 ---
p---p
a---a
i---i
n---n
 ---
a---a
n---n
d---d
 ---
t---t
e---e
n---n
d---d
e---e
r---r
n---n
e---e
s---s
s---s
 ---
i---i
n---n
 ---
t---t
h---h
e---e
 ---
r---r
i---i
g---g
h---h
t---t
 ---
m---m
a---a
x---x
i---i
l---l
l---l
a---a
r---r
y---y
 ---
l---l
a---a
t---t
e---e
r---r
a---a
l---l
 ---
i---i
n---n
c---c
i---i
s---s
o---o
r---r
 ---
d---d
i---i
a---a
g---g
n---n
o---o
s---s
e---e
d---d
 ---
w---w
i---i
t---t
h---h
 ---
d---d
e---e
n---n
s---s
 ---
i---i
n---n
v---v
a---a
g---g
i---i
n---n
a---a
t---t
u---u
s---s
 ---
t---t
y---y
p---p
e---e
 ---
2---2
 ---
i---i
n---n
 ---
t---t
o---o
o---o
t---t
h---h
 ---
2---2
2---2
 ---
a---a
n---n
d---d
 ---
d---d
o---o
u---u
b---b
l---l
e---e
 ---
d---d
e---e
n---n
s---s
 ---
i---i
n---n
v---v
a---a
g---g
i---i
n---n
a---a
t---t
u---u
s---s
 ---
i---i
n---n
 ---
t---t
o---o
o---o
t---t
h---h
 ---
1---1
2---2
.---.
 ---
i---i
n---n
t---t
r---r
a---a
-----
o---o
r---r
a---a
l---l
 ---
r---r
a---a
d---d
i---i
o---o
g---g
r---r
a---a
p---p
h---h
 ---
o---o
f---f
 ---
t---t
o---o
o---o
t---t
h---h
 ---
1---1
2---2
 ---
s---s
h---h
o---o
w---w
s---s
 ---
t---t
h---h
e---e
 ---
d---d
o---o
u---u
b---b
l---l
e---e
 ---
d---d
e---e
n---n
s---s
 ---
i---i
n---n
v---v
a---a
g---g
i---i
n---n
a---a
t---t
u---u
s---s
 ---
a---a
n---n
d---d
 ---
t---t
h---h
e---e
 ---
p---p
r---r
e---e
s---s
e---e
n---n
c---c
e---e
 ---
o---o
f---f
 ---
t---t
w---w
o---o
 ---
e---e
n---n
a---a
m---m
e---e
l---l
 ---
l---l
i---i
n---n
e---e
d---d
 ---
i---i
n---n
v---v
a---a
g---g
i---i
n---n
a---a
t---t
i---i
o---o
n---n
s---s
 ---
(---(
a---a
r---r
r---r
o---o
w---w
s---s
)---)
.---.
 ---
 ---
l---l
a---a
t---t
e---e
r---r
a---a
l---l
 ---
v---v
i---i
e---e
w---w
 ---
s---s
h---h
o---o
w---w
i---i
n---n
g---g
 ---
s---s
i---i
n---n
g---g
l---l
e---e
 ---
f---f
e---e
m---m
u---u
r---r
 ---
a---a
n---n
d---d
 ---
t---t
i---i
b---b
i---i
a---a
 ---
 ---
a---a
n---n
g---g
i---i
o---o
g---g
r---r
a---a
m---m
 ---
o---o
f---f
 ---
l---l
e---e
f---f
t---t
 ---
a---a
n---n
t---t
e---e
r---r
i---i
o---o
r---r
 ---
d---d
e---e
s---s
c---c
e---e
n---n
d---d
i---i
n---n
g---g
 ---
c---c
o---o
r---r
o---o
n---n
a---a
r---r
y---y
 ---
a---a
r---r
t---t
e---e
r---r
y---y
 ---
d---d
e---e
m---m
o---o
n---n
s---s
t---t
r---r
a---a
t---t
i---i
n---n
g---g
 ---
8---8
0---0
%---%
 ---
s---s
t---t
e---e
n---n
o---o
s---s
i---i
s---s
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
p---p
r---r
o---o
x---x
i---i
m---m
a---a
l---l
 ---
s---s
e---e
g---g
m---m
e---e
n---n
t---t
 ---
(---(
b---b
l---l
a---a
c---c
k---k
 ---
a---a
r---r
r---r
o---o
w---w
)---)
.---.
 ---
 ---
c---c
t---t
 ---
i---i
m---m
a---a
g---g
i---i
n---n
g---g
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
b---b
a---a
l---l
l---l
o---o
o---o
n---n
i---i
n---n
g---g
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
c---c
y---y
s---s
t---t
 ---
a---a
f---f
t---t
e---e
r---r
 ---
b---b
i---i
r---r
t---t
h---h
.---.
 ---
 ---
x---x
-----
r---r
a---a
y---y
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
a---a
n---n
k---k
l---l
e---e
 ---
i---i
n---n
 ---
l---l
a---a
t---t
e---e
r---r
a---a
l---l
 ---
v---v
i---i
e---e
w---w
 ---
s---s
h---h
o---o
w---w
s---s
 ---
t---t
h---h
e---e
 ---
a---a
n---n
g---g
l---l
e---e
 ---
o---o
f---f
 ---
g---g
i---i
s---s
s---s
a---a
n---n
e---e
.---.
 ---
 ---
f---f
o---o
l---l
l---l
o---o
w---w
-----
u---u
p---p
 ---
r---r
a---a
d---d
i---i
o---o
g---g
r---r
a---a
p---p
h---h
 ---
a---a
t---t
 ---
3---3
 ---
y---y
e---e
a---a
r---r
s---s
 ---
a---a
n---n
d---d
 ---
6---6
 ---
m---m
o---o
n---n
t---t
h---h
s---s
 ---
p---p
o---o
s---s
t---t
-----
s---s
u---u
r---r
g---g
e---e
r---r
y---y
.---.
 ---
t---t
h---h
e---e
 ---
r---r
a---a
d---d
i---i
o---o
g---g
r---r
a---a
p---p
h---h
 ---
s---s
h---h
o---o
w---w
s---s
 ---
g---g
o---o
o---o
d---d
 ---
r---r
e---e
m---m
o---o
d---d
e---e
l---l
i---i
n---n
g---g
 ---
a---a
n---n
d---d
 ---
n---n
o---o
 ---
i---i
n---n
v---v
o---o
l---l
v---v
e---e
m---m
e---e
n---n
t---t
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
h---h
i---i
p---p
 ---
j---j
o---o
i---i
n---n
t---t
.---.
 ---
 ---
c---c
o---o
n---n
t---t
r---r
a---a
s---s
t---t
 ---
r---r
a---a
d---d
i---i
o---o
g---g
r---r
a---a
p---p
h---h
y---y
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
b---b
i---i
l---l
i---i
a---a
r---r
y---y
 ---
t---t
r---r
a---a
c---c
t---t
 ---
b---b
y---y
 ---
p---p
t---t
g---g
b---b
d---d
 ---
s---s
h---h
o---o
w---w
e---e
d---d
 ---
g---g
a---a
l---l
l---l
b---b
l---l
a---a
d---d
d---d
e---e
r---r
 ---
s---s
t---t
o---o
n---n
e---e
s---s
 ---
(---(
a---a
r---r
r---r
o---o
w---w
h---h
e---e
a---a
d---d
)---)
 ---
a---a
n---n
d---d
 ---
c---c
o---o
m---m
m---m
o---o
n---n
 ---
b---b
i---i
l---l
e---e
 ---
d---d
u---u
c---c
t---t
 ---
s---s
t---t
o---o
n---n
e---e
s---s
 ---
(---(
a---a
r---r
r---r
o---o
w---w
)---)
.---.
 ---
 ---
c---c
o---o
m---m
p---p
e---e
n---n
s---s
a---a
t---t
e---e
d---d
 ---
c---c
o---o
n---n
g---g
e---e
n---n
i---i
t---t
a---a
l---l
 ---
s---s
c---c
o---o
l---l
i---i
o---o
s---s
i---i
s---s
 ---
–---–
 ---
2---2
 ---
a---a
l---l
t---t
e---e
r---r
n---n
a---a
n---n
t---t
 ---
h---h
e---e
m---m
i---i
v---v
e---e
r---r
t---t
e---e
b---b
r---r
a---a
e---e
:---:
 ---
t---t
6---6
 ---
a---a
n---n
d---d
 ---
t---t
9---9
 ---
w---w
i---i
t---t
h---h
 ---
2---2
 ---
n---n
o---o
r---r
m---m
a---a
l---l
 ---
v---v
e---e
r---r
t---t
e---e
b---b
r---r
a---a
e---e
 ---
b---b
e---e
t---t
w---w
e---e
e---e
n---n
 ---
t---t
h---h
e---e
m---m
 ---
 ---
m---m
a---a
m---m
m---m
o---o
g---g
r---r
a---a
p---p
h---h
y---y
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
l---l
e---e
f---f
t---t
 ---
b---b
r---r
e---e
a---a
s---s
t---t
 ---
s---s
h---h
o---o
w---w
i---i
n---n
g---g
 ---
a---a
 ---
c---c
o---o
n---n
f---f
i---i
n---n
e---e
d---d
 ---
d---d
e---e
n---n
s---s
i---i
t---t
y---y
 ---
i---i
n---n
 ---
t---t
h---h
e---e
 ---
r---r
e---e
t---t
r---r
o---o
a---a
r---r
e---e
o---o
l---l
a---a
r---r
 ---
a---a
r---r
e---e
a---a
.---.
 ---
 ---
c---c
h---h
e---e
s---s
t---t
 ---
x---x
-----
r---r
a---a
y---y
 ---
s---s
h---h
o---o
w---w
i---i
n---n
g---g
 ---
t---t
h---h
e---e
 ---
p---p
o---o
r---r
t---t
 ---
i---i
n---n
 ---
c---c
o---o
r---r
r---r
e---e
c---c
t---t
 ---
p---p
o---o
s---s
i---i
t---t
i---i
o---o
n---n
 ---
w---w
h---h
i---i
l---l
e---e
 ---
t---t
h---h
e---e
 ---
c---c
a---a
t---t
h---h
e---e
t---t
e---e
r---r
 ---
i---i
s---s
 ---
n---n
o---o
t---t
 ---
s---s
h---h
o---o
w---w
n---n
 ---
h---h
e---e
r---r
e---e
.---.
 ---
t---t
h---h
e---e
 ---
c---c
a---a
t---t
h---h
e---e
t---t
e---e
r---r
 ---
h---h
a---a
d---d
 ---
m---m
o---o
v---v
e---e
d---d
 ---
i---i
n---n
 ---
t---t
h---h
e---e
 ---
r---r
i---i
g---g
h---h
t---t
 ---
a---a
t---t
r---r
i---i
u---u
m---m
,---,
 ---
f---f
r---r
o---o
m---m
 ---
w---w
h---h
e---e
r---r
e---e
 ---
i---i
t---t
 ---
w---w
a---a
s---s
 ---
r---r
e---e
m---m
o---o
v---v
e---e
d---d
 ---
f---f
l---l
u---u
o---o
r---r
o---o
s---s
c---c
o---o
p---p
i---i
c---c
a---a
l---l
l---l
y---y
.---.
 ---
 ---
b---b
a---a
r---r
i---i
u---u
m---m
 ---
e---e
s---s
o---o
p---p
h---h
a---a
g---g
o---o
g---g
r---r
a---a
m---m
 ---
s---s
h---h
o---o
w---w
i---i
n---n
g---g
 ---
m---m
a---a
r---r
k---k
e---e
d---d
 ---
l---l
u---u
m---m
i---i
n---n
a---a
l---l
 ---
n---n
a---a
r---r
r---r
o---o
w---w
i---i
n---n
g---g
 ---
a---a
t---t
 ---
t---t
h---h
e---e
 ---
g---g
a---a
s---s
t---t
r---r
o---o
e---e
s---s
o---o
p---p
h---h
a---a
g---g
e---e
a---a
l---l
 ---
j---j
u---u
n---n
c---c
t---t
i---i
o---o
n---n
 ---
w---w
i---i
t---t
h---h
 ---
b---b
i---i
r---r
d---d
 ---
b---b
e---e
a---a
k---k
 ---
c---c
o---o
n---n
f---f
i---i
g---g
u---u
r---r
a---a
t---t
i---i
o---o
n---n
,---,
 ---
c---c
o---o
n---n
s---s
i---i
s---s
t---t
e---e
n---n
t---t
 ---
w---w
i---i
t---t
h---h
 ---
a---a
c---c
h---h
a---a
l---l
a---a
s---s
i---i
a---a
.---.
 ---
 ---
u---u
n---n
e---e
n---n
h---h
a---a
n---n
c---c
e---e
d---d
 ---
c---c
t---t
:---:
 ---
s---s
e---e
v---v
e---e
r---r
e---e
 ---
s---s
c---c
o---o
l---l
i---i
o---o
s---s
i---i
s---s
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
l---l
u---u
m---m
b---b
a---a
r---r
 ---
s---s
p---p
i---i
n---n
e---e
 ---
a---a
n---n
d---d
 ---
d---d
i---i
s---s
p---p
l---l
a---a
c---c
e---e
m---m
e---e
n---n
t---t
 ---
a---a
n---n
d---d
 ---
h---h
o---o
r---r
i---i
z---z
o---o
n---n
t---t
a---a
l---l
 ---
t---t
o---o
r---r
s---s
i---i
o---o
n---n
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
l---l
e---e
f---f
t---t
 ---
k---k
i---i
d---d
n---n
e---e
y---y
 ---
t---t
o---o
 ---
t---t
h---h
e---e
 ---
m---m
i---i
d---d
l---l
i---i
n---n
e---e
 ---
(---(
f---f
i---i
n---n
e---e
 ---
a---a
r---r
r---r
o---o
w---w
)---)
.---.
 ---
m---m
a---a
r---r
k---k
e---e
d---d
 ---
d---d
i---i
l---l
a---a
t---t
a---a
t---t
i---i
o---o
n---n
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
p---p
e---e
l---l
v---v
i---i
c---c
a---a
l---l
i---i
c---c
e---e
a---a
l---l
 ---
s---s
y---y
s---s
t---t
e---e
m---m
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
l---l
e---e
f---f
t---t
 ---
k---k
i---i
d---d
n---n
e---e
y---y
 ---
(---(
t---t
h---h
i---i
c---c
k---k
 ---
a---a
r---r
r---r
o---o
w---w
)---)
;---;
 ---
n---n
o---o
 ---
d---d
i---i
l---l
a---a
t---t
e---e
d---d
 ---
u---u
r---r
e---e
t---t
e---e
r---r
.---.
 ---
n---n
o---o
r---r
m---m
a---a
l---l
 ---
p---p
o---o
s---s
i---i
t---t
i---i
o---o
n---n
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
r---r
i---i
g---g
h---h
t---t
 ---
k---k
i---i
d---d
n---n
e---e
y---y
;---;
 ---
n---n
o---o
 ---
d---d
i---i
l---l
a---a
t---t
a---a
t---t
i---i
o---o
n---n
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
e---e
x---x
c---c
r---r
e---e
t---t
o---o
r---r
y---y
 ---
s---s
y---y
s---s
t---t
e---e
m---m
.---.
 ---
 ---
t---t
r---r
a---a
n---n
s---s
t---t
h---h
o---o
r---r
a---a
c---c
i---i
c---c
 ---
e---e
c---c
h---h
o---o
c---c
a---a
r---r
d---d
i---i
o---o
g---g
r---r
a---a
m---m
:---:
 ---
a---a
p---p
i---i
c---c
a---a
l---l
 ---
f---f
o---o
u---u
r---r
‐---‐
c---c
h---h
a---a
m---m
b---b
e---e
r---r
 ---
v---v
i---i
e---e
w---w
 ---
w---w
i---i
t---t
h---h
 ---
f---f
o---o
c---c
u---u
s---s
 ---
o---o
n---n
 ---
t---t
h---h
e---e
 ---
r---r
i---i
g---g
h---h
t---t
 ---
a---a
t---t
r---r
i---i
u---u
m---m
.---.
 ---
 ---
a---a
n---n
 ---
a---a
x---x
i---i
a---a
l---l
 ---
t---t
2---2
 ---
m---m
r---r
i---i
 ---
s---s
h---h
o---o
w---w
i---i
n---n
g---g
 ---
t---t
h---h
e---e
 ---
f---f
a---a
t---t
t---t
y---y
 ---
a---a
t---t
r---r
o---o
p---p
h---h
y---y
 ---
a---a
n---n
d---d
 ---
r---r
e---e
t---t
r---r
a---a
c---c
t---t
i---i
o---o
n---n
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
r---r
i---i
g---g
h---h
t---t
 ---
i---i
l---l
i---i
o---o
-----
p---p
s---s
o---o
a---a
s---s
 ---
t---t
e---e
n---n
d---d
o---o
n---n
 ---
(---(
a---a
r---r
r---r
o---o
w---w
)---)
 ---
a---a
l---l
l---l
 ---
t---t
h---h
e---e
 ---
w---w
a---a
y---y
 ---
t---t
o---o
 ---
t---t
h---h
e---e
 ---
l---l
e---e
v---v
e---e
l---l
 ---
o---o
f---f
 ---
t---t
h---h
e---e
 ---
s---s
a---a
c---c
r---r
o---o
-----
i---i
l---l
i---i
a---a
c---c
 ---
j---j
o---o
i---i
n---n
t---t
.---.
 ---
 ---
c---c
r---r
a---a
n---n
i---i
a---a
l---l
 ---
c---c
o---o
m---m
p---p
u---u
t---t
e---e
d---d
 ---
t---t
o---o
m---m
o---o
g---g
r---r
a---a
p---p
h---h
y---y
 ---
s---s
h---h
o---o
w---w
s---s
 ---
l---l
o---o
c---c
a---a

In [27]:
stemming.stem("calculation"),snowballstemmer.stem("calculation")

('calcul', 'calcul')

In [28]:
from nltk.stem import WordNetLemmatizer
import nltk

In [29]:
nltk.download("wordnet")

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [30]:
lemmatizer=WordNetLemmatizer()

In [31]:
lemmatizer.lemmatize("corpora",pos="n")

'corpus'

In [32]:
import nltk
nltk.download("punkt")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [33]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [34]:
from nltk.stem import PorterStemmer
stemmer=PorterStemmer()

In [35]:
sentences=nltk.sent_tokenize(captions)

In [36]:
nltk.download("stopwords")
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [37]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [38]:
for i in range(len(sentences)):
    words=nltk.word_tokenize(sentences[i])
    words=[stemmer.stem(word) for word in words if word not in set(stopwords.words('english'))]
    sentences[i]=" ".join(words)

In [39]:
print(sentences)

['coron plain comput tomographi imag show multipl larg tumor mass edg enhanc insid abdomin caviti liver .', 'axial sourc imag intracrani magnet reson angiogram reveal abnorm arteri signal elev left right cavern sinus consist carotid cavern fistula , indic arrow .', 'apic height , homogen , thick miner trioxid aggreg plug cto rca ( closur 2nd segment ) venographi show larg amount thrombogenesi femoropoplitea vein thrombolysi .', 'postop decreas size cyst fetal aortic arch .', 'solid arrow repres ascend aorta dot arrow repres aortic arch distal ductu arteriosu .', 'note alias ductal arch reflect turbul blood flow result extern compress due mass-effect .', 'abdomin comput tomographi scan .', 'arrow point like cholecystocutan fistul track .', 'distens digest avec niveaux hydro-aériqu coliqu et vacuité pelvienn panoram x ray taken four year later show unilocular radioluc area left ramu .', 'anteroposterior radiograph pelvi recent follow .', 'immedi postinjuri magnet reson imag demonstr intact spinal cord canal cerebrospin fluid signal surround spinal cord level .', 'arteri phase dynam ct show homogen enhanc mass ( arrow ) .', 'level , normal right side adren gland visual .', 'angiogram show pseudoaneurysm ( arrow ) format proxim left superfici femor arteri .', 'imag ct fluoroscop guidanc rhizotomi demonstr radiofrequ cannular tip junction superior articular process transvers process .', 'bileter styloid process elong subject panoram radiographi .', 'solid-cyst lesion thicken hyperecho wall .', 'region polycycl solid structur wall lesion , color doppler ( cdu ) show tortuou arteri vessel initi chest x-ray show left tension pneumothorax shift mediastinum right , pleural effus left , basal dorsolater rib fractur .', "'s also air visibl right diaphragm ( arrow ) .", 'larg subcutan tributari pierc superfici fascia join lsv thigh region .', 'brain magnet reson imag ( mri ) gadolinium inject show imag axial ( flair sequenc ) show hyper-intens lesion white matter frontal lobe .', 'signal abnorm cortex .', 'note mass effect ventricular caviti midlin structur .', 'dosimetr result obtain rapidarc .', 'barium small bowel meal follow show normal small larg bowel .', 'ct axial section show multilocular expansil lytic lesion bodi mandibl right side signific enhanc soft tissu matrix comput tomographi obtain 3 week admiss diagnosi aspir pneumonia show hepat portal venou ga ga within wall stomach visual portion upper abdomen postop day 1 chest radiograph reveal larg left pneumothorax .', 'left upper lobe squamou cell cancer show broad , convex margin mediastinum ct ( arrow ) ; mediastin pleural invas surgeri patholog ( t2 tumor ) .', 'ct scan thorax demonstr necrot paratrach node .', 'enhanc axial ct scan thorax , mediastin window , 58-year-old femal present bilater vocal cord immobl unknown etiolog .', 'posit serum anti-hu antibodi , highli associ small cell lung carcinoma , led repeat ct scan .', 'arrow demonstr enlarg level 4r paratrach lymph node central necrosi .', 'see figur 2 patholog descript biopsi node .', 'cortic bone chang rheumatoid arthriti classic radiographi show striation lamel cortic bone phalanx .', 'twelve-year-old boy present nasopharyng angiofi broma diagnos unilater meningo-ophthalm arteri anomali .', 'comput tomographi scan show midlin nasopharyng angiofi broma ( black arrow ) , promin right-sid infiltr infratempor fossa ( white arrow ) .', 'pelvi arthrogram show defect ossif later acetabular corner , leav signific cartilagin anlag left anterior obliqu common coronari arteri branch critic diseas proxim rca , mid/dist anomal lcx .', 'calcul inferior vena cava collaps index ( [ a–b ] /b ) ( % ) use ultrasonographi ct guid core biopsi infracol oment cake .', 'initi radiograph show right femor neck fractur sclerot superior cortex undisplac linear pattern .', 't2-weight mr sagitt imag show isointens schwannoma cauda equina compress s3 level .', 'magnet reson angiographi present show giant intracrani aneurysm onset ectasia left carotid siphon .', 'mri right elbow ( t2 imag ) demonstr fusion proxim one-third ulna radiu .', 'note anterior disloc radial head , joint fluid effus , tension anterior capsul , edema signal anterior soft tissu .', 'anteroposterior chest radiograph show cardiomegali well irregular contour later margin descend thorac aorta ( arrow ) .', 'chest x-ray show mild increas transvers cardiac diamet .', 'left cardiac border protrud left mildli .', 'computer tomographi reveal dilat intrahepat biliari duct .', 'pneumocysti pneumonia aid patient .', 'hrct level upper lobe reveal mix “ ground-glass cystic pattern ” characteris presenc diffus area ground-glass opac thin-wal multilocular cyst fail consolid treatment nail alon .', 'elast stabl intramedullari nail combin orthoss® gps® earlier fail treatment .', 'radiograph three month follow initi gps®/orthoss® treatment result bone miner .', 'ct scan show larg left ovarian cyst hc diamet 0.37 cm left hippocampu note t1-weight imag level hippocampu fragment humer head step thorac aorta ( black arrow ) ultrasound imag bovin liver depict tip ( arrow ) two cannula insert use introduc set prior rf ablat .', 'two hyperecho tip , posterior acoust shadow visibl .', 'aortic root demonstr linear measur patient suffer dissect .', '( case # 2 ) comput tomographi abdomen show right upper quadrant abdomin pseudocyst ( arrow ) near gastric outlet renal manifest ct abdomen .', 'bilater nephromegali ( greater 2 standard deviat age ) , nephrocalcinosi ( red box ) .', 'abdomin ct find reveal remain round foreign bodi appendix , dilat appendix .', 'mri find .', 'cystic duct seen .', 'six week partial medial meniscectomi , coron fat-satur t2-weight imag show subchondr fractur medial femor condyl ( larg arrow ) mark surround marrow edema pattern well smaller subchondr fractur central aspect later femor condyl ( small arrow ) less extens adjac marrow edema pattern .', 'case unusu given subchondr fractur compart ; usual , fractur occur compart prior partial meniscectomi radial split complex tear posterior horn root .', 'ct scan imag opacif bladder demonstr extra-periton extravas infus contrast posterior aspect bladder radiograph appear 6 month show lesion disappear .', 'abdomin mri demonstr cyst ( asterisk ) intim relat left lobe liver ( l ) , spleen ( ) gastric bodi ( g ) , still without clearli demonstr plane structur .', 'transoesophag echocardiogram demonstr mass ( fibroelastoma ) left ventricular outflow tract immedi surgeri : enucl cyst & fixat bend 8-hole plate five screw ; extract # 26. radiograph chest reveal bilater pleural effus .', 'feli catu , adult , longitudin section middl ear gener avizo®7 ct data [ 42 ] ( see text method ) .seam tympan plate mallear rostral process ectotympan mark caret .', 'scale = 2 mm .', 'abbrevi : ecto , ectotympan ; en , ectotympan notch ; hm , head malleu ; , incu ; mh , mallear hook ; ol , osseou lamina ; pet , petros ; tp , tympan plate rostral process .', 'axial section cect abdomen show enlarg left psoa muscl ill-defin hypodens area ( star ) retroperiton fat strand ( solid arrow ) .', 'fluid collect multipl air pocket seen left posterior preperiton space ( hollow arrow ) .', 'ct treatment demonstr pack coil seat right acc hypogloss canal ( treat 5 year ago ) left acc .', 'comput tomographi show larg bilater adren mass schemat represent method use measur interradicular space .', 'first , cemento-enamel junction ( cej ) two adjac teeth identifi .', 'start cej , ruler scroll toward root apex 3 mm horizont interradicular space found ; , distanc cej measur well total root length cej apex .', 'bullet local intraop portabl imag system ( c-arm ) longitudin section – intercost space ( “ bat sign ” ) : f – subcutan fat .', 'ice –extern intercost muscl , r – rib , horizont arrow – intern intercost muscl , upward arrow – pleura paramet evalu airway .', 'abdomin comput tomographi ( ct ) scan retroperiton recurr mri abdomen : lymph node distant metastasi .', 'fetu uteru seen .', 'three-dimension reconstruct maxilla , transposit left canin first premolar .', 'antenat ultrasound imag 20 week gestat , illustr megalourethra cystic structur balloon distal penil portion urethra .', 'ob 600 –automat sort machin wast portabl batteries.sourc : optisort .', 'chest radiograph show left-sid pleural effus shortli admiss .', 'post mortem ct show hydrocephalu ( asterisk ) multicyst encephalomalacia ( arrow ) axial ct demonstr well-defin lesion expans buccal lingual cortic plate fa left eye normal impact fractur weight bear result screw joint penetr three month postop .', 'doppler ultrasound perform upon patient present demonstr heterogen echotextur testicl epididymi signifi ischemia inflamm testicl necrosi epididymi ( red arrow ) .', 'peripher blood flow testicl present blood flow epididymi maintain .', 'addit , signific hematoma visual anterior aspect testicl ( green arrow ) .', 'plain radiograph show lytic lesion right iliac wing minim periost reaction .', 'sagitt transperin sonographi show recurr mass patient occupi rectovagin septum .', 'vagina fill acoust contrast .', 'cerebr angiogram ca demonstr ophthalm arteri occlus ( arrow ) .', 'ct scan sagitt section show coron plane fractur distal femur ( hoffa fractur ) .', 'third degre adiposi .', 'clearli deterior dorsal transson pancrea .', 'invis splenic vein anatom structur locat deeper .', 'f – supraperiton fat subcutan epidermoid cyst phalang ( arrowhead ) .', 'longitudin ultrasound show well-defin subcutan lesion variabl echogen ( anecho compon intern hyperecho debri ) pmmr hypox brain chang .', 'axial t2-weight pmmr imag fetal post mortem brain , show exampl typic low signal chang basal ganglia may associ hypoxia .', 'convent pmmr current distinguish antemortem postmortem hypox chang susceptibility-weight imag 7 ( 8-channel head coil ) ; imag repres minimum intens project 6 mm slab .', 'note , vein iron contain structur like basal ganglia appear hypo intens .', 'imag acquir use echo time 15 ms resolut 0.3 × 0.3 × 1.2 mm .', 'primari bullet path full metal jacket two-shot techniqu axial ct scan incarcer stomach ; first part duodenum seen leav inguin hernia .', 'anteroposterior radiograph femal patient underw bilater ludloff open reduct age 5 month ; ) 1.6 year post-op , show advanc sublux femor head residu acetabular dysplasia ; b ) two month bilater salter femor derot varu osteotomi ; c ) recurr coxa valga without asept necrosi nine year age ) severin group iia hip 28 year age .', 'immedi postop orthopentomogram sagitt te weight mr imag reveal thought complet acl ruptur ( arrow ) appreci complet ruptur arthroscopi .', 'accord arthroscopist partial tear involv approxim 75 % ligament bodi .', 'radiograph 39 year old male ( case report 1 ) made one year open reduct intern fixat .', 'good boni consolid incomplet reconstruct joint line visibl .', 'pet/ct imag .', 'pet/ct show mass display increas fdg uptak cholangiograph find .', 'endoscop retrograd cholangiographi use carbon dioxid insuffl show kink common bile duct 1 cm proxim end metal stent ( arrow ) .', 'ct scan 6 month mitotan treatment show reduct size adren mass .', 'abdomin ultrasound imag 48-year-old femal benign lesser curvatur gastric ulcer show thicken gastric wall niche-lik echogen ( arrow ) , probabl repres ulcer carter .', 'axial cut ct-chest demonstr well-circumscrib soft tissu densiti ( * ) left breast measur 3.1×3.7 cm.abbrevi : ct , comput tomographi .', 'supin ventral-dors abdomin x-ray immedi surgeri .', 'right abdomin wall small hybrid rebound hrd .', 'left side dog bone rebound hrd .', 'pass lesion.abbrevi : cran , cranial ; rao , right anterior obliqu .', 'increas activ upper left quadrant case 3 2nd hour .', 'activ move toward inferior quadrant 4th hour .', 'mri scan chest – axial view .', 'note anterior chest wall defect tooth 3.4 reduc periap radioluc ct scan portal phase .', 'contrast enhanc , enhanc portion lesion .', 'pet-ct imag show intens fluorine-18 fluorodeoxyglucos ( 18f–fdg ) uptak maximum standard uptak valu ( suv ) 9.0 ( arrow ) .', 'suspect extrasplen tumor dissemin metastasi transthorac short axi parastern view measur veget 20 mm long .', 'radiograph individu hereditari multipl exostosi .', 'note deform forearm ( due shorten ulna ) .', 'ct scan ( frontal view ) demonstr multipl locul air ( arrow ) .', 'transposit ulnar nerv symptom secondari neuropathi .', 'bend ( arrow ) nerv ( asterisk ) site enter head flexor carpi ulnari muscl short tau invers recoveri magnet reson imag show signific deviat median nerv toward fractur site radiu ( arrow ) .', 'ultrasound scan reveal giant hepat cyst .', 'echogen substanc visibl bottom cyst lead “ fluid-fluid ” level .', 'pre-op radiolog view case 1 mass-lik echo , medium intens , roughli distribut within echo right anterior vitreou caviti .', "posterior vitreou reveal `` v '' -shape echo .", 'transgastr short axi view tranesophag echocardiographi view lunar modul mass transthorac echocardiographi demonstr secundum asd left-to-right shunt mid-esophag right ventricular inflow-outflow view , arrow point 2 cm × 2 cm mobil echogen mass probabl thrombu right ventricular outflow tract patient .', '15. stump lengthen procedur .', 'magnet reson imag ( mri ) imag shoulder mass 28-year-old femal .', 't2 fat-satur sequenc demonstr 10.6 cm hyperintens fluid collect ( white arrowhead ) multipl foci intern debri , consist rice bodi format ( black arrow ) .', 'aortogram reveal sever aortic regurgit possibl dissect flap .', 'postop arthroscann show boni integr achilles-calcan allograft , good integr posterosuperior tendin graft coron preoper chest ct demonstr herniat colon chest free air ( arrow ) ct scan brain show solitari metastasi , 5x4 cm , right occipit lobe , extens pariet lobe .', 'note heterogen appear metastasi surround brain edema stand later radiograph left leg show callu format proxim fibula .', 'faint fractur line also seen .', 'left coronari angiogram ct measur renal papilla area 10mm2 , obtain mean area hounsfield unit .', 'filter bleb : as-oct show elev function filter bleb .', 'bleb moder elev homogen spongi fluid-fil space vitiligo ( red arrow ) ( seen wood ’ lamp ) .', 'radiograph patient made 4 week osteotomi .', 'patient report right buttock pain 3.5 week postop .', 'fractur posterior column ( arrow ) reveal , seen figur 1. ct scan show abscess format begin around piriform sinu .', 'protect proximal/middl segment vessel smooth , normal flow evid lumin strictur .', 'echo-endoscop aspect chest x-ray show pneumothorax secondari block chest tube .', 'a. pleural white line b. block chest tube axial t2 mri imag c6–7 demonstr bilater neuroforamin stenosi secondari disc protrus .', 'intracoronari ultrasound ( ivu ) correspond lad segment demonstr fals lumen ( fl ) occupi echogen mass ( intramur hematoma ) .', 'true lumen ( tl ) compress narrow ( white arrow : flap , c : cathet ) .', 'ct-scan abdomen : imag show oval umbil mass measur 2 cm .', 'comput tomographi scan show giant hepat cyst right lobe liver compress adjac diaphragm , right ventricl inferior vena cava ( arrow head ) .', 'orthopantomograph posttreat chest comput tomographi time hospit admissiona 9-mm intermedi lobular nodul seen ( red arrow ) subpleura right lower lung .', 'chest x-ray demonstr high posit right diaphragm due postop paralysi .', 'anterior-posterior cross-sect extrud slab model precentr gyru .', '3d model construct extrud cross-sect .', 'invas electrod place on/und dura mater epidural/subdur cortic stimul .', 'maximum von miss stress observ c7 vertebra level pedicl ( white circular area ) load mode .', 'posterioanterior fluoroscop imag lumbosacr spine show fusion vertebr bodi needl placement left s1 neuroforamen b-line .', 'b-line ( arrow ) bright comet-tail artifact aris pleural line ( arrowhead ) .', 'move lung slide , slide present , extend end screen without fade ct scan thorax femal patient intub due respiratori failur .', 'tuberculosi subsequ cultur bronchoscopi specimen .', 'note cavit mainli right upper lobe .', 'follow-up barium enema reveal evid distal obstruct anatomi suitabl segment intestin resect enterocutan fistula .', 'contrast reflux anu previous obstruct area , fistula .', 'parastern long axi view systol .', 'balloon apic segment left ventricl appar .', 't1 coron imag : well defin mass ( long white arrow ) inferior right parotid gland ( short white arrow ) & medial sternocleidomastoid muscl ( arrowhead ) .', 'methodolog measur retroperiton fat tissu thick use axial comput tomographi imag .', 'measur retroperiton fat tissu thick perform slice show renal vein treat kidney side patient 7 : x-ray bone graft 4 dental implant ( imag show differ graft rest jaw ) .', 'transvers comput tomographi imag level 2nd lumbar vertebra 10 mmhg co2 insuffl pressur .', 'trocar place right approach .', 'maximum linear dimens ( maximum dorsoventr diamet maximum transvers diamet [ red line ] ) measur separ left right side base mid‐sagitt plane medial border ( green line ) .', 'endoscop papillari balloon dilat .', 'dilat ectop open 8 mm diamet biliari dilat balloon .', 'note stone next balloon .', 'sutura temporozygomatica ( arrow ) , axial multiplanar reconstruct .', 'initi pelvic injuri seen anteroposterior pelvic radiograph case 2 includ pubic symphysi diastasi , right sacroiliac diastasi right sacral ala fractur post-op axial ct head show intracrani patholog .', 'incid apical de 4 cavité montrant un vg dilaté et globuleux delayed-phas ct show left renal pelvi extravas urin anterior ( arrow ) .', 'note unopacifi urin perinephr space ( arrowhead ) color doppler ultrasound show thrombosi superfici dorsal vein peni ( arrow ) .', 'current flow vein peni , monitor superfici dorsal vein .', 'sagit t2-mri spinal cord show extens enhanc thorac lesion ( th1-th3 ) .', 'coron thorac ct imag show right diaphragmat defect loop bowel protrud thorac caviti , indic white arrow .', 'ct , comput tomographi .', 'comput tomographi .', 'initi tumor present ( 2006 ) .', 'point wide field laryngectomi , right thyroid lobectomi , biopsi right upper digastr jugular node perform .', 'final patholog reveal high-grad mucoepidermoid carcinoma .', '27-week fetu persist persist left superior vena cava .', 'fetal cmr b-tfe four-chamb view imag show enlarg coronari sinu ( arrow ) t2-weight mri coron imag show hyperintens lesion .', 'noncontrast axial head ct complet pod 1 show stabl postop chang .', 'magnet reson imag pelvi : sagitt view .', 'enhanc mass visibl anterior cervix comput tomographi show defect ( arrow ) aneurysm ( ) right atrium ( ra ) .', 'lv indic left ventricl ; ao , aorta .', 'cardiogen pulmonari oedema .', 'numer b-line artifact ( → ) seen bilater lower middl field ; normal pleural line .', 'linear probe later cephalogram depict type 3 ( butt shape ) pattern soft palat .', 'comput tomographi thorax .', 'arrow show cold abscess .', 'mri cystic teratoma pancreat tail .', 'enhanc magnet reson show cystic mass aris tail pancrea extend middl side stomach without defin margin .', 'pulmonari angiogram show diffus pavm frontal radiograph pelvi taken six month show widen proxim right femor physi .', 'four-chamb transesophag echocardiogram , show complet absenc interatri septum .', 'ca : common atrium , lv : left ventricl , rv : right ventricl .', 'ultrasonogram patient recurr hernia : oment herniat ( thick arrow ) seen later mesh ( thin arrow ) .', 'suspect cartilag lesion axial comput tomographi nose paranas sinus demonstr total opacif contract right maxillari sinu .', 'present endokomvo schemat : extracorpor limb control intracorpor format triangl .', 'linear high signal within spinal cord extend c4/c5 c7 level keep acut spinal cord infarct duplex scan infect poplit aneurysm .', 'extern j retent wire ( arrow ) notic atrial lead .', 'direct point , advanc laser sheath immedi possibl .', '45-year-old woman bmi 23.1 chest circumfer 94.0 cm .', 'axial ct imag obtain 120 kv 200 ma show ascend aorta imag nois 36.4 hu vessel attenu 509.3 hu .', '

In [40]:
for i in range(len(sentences)):
    words=nltk.word_tokenize(sentences[i])
    words=[snowballstemmer.stem(word) for word in words if word not in set(stopwords.words('english'))]
    sentences[i]=" ".join(words)

In [41]:
sentences

['coron plain comput tomographi imag show multipl larg tumor mass edg enhanc insid abdomin caviti liver .',
 'axial sourc imag intracrani magnet reson angiogram reveal abnorm arteri signal elev left right cavern sinus consist carotid cavern fistula , indic arrow .',
 'apic height , homogen , thick miner trioxid aggreg plug cto rca ( closur 2nd segment ) venographi show larg amount thrombogenesi femoropoplitea vein thrombolysi .',
 'postop decrea size cyst fetal aortic arch .',
 'solid arrow repr ascend aorta dot arrow repr aortic arch distal ductu arteriosu .',
 'note alia ductal arch reflect turbul blood flow result extern compress due mass-effect .',
 'abdomin comput tomographi scan .',
 'arrow point like cholecystocutan fistul track .',
 'disten digest avec niveaux hydro-aériqu coliqu et vacuité pelvienn panoram x ray taken four year later show unilocular radioluc area left ramu .',
 'anteroposterior radiograph pelvi recent follow .',
 'immedi postinjuri magnet reson imag demonstr intact spinal cord canal cerebrospin fluid signal surround spinal cord level .',
 'arteri phase dynam ct show homogen enhanc mass ( arrow ) .',
 'level , normal right side adren gland visual .',
 'angiogram show pseudoaneurysm ( arrow ) format proxim left superfici femor arteri .',
 'imag ct fluoroscop guidanc rhizotomi demonstr radiofrequ cannular tip junction superior articular process transver process .',
 'bilet styloid process elong subject panoram radiographi .',
 'solid-cyst lesion thicken hyperecho wall .',
 'region polycycl solid structur wall lesion , color doppler ( cdu ) show tortuou arteri vessel initi chest x-ray show left tension pneumothorax shift mediastinum right , pleural effus left , basal dorsolat rib fractur .',
 "'s also air visibl right diaphragm ( arrow ) .",
 'larg subcutan tributari pierc superfici fascia join lsv thigh region .',
 'brain magnet reson imag ( mri ) gadolinium inject show imag axial ( flair sequenc ) show hyper-inten lesion white matter frontal lobe .',
 'signal abnorm cortex .',
 'note mass effect ventricular caviti midlin structur .',
 'dosimetr result obtain rapidarc .',
 'barium small bowel meal follow show normal small larg bowel .',
 'ct axial section show multilocular expansil lytic lesion bodi mandibl right side signif enhanc soft tissu matrix comput tomographi obtain 3 week admiss diagnosi aspir pneumonia show hepat portal venou ga ga within wall stomach visual portion upper abdomen postop day 1 chest radiograph reveal larg left pneumothorax .',
 'left upper lobe squamou cell cancer show broad , convex margin mediastinum ct ( arrow ) ; mediastin pleural inva surgeri patholog ( t2 tumor ) .',
 'ct scan thorax demonstr necrot paratrach node .',
 'enhanc axial ct scan thorax , mediastin window , 58-year-old femal present bilat vocal cord immobl unknown etiolog .',
 'posit serum anti-hu antibodi , high associ small cell lung carcinoma , led repeat ct scan .',
 'arrow demonstr enlarg level 4r paratrach lymph node central necrosi .',
 'see figur 2 patholog descript biopsi node .',
 'cortic bone chang rheumatoid arthriti classic radiographi show striation lamel cortic bone phalanx .',
 'twelve-year-old boy present nasopharyng angiofi broma diagno unilat meningo-ophthalm arteri anomali .',
 'comput tomographi scan show midlin nasopharyng angiofi broma ( black arrow ) , promin right-sid infiltr infratempor fossa ( white arrow ) .',
 'pelvi arthrogram show defect ossif later acetabular corner , leav signif cartilagin anlag left anterior obliqu common coronari arteri branch critic disea proxim rca , mid/dist anom lcx .',
 'calcul inferior vena cava collap index ( [ a–b ] /b ) ( % ) use ultrasonographi ct guid core biopsi infracol oment cake .',
 'initi radiograph show right femor neck fractur sclerot superior cortex undisplac linear pattern .',
 't2-weight mr sagitt imag show isointen schwannoma cauda equina compress s3 level .',
 'magnet reson angiographi present show giant intracrani aneurysm onset ectasia left carotid siphon .',
 'mri right elbow ( t2 imag ) demonstr fusion proxim one-third ulna radiu .',
 'note anterior disloc radial head , joint fluid effus , tension anterior capsul , edema signal anterior soft tissu .',
 'anteroposterior chest radiograph show cardiomegali well irregular contour later margin descend thorac aorta ( arrow ) .',
 'chest x-ray show mild increa transver cardiac diamet .',
 'left cardiac border protrud left mild .',
 'comput tomographi reveal dilat intrahepat biliari duct .',
 'pneumocysti pneumonia aid patient .',
 'hrct level upper lobe reveal mix “ ground-glass cystic pattern ” characteri presenc diffus area ground-glass opac thin-wal multilocular cyst fail consolid treatment nail alon .',
 'elast stabl intramedullari nail combin orthoss® gps® earlier fail treatment .',
 'radiograph three month follow initi gps®/orthoss® treatment result bone miner .',
 'ct scan show larg left ovarian cyst hc diamet 0.37 cm left hippocampu note t1-weight imag level hippocampu fragment humer head step thorac aorta ( black arrow ) ultrasound imag bovin liver depict tip ( arrow ) two cannula insert use introduc set prior rf ablat .',
 'two hyperecho tip , posterior acoust shadow visibl .',
 'aortic root demonstr linear measur patient suffer dissect .',
 '( case # 2 ) comput tomographi abdomen show right upper quadrant abdomin pseudocyst ( arrow ) near gastric outlet renal manifest ct abdomen .',
 'bilat nephromegali ( greater 2 standard deviat age ) , nephrocalcinosi ( red box ) .',
 'abdomin ct find reveal remain round foreign bodi appendix , dilat appendix .',
 'mri find .',
 'cystic duct seen .',
 'six week partial medial meniscectomi , coron fat-satur t2-weight imag show subchondr fractur medial femor condyl ( larg arrow ) mark surround marrow edema pattern well smaller subchondr fractur central aspect later femor condyl ( small arrow ) less exten adjac marrow edema pattern .',
 'case unusu given subchondr fractur compart ; usual , fractur occur compart prior partial meniscectomi radial split complex tear posterior horn root .',
 'ct scan imag opacif bladder demonstr extra-periton extrava infus contrast posterior aspect bladder radiograph appear 6 month show lesion disappear .',
 'abdomin mri demonstr cyst ( asterisk ) intim relat left lobe liver ( l ) , spleen ( ) gastric bodi ( g ) , still without clear demonstr plane structur .',
 'transoesophag echocardiogram demonstr mass ( fibroelastoma ) left ventricular outflow tract immedi surgeri : enucl cyst & fixat bend 8-hole plate five screw ; extract # 26. radiograph chest reveal bilat pleural effus .',
 'feli catu , adult , longitudin section middl ear gener avizo®7 ct data [ 42 ] ( see text method ) .seam tympan plate mallear rostral process ectotympan mark caret .',
 'scale = 2 mm .',
 'abbrevi : ecto , ectotympan ; en , ectotympan notch ; hm , head malleu ; , incu ; mh , mallear hook ; ol , osseou lamina ; pet , petro ; tp , tympan plate rostral process .',
 'axial section cect abdomen show enlarg left psoa muscl ill-defin hypoden area ( star ) retroperiton fat strand ( solid arrow ) .',
 'fluid collect multipl air pocket seen left posterior preperiton space ( hollow arrow ) .',
 'ct treatment demonstr pack coil seat right acc hypogloss canal ( treat 5 year ago ) left acc .',
 'comput tomographi show larg bilat adren mass schemat repres method use measur interradicular space .',
 'first , cemento-enamel junction ( cej ) two adjac teeth identifi .',
 'start cej , ruler scroll toward root apex 3 mm horizont interradicular space found ; , distanc cej measur well total root length cej apex .',
 'bullet local intraop portabl imag system ( c-arm ) longitudin section – intercost space ( “ bat sign ” ) : f – subcutan fat .',
 'ice –extern intercost muscl , r – rib , horizont arrow – intern intercost muscl , upward arrow – pleura paramet evalu airway .',
 'abdomin comput tomographi ( ct ) scan retroperiton recurr mri abdomen : lymph node distant metastasi .',
 'fetu uteru seen .',
 'three-dimens reconstruct maxilla , transposit left canin first premolar .',
 'antenat ultrasound imag 20 week gestat , illustr megalourethra cystic structur balloon distal penil portion urethra .',
 'ob 600 –automat sort machin wast portabl batteries.sourc : optisort .',
 'chest radiograph show left-sid pleural effus short admiss .',
 'post mortem ct show hydrocephalu ( asterisk ) multicyst encephalomalacia ( arrow ) axial ct demonstr well-defin lesion expan buccal lingual cortic plate fa left eye normal impact fractur weight bear result screw joint penetr three month postop .',
 'doppler ultrasound perform upon patient present demonstr heterogen echotextur testicl epididymi signifi ischemia inflamm testicl necrosi epididymi ( red arrow ) .',
 'periph blood flow testicl present blood flow epididymi maintain .',
 'addit , signif hematoma visual anterior aspect testicl ( green arrow ) .',
 'plain radiograph show lytic lesion right iliac wing minim periost reaction .',
 'sagitt transperin sonographi show recurr mass patient occupi rectovagin septum .',
 'vagina fill acoust contrast .',
 'cerebr angiogram ca demonstr ophthalm arteri occlus ( arrow ) .',
 'ct scan sagitt section show coron plane fractur distal femur ( hoffa fractur ) .',
 'third degr adiposi .',
 'clear deterior dorsal transson pancrea .',
 'invi splenic vein anatom structur locat deeper .',
 'f – supraperiton fat subcutan epidermoid cyst phalang ( arrowhead ) .',
 'longitudin ultrasound show well-defin subcutan lesion variabl echogen ( anecho compon intern hyperecho debri ) pmmr hypox brain chang .',
 'axial t2-weight pmmr imag fetal post mortem brain , show exampl typic low signal chang basal ganglia may associ hypoxia .',
 'convent pmmr current distinguish antemortem postmortem hypox chang susceptibility-weight imag 7 ( 8-channel head coil ) ; imag repr minimum inten project 6 mm slab .',
 'note , vein iron contain structur like basal ganglia appear hypo inten .',
 'imag acquir use echo time 15 ms resolut 0.3 × 0.3 × 1.2 mm .',
 'primari bullet path full metal jacket two-shot techniqu axial ct scan incarc stomach ; first part duodenum seen leav inguin hernia .',
 'anteroposterior radiograph femal patient underw bilat ludloff open reduct age 5 month ; ) 1.6 year post-op , show advanc sublux femor head residu acetabular dysplasia ; b ) two month bilat salter femor derot varu osteotomi ; c ) recurr coxa valga without asept necrosi nine year age ) severin group iia hip 28 year age .',
 'immedi postop orthopentomogram sagitt te weight mr imag reveal thought complet acl ruptur ( arrow ) appreci complet ruptur arthroscopi .',
 'accord arthroscopist partial tear involv approxim 75 % ligament bodi .',
 'radiograph 39 year old male ( case report 1 ) made one year open reduct intern fixat .',
 'good boni consolid incomplet reconstruct joint line visibl .',
 'pet/ct imag .',
 'pet/ct show mass display increa fdg uptak cholangiograph find .',
 'endoscop retrograd cholangiographi use carbon dioxid insuffl show kink common bile duct 1 cm proxim end metal stent ( arrow ) .',
 'ct scan 6 month mitotan treatment show reduct size adren mass .',
 'abdomin ultrasound imag 48-year-old femal benign lesser curvatur gastric ulcer show thicken gastric wall niche-lik echogen ( arrow ) , probabl repr ulcer carter .',
 'axial cut ct-chest demonstr well-circumscrib soft tissu densiti ( * ) left breast measur 3.1×3.7 cm.abbrevi : ct , comput tomographi .',
 'supin ventral-dor abdomin x-ray immedi surgeri .',
 'right abdomin wall small hybrid rebound hrd .',
 'left side dog bone rebound hrd .',
 'pass lesion.abbrevi : cran , cranial ; rao , right anterior obliqu .',
 'increa activ upper left quadrant case 3 2nd hour .',
 'activ move toward inferior quadrant 4th hour .',
 'mri scan chest – axial view .',
 'note anterior chest wall defect tooth 3.4 reduc periap radioluc ct scan portal phase .',
 'contrast enhanc , enhanc portion lesion .',
 'pet-ct imag show inten fluorine-18 fluorodeoxygluco ( 18f–fdg ) uptak maximum standard uptak valu ( suv ) 9.0 ( arrow ) .',
 'suspect extrasplen tumor dissemin metastasi transthorac short axi parastern view measur veget 20 mm long .',
 'radiograph individu hereditari multipl exostosi .',
 'note deform forearm ( due shorten ulna ) .',
 'ct scan ( frontal view ) demonstr multipl locul air ( arrow ) .',
 'transposit ulnar nerv symptom secondari neuropathi .',
 'bend ( arrow ) nerv ( asterisk ) site enter head flexor carpi ulnari muscl short tau inver recoveri magnet reson imag show signif deviat median nerv toward fractur site radiu ( arrow ) .',
 'ultrasound scan reveal giant hepat cyst .',
 'echogen substanc visibl bottom cyst lead “ fluid-fluid ” level .',
 'pre-op radiolog view case 1 mass-lik echo , medium inten , rough distribut within echo right anterior vitreou caviti .',
 'posterior vitreou reveal `` v `` -shape echo .',
 'transgastr short axi view tranesophag echocardiographi view lunar modul mass transthorac echocardiographi demonstr secundum asd left-to-right shunt mid-esophag right ventricular inflow-outflow view , arrow point 2 cm × 2 cm mobil echogen mass probabl thrombu right ventricular outflow tract patient .',
 '15. stump lengthen procedur .',
 'magnet reson imag ( mri ) imag shoulder mass 28-year-old femal .',
 't2 fat-satur sequenc demonstr 10.6 cm hyperinten fluid collect ( white arrowhead ) multipl foci intern debri , consist rice bodi format ( black arrow ) .',
 'aortogram reveal sever aortic regurgit possibl dissect flap .',
 'postop arthroscann show boni integr achilles-calcan allograft , good integr posterosuperior tendin graft coron preoper chest ct demonstr herniat colon chest free air ( arrow ) ct scan brain show solitari metastasi , 5x4 cm , right occipit lobe , exten pariet lobe .',
 'note heterogen appear metastasi surround brain edema stand later radiograph left leg show callu format proxim fibula .',
 'faint fractur line also seen .',
 'left coronari angiogram ct measur renal papilla area 10mm2 , obtain mean area hounsfield unit .',
 'filter bleb : as-oct show elev function filter bleb .',
 'bleb moder elev homogen spongi fluid-fil space vitiligo ( red arrow ) ( seen wood ’ lamp ) .',
 'radiograph patient made 4 week osteotomi .',
 'patient report right buttock pain 3.5 week postop .',
 'fractur posterior column ( arrow ) reveal , seen figur 1. ct scan show abscess format begin around piriform sinu .',
 'protect proximal/middl segment vessel smooth , normal flow evid lumin strictur .',
 'echo-endoscop aspect chest x-ray show pneumothorax secondari block chest tube .',
 'a. pleural white line b. block chest tube axial t2 mri imag c6–7 demonstr bilat neuroforamin stenosi secondari disc protrus .',
 'intracoronari ultrasound ( ivu ) correspond lad segment demonstr fal lumen ( fl ) occupi echogen mass ( intramur hematoma ) .',
 'true lumen ( tl ) compress narrow ( white arrow : flap , c : cathet ) .',
 'ct-scan abdomen : imag show oval umbil mass measur 2 cm .',
 'comput tomographi scan show giant hepat cyst right lobe liver compress adjac diaphragm , right ventricl inferior vena cava ( arrow head ) .',
 'orthopantomograph posttreat chest comput tomographi time hospit admissiona 9-mm intermedi lobular nodul seen ( red arrow ) subpleura right lower lung .',
 'chest x-ray demonstr high posit right diaphragm due postop paralysi .',
 'anterior-posterior cross-sect extrud slab model precentr gyru .',
 '3d model construct extrud cross-sect .',
 'inva electrod place on/und dura mater epidural/subdur cortic stimul .',
 'maximum von miss stress observ c7 vertebra level pedicl ( white circular area ) load mode .',
 'posterioanterior fluoroscop imag lumbosacr spine show fusion vertebr bodi needl placement left s1 neuroforamen b-line .',
 'b-line ( arrow ) bright comet-tail artifact ari pleural line ( arrowhead ) .',
 'move lung slide , slide present , extend end screen without fade ct scan thorax femal patient intub due respiratori failur .',
 'tuberculosi subsequ cultur bronchoscopi specimen .',
 'note cavit main right upper lobe .',
 'follow-up barium enema reveal evid distal obstruct anatomi suitabl segment intestin resect enterocutan fistula .',
 'contrast reflux anu previous obstruct area , fistula .',
 'parastern long axi view systol .',
 'balloon apic segment left ventricl appar .',
 't1 coron imag : well defin mass ( long white arrow ) inferior right parotid gland ( short white arrow ) & medial sternocleidomastoid muscl ( arrowhead ) .',
 'methodolog measur retroperiton fat tissu thick use axial comput tomographi imag .',
 'measur retroperiton fat tissu thick perform slice show renal vein treat kidney side patient 7 : x-ray bone graft 4 dental implant ( imag show differ graft rest jaw ) .',
 'transver comput tomographi imag level 2nd lumbar vertebra 10 mmhg co2 insuffl pressur .',
 'trocar place right approach .',
 'maximum linear dimen ( maximum dorsoventr diamet maximum transver diamet [ red line ] ) measur separ left right side base mid‐sagitt plane medial border ( green line ) .',
 'endoscop papillari balloon dilat .',
 'dilat ectop open 8 mm diamet biliari dilat balloon .',
 'note stone next balloon .',
 'sutura temporozygomatica ( arrow ) , axial multiplanar reconstruct .',
 'initi pelvic injuri seen anteroposterior pelvic radiograph case 2 includ pubic symphysi diastasi , right sacroiliac diastasi right sacral ala fractur post-op axial ct head show intracrani patholog .',
 'incid apic de 4 cavité montrant un vg dilaté et globuleux delayed-pha ct show left renal pelvi extrava urin anterior ( arrow ) .',
 'note unopacifi urin perinephr space ( arrowhead ) color doppler ultrasound show thrombosi superfici dorsal vein peni ( arrow ) .',
 'current flow vein peni , monitor superfici dorsal vein .',
 'sagit t2-mri spinal cord show exten enhanc thorac lesion ( th1-th3 ) .',
 'coron thorac ct imag show right diaphragmat defect loop bowel protrud thorac caviti , indic white arrow .',
 'ct , comput tomographi .',
 'comput tomographi .',
 'initi tumor present ( 2006 ) .',
 'point wide field laryngectomi , right thyroid lobectomi , biopsi right upper digastr jugular node perform .',
 'final patholog reveal high-grad mucoepidermoid carcinoma .',
 '27-week fetu persist persist left superior vena cava .',
 'fetal cmr b-tfe four-chamb view imag show enlarg coronari sinu ( arrow ) t2-weight mri coron imag show hyperinten lesion .',
 'noncontrast axial head ct complet pod 1 show stabl postop chang .',
 'magnet reson imag pelvi : sagitt view .',
 'enhanc mass visibl anterior cervix comput tomographi show defect ( arrow ) aneurysm ( ) right atrium ( ra ) .',
 'lv indic left ventricl ; ao , aorta .',
 'cardiogen pulmonari oedema .',
 'numer b-line artifact ( → ) seen bilat lower middl field ; normal pleural line .',
 'linear probe later cephalogram depict type 3 ( butt shape ) pattern soft palat .',
 'comput tomographi thorax .',
 'arrow show cold abscess .',
 'mri cystic teratoma pancreat tail .',
 'enhanc magnet reson show cystic mass ari tail pancrea extend middl side stomach without defin margin .',
 'pulmonari angiogram show diffus pavm frontal radiograph pelvi taken six month show widen proxim right femor physi .',
 'four-chamb transesophag echocardiogram , show complet absenc interatri septum .',
 'ca : common atrium , lv : left ventricl , rv : right ventricl .',
 'ultrasonogram patient recurr hernia : oment herniat ( thick arrow ) seen later mesh ( thin arrow ) .',
 'suspect cartilag lesion axial comput tomographi nose parana sinus demonstr total opacif contract right maxillari sinu .',
 'present endokomvo schemat : extracorpor limb control intracorpor format triangl .',
 'linear high signal within spinal cord extend c4/c5 c7 level keep acut spinal cord infarct duplex scan infect poplit aneurysm .',
 'extern j retent wire ( arrow ) notic atrial lead .',
 'direct point , advanc laser sheath immedi possibl .',
 '45-year-old woman bmi 23.1 chest circumf 94.0 cm .',

In [42]:
import nltk
nltk.download("avergaed_perceptron_tagger")

[nltk_data] Error loading avergaed_perceptron_tagger: Package
[nltk_data]     'avergaed_perceptron_tagger' not found in index

False

In [43]:
sentences

['coron plain comput tomographi imag show multipl larg tumor mass edg enhanc insid abdomin caviti liver .',
 'axial sourc imag intracrani magnet reson angiogram reveal abnorm arteri signal elev left right cavern sinus consist carotid cavern fistula , indic arrow .',
 'apic height , homogen , thick miner trioxid aggreg plug cto rca ( closur 2nd segment ) venographi show larg amount thrombogenesi femoropoplitea vein thrombolysi .',
 'postop decrea size cyst fetal aortic arch .',
 'solid arrow repr ascend aorta dot arrow repr aortic arch distal ductu arteriosu .',
 'note alia ductal arch reflect turbul blood flow result extern compress due mass-effect .',
 'abdomin comput tomographi scan .',
 'arrow point like cholecystocutan fistul track .',
 'disten digest avec niveaux hydro-aériqu coliqu et vacuité pelvienn panoram x ray taken four year later show unilocular radioluc area left ramu .',
 'anteroposterior radiograph pelvi recent follow .',
 'immedi postinjuri magnet reson imag demonstr intact spinal cord canal cerebrospin fluid signal surround spinal cord level .',
 'arteri phase dynam ct show homogen enhanc mass ( arrow ) .',
 'level , normal right side adren gland visual .',
 'angiogram show pseudoaneurysm ( arrow ) format proxim left superfici femor arteri .',
 'imag ct fluoroscop guidanc rhizotomi demonstr radiofrequ cannular tip junction superior articular process transver process .',
 'bilet styloid process elong subject panoram radiographi .',
 'solid-cyst lesion thicken hyperecho wall .',
 'region polycycl solid structur wall lesion , color doppler ( cdu ) show tortuou arteri vessel initi chest x-ray show left tension pneumothorax shift mediastinum right , pleural effus left , basal dorsolat rib fractur .',
 "'s also air visibl right diaphragm ( arrow ) .",
 'larg subcutan tributari pierc superfici fascia join lsv thigh region .',
 'brain magnet reson imag ( mri ) gadolinium inject show imag axial ( flair sequenc ) show hyper-inten lesion white matter frontal lobe .',
 'signal abnorm cortex .',
 'note mass effect ventricular caviti midlin structur .',
 'dosimetr result obtain rapidarc .',
 'barium small bowel meal follow show normal small larg bowel .',
 'ct axial section show multilocular expansil lytic lesion bodi mandibl right side signif enhanc soft tissu matrix comput tomographi obtain 3 week admiss diagnosi aspir pneumonia show hepat portal venou ga ga within wall stomach visual portion upper abdomen postop day 1 chest radiograph reveal larg left pneumothorax .',
 'left upper lobe squamou cell cancer show broad , convex margin mediastinum ct ( arrow ) ; mediastin pleural inva surgeri patholog ( t2 tumor ) .',
 'ct scan thorax demonstr necrot paratrach node .',
 'enhanc axial ct scan thorax , mediastin window , 58-year-old femal present bilat vocal cord immobl unknown etiolog .',
 'posit serum anti-hu antibodi , high associ small cell lung carcinoma , led repeat ct scan .',
 'arrow demonstr enlarg level 4r paratrach lymph node central necrosi .',
 'see figur 2 patholog descript biopsi node .',
 'cortic bone chang rheumatoid arthriti classic radiographi show striation lamel cortic bone phalanx .',
 'twelve-year-old boy present nasopharyng angiofi broma diagno unilat meningo-ophthalm arteri anomali .',
 'comput tomographi scan show midlin nasopharyng angiofi broma ( black arrow ) , promin right-sid infiltr infratempor fossa ( white arrow ) .',
 'pelvi arthrogram show defect ossif later acetabular corner , leav signif cartilagin anlag left anterior obliqu common coronari arteri branch critic disea proxim rca , mid/dist anom lcx .',
 'calcul inferior vena cava collap index ( [ a–b ] /b ) ( % ) use ultrasonographi ct guid core biopsi infracol oment cake .',
 'initi radiograph show right femor neck fractur sclerot superior cortex undisplac linear pattern .',
 't2-weight mr sagitt imag show isointen schwannoma cauda equina compress s3 level .',
 'magnet reson angiographi present show giant intracrani aneurysm onset ectasia left carotid siphon .',
 'mri right elbow ( t2 imag ) demonstr fusion proxim one-third ulna radiu .',
 'note anterior disloc radial head , joint fluid effus , tension anterior capsul , edema signal anterior soft tissu .',
 'anteroposterior chest radiograph show cardiomegali well irregular contour later margin descend thorac aorta ( arrow ) .',
 'chest x-ray show mild increa transver cardiac diamet .',
 'left cardiac border protrud left mild .',
 'comput tomographi reveal dilat intrahepat biliari duct .',
 'pneumocysti pneumonia aid patient .',
 'hrct level upper lobe reveal mix “ ground-glass cystic pattern ” characteri presenc diffus area ground-glass opac thin-wal multilocular cyst fail consolid treatment nail alon .',
 'elast stabl intramedullari nail combin orthoss® gps® earlier fail treatment .',
 'radiograph three month follow initi gps®/orthoss® treatment result bone miner .',
 'ct scan show larg left ovarian cyst hc diamet 0.37 cm left hippocampu note t1-weight imag level hippocampu fragment humer head step thorac aorta ( black arrow ) ultrasound imag bovin liver depict tip ( arrow ) two cannula insert use introduc set prior rf ablat .',
 'two hyperecho tip , posterior acoust shadow visibl .',
 'aortic root demonstr linear measur patient suffer dissect .',
 '( case # 2 ) comput tomographi abdomen show right upper quadrant abdomin pseudocyst ( arrow ) near gastric outlet renal manifest ct abdomen .',
 'bilat nephromegali ( greater 2 standard deviat age ) , nephrocalcinosi ( red box ) .',
 'abdomin ct find reveal remain round foreign bodi appendix , dilat appendix .',
 'mri find .',
 'cystic duct seen .',
 'six week partial medial meniscectomi , coron fat-satur t2-weight imag show subchondr fractur medial femor condyl ( larg arrow ) mark surround marrow edema pattern well smaller subchondr fractur central aspect later femor condyl ( small arrow ) less exten adjac marrow edema pattern .',
 'case unusu given subchondr fractur compart ; usual , fractur occur compart prior partial meniscectomi radial split complex tear posterior horn root .',
 'ct scan imag opacif bladder demonstr extra-periton extrava infus contrast posterior aspect bladder radiograph appear 6 month show lesion disappear .',
 'abdomin mri demonstr cyst ( asterisk ) intim relat left lobe liver ( l ) , spleen ( ) gastric bodi ( g ) , still without clear demonstr plane structur .',
 'transoesophag echocardiogram demonstr mass ( fibroelastoma ) left ventricular outflow tract immedi surgeri : enucl cyst & fixat bend 8-hole plate five screw ; extract # 26. radiograph chest reveal bilat pleural effus .',
 'feli catu , adult , longitudin section middl ear gener avizo®7 ct data [ 42 ] ( see text method ) .seam tympan plate mallear rostral process ectotympan mark caret .',
 'scale = 2 mm .',
 'abbrevi : ecto , ectotympan ; en , ectotympan notch ; hm , head malleu ; , incu ; mh , mallear hook ; ol , osseou lamina ; pet , petro ; tp , tympan plate rostral process .',
 'axial section cect abdomen show enlarg left psoa muscl ill-defin hypoden area ( star ) retroperiton fat strand ( solid arrow ) .',
 'fluid collect multipl air pocket seen left posterior preperiton space ( hollow arrow ) .',
 'ct treatment demonstr pack coil seat right acc hypogloss canal ( treat 5 year ago ) left acc .',
 'comput tomographi show larg bilat adren mass schemat repres method use measur interradicular space .',
 'first , cemento-enamel junction ( cej ) two adjac teeth identifi .',
 'start cej , ruler scroll toward root apex 3 mm horizont interradicular space found ; , distanc cej measur well total root length cej apex .',
 'bullet local intraop portabl imag system ( c-arm ) longitudin section – intercost space ( “ bat sign ” ) : f – subcutan fat .',
 'ice –extern intercost muscl , r – rib , horizont arrow – intern intercost muscl , upward arrow – pleura paramet evalu airway .',
 'abdomin comput tomographi ( ct ) scan retroperiton recurr mri abdomen : lymph node distant metastasi .',
 'fetu uteru seen .',
 'three-dimens reconstruct maxilla , transposit left canin first premolar .',
 'antenat ultrasound imag 20 week gestat , illustr megalourethra cystic structur balloon distal penil portion urethra .',
 'ob 600 –automat sort machin wast portabl batteries.sourc : optisort .',
 'chest radiograph show left-sid pleural effus short admiss .',
 'post mortem ct show hydrocephalu ( asterisk ) multicyst encephalomalacia ( arrow ) axial ct demonstr well-defin lesion expan buccal lingual cortic plate fa left eye normal impact fractur weight bear result screw joint penetr three month postop .',
 'doppler ultrasound perform upon patient present demonstr heterogen echotextur testicl epididymi signifi ischemia inflamm testicl necrosi epididymi ( red arrow ) .',
 'periph blood flow testicl present blood flow epididymi maintain .',
 'addit , signif hematoma visual anterior aspect testicl ( green arrow ) .',
 'plain radiograph show lytic lesion right iliac wing minim periost reaction .',
 'sagitt transperin sonographi show recurr mass patient occupi rectovagin septum .',
 'vagina fill acoust contrast .',
 'cerebr angiogram ca demonstr ophthalm arteri occlus ( arrow ) .',
 'ct scan sagitt section show coron plane fractur distal femur ( hoffa fractur ) .',
 'third degr adiposi .',
 'clear deterior dorsal transson pancrea .',
 'invi splenic vein anatom structur locat deeper .',
 'f – supraperiton fat subcutan epidermoid cyst phalang ( arrowhead ) .',
 'longitudin ultrasound show well-defin subcutan lesion variabl echogen ( anecho compon intern hyperecho debri ) pmmr hypox brain chang .',
 'axial t2-weight pmmr imag fetal post mortem brain , show exampl typic low signal chang basal ganglia may associ hypoxia .',
 'convent pmmr current distinguish antemortem postmortem hypox chang susceptibility-weight imag 7 ( 8-channel head coil ) ; imag repr minimum inten project 6 mm slab .',
 'note , vein iron contain structur like basal ganglia appear hypo inten .',
 'imag acquir use echo time 15 ms resolut 0.3 × 0.3 × 1.2 mm .',
 'primari bullet path full metal jacket two-shot techniqu axial ct scan incarc stomach ; first part duodenum seen leav inguin hernia .',
 'anteroposterior radiograph femal patient underw bilat ludloff open reduct age 5 month ; ) 1.6 year post-op , show advanc sublux femor head residu acetabular dysplasia ; b ) two month bilat salter femor derot varu osteotomi ; c ) recurr coxa valga without asept necrosi nine year age ) severin group iia hip 28 year age .',
 'immedi postop orthopentomogram sagitt te weight mr imag reveal thought complet acl ruptur ( arrow ) appreci complet ruptur arthroscopi .',
 'accord arthroscopist partial tear involv approxim 75 % ligament bodi .',
 'radiograph 39 year old male ( case report 1 ) made one year open reduct intern fixat .',
 'good boni consolid incomplet reconstruct joint line visibl .',
 'pet/ct imag .',
 'pet/ct show mass display increa fdg uptak cholangiograph find .',
 'endoscop retrograd cholangiographi use carbon dioxid insuffl show kink common bile duct 1 cm proxim end metal stent ( arrow ) .',
 'ct scan 6 month mitotan treatment show reduct size adren mass .',
 'abdomin ultrasound imag 48-year-old femal benign lesser curvatur gastric ulcer show thicken gastric wall niche-lik echogen ( arrow ) , probabl repr ulcer carter .',
 'axial cut ct-chest demonstr well-circumscrib soft tissu densiti ( * ) left breast measur 3.1×3.7 cm.abbrevi : ct , comput tomographi .',
 'supin ventral-dor abdomin x-ray immedi surgeri .',
 'right abdomin wall small hybrid rebound hrd .',
 'left side dog bone rebound hrd .',
 'pass lesion.abbrevi : cran , cranial ; rao , right anterior obliqu .',
 'increa activ upper left quadrant case 3 2nd hour .',
 'activ move toward inferior quadrant 4th hour .',
 'mri scan chest – axial view .',
 'note anterior chest wall defect tooth 3.4 reduc periap radioluc ct scan portal phase .',
 'contrast enhanc , enhanc portion lesion .',
 'pet-ct imag show inten fluorine-18 fluorodeoxygluco ( 18f–fdg ) uptak maximum standard uptak valu ( suv ) 9.0 ( arrow ) .',
 'suspect extrasplen tumor dissemin metastasi transthorac short axi parastern view measur veget 20 mm long .',
 'radiograph individu hereditari multipl exostosi .',
 'note deform forearm ( due shorten ulna ) .',
 'ct scan ( frontal view ) demonstr multipl locul air ( arrow ) .',
 'transposit ulnar nerv symptom secondari neuropathi .',
 'bend ( arrow ) nerv ( asterisk ) site enter head flexor carpi ulnari muscl short tau inver recoveri magnet reson imag show signif deviat median nerv toward fractur site radiu ( arrow ) .',
 'ultrasound scan reveal giant hepat cyst .',
 'echogen substanc visibl bottom cyst lead “ fluid-fluid ” level .',
 'pre-op radiolog view case 1 mass-lik echo , medium inten , rough distribut within echo right anterior vitreou caviti .',
 'posterior vitreou reveal `` v `` -shape echo .',
 'transgastr short axi view tranesophag echocardiographi view lunar modul mass transthorac echocardiographi demonstr secundum asd left-to-right shunt mid-esophag right ventricular inflow-outflow view , arrow point 2 cm × 2 cm mobil echogen mass probabl thrombu right ventricular outflow tract patient .',
 '15. stump lengthen procedur .',
 'magnet reson imag ( mri ) imag shoulder mass 28-year-old femal .',
 't2 fat-satur sequenc demonstr 10.6 cm hyperinten fluid collect ( white arrowhead ) multipl foci intern debri , consist rice bodi format ( black arrow ) .',
 'aortogram reveal sever aortic regurgit possibl dissect flap .',
 'postop arthroscann show boni integr achilles-calcan allograft , good integr posterosuperior tendin graft coron preoper chest ct demonstr herniat colon chest free air ( arrow ) ct scan brain show solitari metastasi , 5x4 cm , right occipit lobe , exten pariet lobe .',
 'note heterogen appear metastasi surround brain edema stand later radiograph left leg show callu format proxim fibula .',
 'faint fractur line also seen .',
 'left coronari angiogram ct measur renal papilla area 10mm2 , obtain mean area hounsfield unit .',
 'filter bleb : as-oct show elev function filter bleb .',
 'bleb moder elev homogen spongi fluid-fil space vitiligo ( red arrow ) ( seen wood ’ lamp ) .',
 'radiograph patient made 4 week osteotomi .',
 'patient report right buttock pain 3.5 week postop .',
 'fractur posterior column ( arrow ) reveal , seen figur 1. ct scan show abscess format begin around piriform sinu .',
 'protect proximal/middl segment vessel smooth , normal flow evid lumin strictur .',
 'echo-endoscop aspect chest x-ray show pneumothorax secondari block chest tube .',
 'a. pleural white line b. block chest tube axial t2 mri imag c6–7 demonstr bilat neuroforamin stenosi secondari disc protrus .',
 'intracoronari ultrasound ( ivu ) correspond lad segment demonstr fal lumen ( fl ) occupi echogen mass ( intramur hematoma ) .',
 'true lumen ( tl ) compress narrow ( white arrow : flap , c : cathet ) .',
 'ct-scan abdomen : imag show oval umbil mass measur 2 cm .',
 'comput tomographi scan show giant hepat cyst right lobe liver compress adjac diaphragm , right ventricl inferior vena cava ( arrow head ) .',
 'orthopantomograph posttreat chest comput tomographi time hospit admissiona 9-mm intermedi lobular nodul seen ( red arrow ) subpleura right lower lung .',
 'chest x-ray demonstr high posit right diaphragm due postop paralysi .',
 'anterior-posterior cross-sect extrud slab model precentr gyru .',
 '3d model construct extrud cross-sect .',
 'inva electrod place on/und dura mater epidural/subdur cortic stimul .',
 'maximum von miss stress observ c7 vertebra level pedicl ( white circular area ) load mode .',
 'posterioanterior fluoroscop imag lumbosacr spine show fusion vertebr bodi needl placement left s1 neuroforamen b-line .',
 'b-line ( arrow ) bright comet-tail artifact ari pleural line ( arrowhead ) .',
 'move lung slide , slide present , extend end screen without fade ct scan thorax femal patient intub due respiratori failur .',
 'tuberculosi subsequ cultur bronchoscopi specimen .',
 'note cavit main right upper lobe .',
 'follow-up barium enema reveal evid distal obstruct anatomi suitabl segment intestin resect enterocutan fistula .',
 'contrast reflux anu previous obstruct area , fistula .',
 'parastern long axi view systol .',
 'balloon apic segment left ventricl appar .',
 't1 coron imag : well defin mass ( long white arrow ) inferior right parotid gland ( short white arrow ) & medial sternocleidomastoid muscl ( arrowhead ) .',
 'methodolog measur retroperiton fat tissu thick use axial comput tomographi imag .',
 'measur retroperiton fat tissu thick perform slice show renal vein treat kidney side patient 7 : x-ray bone graft 4 dental implant ( imag show differ graft rest jaw ) .',
 'transver comput tomographi imag level 2nd lumbar vertebra 10 mmhg co2 insuffl pressur .',
 'trocar place right approach .',
 'maximum linear dimen ( maximum dorsoventr diamet maximum transver diamet [ red line ] ) measur separ left right side base mid‐sagitt plane medial border ( green line ) .',
 'endoscop papillari balloon dilat .',
 'dilat ectop open 8 mm diamet biliari dilat balloon .',
 'note stone next balloon .',
 'sutura temporozygomatica ( arrow ) , axial multiplanar reconstruct .',
 'initi pelvic injuri seen anteroposterior pelvic radiograph case 2 includ pubic symphysi diastasi , right sacroiliac diastasi right sacral ala fractur post-op axial ct head show intracrani patholog .',
 'incid apic de 4 cavité montrant un vg dilaté et globuleux delayed-pha ct show left renal pelvi extrava urin anterior ( arrow ) .',
 'note unopacifi urin perinephr space ( arrowhead ) color doppler ultrasound show thrombosi superfici dorsal vein peni ( arrow ) .',
 'current flow vein peni , monitor superfici dorsal vein .',
 'sagit t2-mri spinal cord show exten enhanc thorac lesion ( th1-th3 ) .',
 'coron thorac ct imag show right diaphragmat defect loop bowel protrud thorac caviti , indic white arrow .',
 'ct , comput tomographi .',
 'comput tomographi .',
 'initi tumor present ( 2006 ) .',
 'point wide field laryngectomi , right thyroid lobectomi , biopsi right upper digastr jugular node perform .',
 'final patholog reveal high-grad mucoepidermoid carcinoma .',
 '27-week fetu persist persist left superior vena cava .',
 'fetal cmr b-tfe four-chamb view imag show enlarg coronari sinu ( arrow ) t2-weight mri coron imag show hyperinten lesion .',
 'noncontrast axial head ct complet pod 1 show stabl postop chang .',
 'magnet reson imag pelvi : sagitt view .',
 'enhanc mass visibl anterior cervix comput tomographi show defect ( arrow ) aneurysm ( ) right atrium ( ra ) .',
 'lv indic left ventricl ; ao , aorta .',
 'cardiogen pulmonari oedema .',
 'numer b-line artifact ( → ) seen bilat lower middl field ; normal pleural line .',
 'linear probe later cephalogram depict type 3 ( butt shape ) pattern soft palat .',
 'comput tomographi thorax .',
 'arrow show cold abscess .',
 'mri cystic teratoma pancreat tail .',
 'enhanc magnet reson show cystic mass ari tail pancrea extend middl side stomach without defin margin .',
 'pulmonari angiogram show diffus pavm frontal radiograph pelvi taken six month show widen proxim right femor physi .',
 'four-chamb transesophag echocardiogram , show complet absenc interatri septum .',
 'ca : common atrium , lv : left ventricl , rv : right ventricl .',
 'ultrasonogram patient recurr hernia : oment herniat ( thick arrow ) seen later mesh ( thin arrow ) .',
 'suspect cartilag lesion axial comput tomographi nose parana sinus demonstr total opacif contract right maxillari sinu .',
 'present endokomvo schemat : extracorpor limb control intracorpor format triangl .',
 'linear high signal within spinal cord extend c4/c5 c7 level keep acut spinal cord infarct duplex scan infect poplit aneurysm .',
 'extern j retent wire ( arrow ) notic atrial lead .',
 'direct point , advanc laser sheath immedi possibl .',
 '45-year-old woman bmi 23.1 chest circumf 94.0 cm .',

In [44]:
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.

True

In [45]:
for i in range(len(sentences)):
      words=nltk.word_tokenize(sentences[i])
      pos_tag=nltk.pos_tag(words)
      print(pos_tag)

Streaming output truncated to the last 5000 lines.
[('intern', 'JJ'), ('bright', 'JJ'), ('signal', 'NN'), ('inferior', 'NN'), ('rectu', 'NN'), ('muscle.a', 'NN'), ('high', 'JJ'), ('inten', 'JJ'), ('area', 'NN'), ('inferior', 'JJ'), ('rectu', 'NN'), ('muscl', 'NN'), ('measur', 'VBD'), ('t1-weight', 'JJ'), ('coron', 'NN'), ('magnet', 'NN'), ('reson', 'NN'), ('imag', 'NN'), ('(', '('), ('arrow', 'NN'), (')', ')'), ('.', '.')]
[('later', 'RB'), ('view', 'NN'), ('x-ray', 'JJ'), ('lumbar', 'NN'), ('spine', 'NN'), ('fal', 'NN'), ('aneurysm', 'NN'), ('segment', 'NN'), ('arteri', 'NN'), ('left', 'VBD'), ('lobe', 'NN'), ('.', '.')]
[('pulmonari', 'NN'), ('angiographi', 'NN'), ('hemoptysi', 'NN'), ('present', 'JJ'), ('extrava', 'NN'), ('contrast', 'NN'), ('media', 'NNS'), ('segment', 'NN'), ('arteri', 'NN'), ('left', 'VBD'), ('lobe', 'JJ'), ('format', 'JJ'), ('fal', 'NN'), ('aneurysm', 'NN'), ('.', '.')]
[('56-year-old', 'JJ'), ('woman', 'NN'), ('present', 'JJ'), ('emerg', 'JJ'), ('depart', 'NN'), ('left', 'VBD'), ('painless', 'JJ'), ('dorsolumbar', 'NN'), ('fluctuat', 'NN'), ('mass', 'NN'), ('progress', 'NN'), ('grow', 'VBD'), ('3', 'CD'), ('month', 'NN'), ('.', '.')]
[('ultrasonographi', 'JJ'), ('first', 'JJ'), ('imag', 'NN'), ('studi', 'NN'), ('obtain', 'VB'), ('.', '.')]
[('long-axi', 'JJ'), ('view', 'NN'), ('left', 'VBD'), ('kidney', 'NN'), ('show', 'NN'), ('subcutan', 'JJ'), ('pariet', 'JJ'), ('multilocul', 'NN'), ('heterogen', 'NN'), ('hypoecho', 'NN'), ('collect', 'NN'), (',', ','), ('compat', 'NN'), ('abscess', 'NN'), ('adjac', 'NN'), ('left', 'VBD'), ('kidney', 'NN'), ('(', '('), ('red', 'JJ'), ('arrow', 'NN'), (')', ')'), ('.', '.')]
[('moder', 'NN'), ('left', 'VBD'), ('hydronephrosi', 'NN'), ('also', 'RB'), ('present', 'JJ'), ('(', '('), ('white', 'JJ'), ('arrowhead', 'NN'), (')', ')'), ('.', '.')]
[('enlarg', 'RB'), ('view', 'NN'), ('ct', 'JJ'), ('scan', 'JJ'), ('imag', 'NN'), ('cross', 'NN'), ('section', 'NN'), (',', ','), ('show', 'VBP'), ('larg', 'JJ'), ('well-circumscrib', 'JJ'), ('mild', 'NN'), ('enhanc', 'NN'), ('mass', 'NN'), ('calcif', 'NN'), ('left', 'VBD'), ('supraren', 'JJ'), ('region', 'NN'), ('.', '.')]
[('preoper', 'NN'), ('anteroposterior', 'JJ'), ('radiograph', 'NN'), ('75-year-old', 'JJ'), ('femal', 'JJ'), ('reveal', 'NN'), ('fix', 'JJ'), ('malposit', 'NN'), ('acetabular', 'JJ'), ('compon', 'NN'), ('(', '('), ('cement', 'NN'), (')', ')'), ('.', '.')]
[('implant', 'JJ'), ('stent', 'NN'), (',', ','), ('diamet', 'VBD'), ('aorta', 'JJ'), ('increa', 'NN'), ('(', '('), ('arrow', 'NN'), (')', ')'), ('pressur', 'NN'), ('gradient', 'NN'), ('across', 'IN'), ('coarctat', 'JJ'), ('decrea', 'NN'), ('0', 'CD'), ('mm', 'NN'), ('hg', 'NN'), ('pre-op', 'NN'), ('later', 'RB'), ('radiograph', 'VB'), ('show', 'NN'), ('signif', 'JJ'), ('cranio-atl', 'JJ'), ('anterior', 'JJ'), ('disloc', 'NN'), ('angul', 'NN'), ('axi', 'NN'), ('.', '.')]
[('initi', 'JJ'), ('sagitt', 'NN'), ('comput', 'NN'), ('tomographi', 'JJ'), ('scan', 'JJ'), ('fractur', 'NN'), ('calcaneu', 'NN'), ('.', '.')]
[('later', 'RB'), ('radiograph', 'NN'), ('.', '.')]
[('63-year-old', 'JJ'), ('man', 'NN'), ('show', 'NN'), ('orbit', 'VBZ'), ('fat', 'JJ'), ('prolap', 'NN'), ('.', '.')]
[('orbit', 'NN'), ('prolap', 'JJ'), ('length', 'NN'), ('(', '('), ('5.9', 'CD'), ('mm', 'NN'), (')', ')'), ('shown', 'VBN'), ('white', 'JJ'), ('line', 'NN'), ('.', '.')]
[('orbiculari', 'JJ'), ('oculi', 'MD'), ('muscl', 'VB'), ('thick', 'NN'), ('(', '('), ('1.8', 'CD'), ('mm', 'NN'), (')', ')'), ('shown', 'VBN'), ('black', 'JJ'), ('line', 'NN'), ('hiatal', 'JJ'), ('region', 'NN'), ('75-year-old', 'JJ'), ('femal', 'JJ'), ('patient', 'NN'), ('1', 'CD'), ('year', 'NN'), ('implant', 'NN'), ('permacol®', 'NN'), ('mesh', 'JJ'), ('describ', 'NN'), ('.', '.')]
[('arrow', 'NN'), ('show', 'NN'), ('posit', 'NN'), ('mesh', 'NN'), ('.', '.')]
[('upper', 'JJ'), ('endoscopi', 'NN'), ('show', 'NN'), ('mild', 'JJ'), ('gastriti', 'NN'), ('without', 'IN'), ('sign', 'NN'), ('esophag', 'NN'), ('reflux', 'NN'), ('time', 'NN'), ('.', '.')]
[('imag', 'NN'), ('panorametri', 'NN'), ('trace', 'NN'), ('panoram', 'NN'), ('radiographi', 'NN'), ('inform', 'NN'), ('bilat', 'JJ'), ('bone-d', 'JJ'), ('angular', 'JJ'), ('measur', 'NN'), ('mandibl', 'NN'), ('.', '.')]
[('clariti', 'NN'), (',', ','), ('differ', 'VBP'), ('possibl', 'JJ'), ('describ', 'NN'), ('text', 'NN'), ('present', 'NN'), ('(', '('), ('may', 'MD'), ('seen', 'VBN'), ('prece', 'VB'), ('figur', 'NN'), (')', ')'), ('.', '.')]
[('besid', 'NN'), ('differ', 'NN'), ('linear', 'JJ'), ('angular', 'JJ'), ('measur', 'NN'), (',', ','), ('triangular', 'JJ'), ('area', 'NN'), ('may', 'MD'), ('also', 'RB'), ('measur', 'VB'), ('compar', 'JJ'), ('term', 'NN'), ('surfac', 'NN'), ('.', '.')]
[('see', 'VB'), ('adequaci', 'JJ'), ('48', 'CD'), ('ax', 'NN'), ('(', '('), ('arrow', 'NN'), (')', ')'), ('determin', 'NN'), ('angl', 'JJ'), ('hrp', 'NN'), ('.', '.')]
[('also', 'RB'), ('point', 'NN'), ('possibl', 'NN'), ('linear', 'JJ'), ('intercoronali', 'NN'), ('measur', 'NN'), (',', ','), ('38-', 'JJ'), ('ml', 'NN'), ('(', '('), ('90°', 'CD'), (')', ')'), ('38-', 'CD'), ('l', 'NN'), ('mpgo', 'NN'), ('(', '('), ('pink', 'NN'), (')', ')'), ('.', '.')]
[('ct', 'NN'), ('imag', 'VBZ'), ('ischem', 'JJ'), ('chang', 'NN'), ('right', 'RB'), ('occipit', 'JJ'), ('region', 'NN'), ('.', '.')]
[('mri', 'NN'), ('brain', 'NN'), ('postcontrast', 'IN'), ('t1-weight', 'JJ'), ('imag', 'NN'), ('depict', 'NN'), ('ectop', 'JJ'), ('locat', 'NN'), ('posterior', 'NN'), ('pituitari', 'NN'), ('gland', 'NN'), ('.', '.')]
[('increa', 'JJ'), ('signal', 'NN'), ('found', 'VBD'), ('floor', 'NN'), ('third', 'JJ'), ('ventricl', 'NN'), ('within', 'IN'), ('sella', 'NN'), ('turcica', 'NN'), ('.', '.')]
[('mri', 'NN'), (',', ','), ('magnet', 'NN'), ('reson', 'NN'), ('imag', 'NN'), ('.', '.')]
[('three', 'CD'), ('month', 'NN'), ('post', 'NN'), ('oper', 'IN'), ('radiograph', 'NN'), ('right', 'JJ'), ('hand', 'NN'), ('coron', 'NN'), ('stir', 'NN'), ('imag', 'NN'), ('reveal', 'NN'), ('swollen', 'VBN'), ('hyperinten', 'JJ'), ('divi', 'NN'), ('cord', 'NN'), ('left', 'VBD'), ('brachial', 'JJ'), ('plexu', 'NN'), ('suggest', 'JJS'), ('postganglion', 'NN'), ('neuroprax', 'NN'), ('injuri', 'NN'), ('mri', 'NN'), ('imag', 'NN'), ('brain', 'NN'), ('(', '('), ('t1', 'JJ'), ('weight', 'NN'), ('imag', 'NN'), (')', ')'), ('.', '.')]
[('arrow', 'NN'), ('indic', 'JJ'), ('ectop', 'JJ'), ('posterior', 'NN'), ('lobe', 'NN'), ('.', '.')]
[('pituitari', 'NN'), ('hypoplasia', 'NN'), ('observ', 'NN'), ('.', '.')]
[('pituitari', 'NN'), ('stalk', 'NN'), ('interrupt', 'NN'), ('.', '.')]
[('mri', 'NN'), ('show', 'VB'), ('right-sid', 'JJ'), ('neurovascular', 'JJ'), ('contact', 'NN'), ('basilar', 'JJ'), ('arteri', 'NN'), ('trigemin', 'NN'), ('nerv', 'NN'), ('.', '.')]
[('may', 'MD'), ('look', 'VB'), ('like', 'IN'), ('anterior', 'JJ'), ('inferior', 'JJ'), ('cerebellar', 'NN'), ('arteri', 'NN'), ('(', '('), ('aica', 'NN'), (')', ')'), ('fact', 'NN'), ('also', 'RB'), ('compress', 'JJ'), ('trigemin', 'NN'), ('nerv', 'NN'), (',', ','), ('treat', 'NN'), ('neurosurgeon', 'NN'), ('(', '('), ('pr', 'NN'), (')', ')'), ('find', 'VBP'), ('case', 'NN'), ('surgeri', 'NN'), ('.', '.')]
[('cubit', 'NN'), ('vein', 'JJ'), ('angiographi', 'NN'), ('.', '.')]
[('passag', 'NN'), ('axillari', 'NN'), ('vein', 'NN'), ('subclavian', 'JJ'), ('vein', 'NN'), ('observ', 'NN'), ('.', '.')]
[('left', 'VBN'), ('arrow', 'JJ'), ('indic', 'JJ'), ('axillari', 'NN'), ('vein', 'NN'), ('right', 'JJ'), ('arrow', 'NN'), ('indic', 'JJ'), ('subclavian', 'JJ'), ('vein', 'NN'), ('.', '.')]
[('57-year-old', 'JJ'), ('femal', 'JJ'), ('cerebrovascular', 'NN'), ('accid', 'NN'), ('present', 'JJ'), ('sudden', 'JJ'), ('onset', 'NN'), ('loss', 'NN'), ('tast', 'NN'), ('tongu', 'JJ'), ('deviat', 'NN'), ('.', '.')]
[('panoram', 'NN'), ('radiograph', 'NN'), ('show', 'VBP'), ('widen', 'JJ'), ('right', 'RB'), ('mandibular', 'JJ'), ('canal', 'NN'), ('(', '('), ('arrow', 'NN'), (')', ')'), ('.', '.')]
[('transperin', 'JJ'), ('sonographi', 'NN'), ('normal', 'JJ'), ('femal', 'JJ'), ('anatomi', 'NN'), ('shown', 'VBN'), ('.', '.')]
[('transperin', 'JJ'), ('sonogram', 'NN'), ('normal', 'JJ'), ('one-week-old', 'JJ'), ('girl', 'NN'), ('show', 'NN'), ('bladder', 'NN'), ('(', '('), ('b', 'NN'), (')', ')'), (',', ','), ('symphysi', 'JJ'), ('pubi', 'NN'), ('(', '('), (')', ')'), ('vagina', 'NN'), ('(', '('), ('v', 'NN'), (')', ')'), ('urethra', 'NN'), ('(', '('), ('u', 'JJ'), (')', ')'), ('rectum', 'NN'), ('(', '('), ('r', 'NN'), (')', ')'), ('normal', 'JJ'), ('rectum', 'NN'), ('direct', 'JJ'), ('posterior', 'JJ'), ('anu', 'NN'), ('shown', 'VBN'), ('.', '.')]
[('echogen', 'NN'), ('fat', 'JJ'), ('plane', 'NN'), ('present', 'JJ'), ('rectum', 'NN'), ('vagina', 'NN'), ('(', '('), ('arrow', 'NN'), (')', ')'), ('.', '.')]
[('ct', 'JJ'), ('scan', 'JJ'), (':', ':'), ('sagitt', 'JJ'), ('reconstruct', 'NN'), ('show', 'NN'), ('stomach', 'NN'), ('(', '('), ('contrast', 'NN'), (')', ')'), ('herniat', 'NN'), ('thorax', 'NN'), ('defect', 'JJ'), ('diaphragm-', 'JJ'), ('‘', 'NN'), ('collar', 'JJ'), ('sign/hourglass', 'NN'), ('sign', 'NN'), ('’', 'NNP'), ('.', '.')]
[('t1', 'NN'), ('mri', 'NN'), ('neck', 'NN'), ('show', 'NN'), ('inva', 'JJ'), ('trachea', 'NN'), ('.', '.')]
[('newspap', 'JJ'), ('caricatur', 'NN'), ('mari', 'NN'), ('warnock', 'NN'), ('.', '.')]
[('reproduc', 'NN'), ('courtesi', 'NN'), ('joe', 'NN'), ('cummings.59', 'NN'), ('irm', 'NN'), ('orbitair', 'NN'), ('de', 'IN'), ('contrôl', 'FW'), ('montr', 'FW'), ('une', 'JJ'), ('exten', 'FW'), ('de', 'FW'), ('la', 'FW'), ('nécrose', 'FW'), ('au', 'FW'), ('sinu', 'FW'), ('éthmoïdal', 'FW'), ('et', 'FW'), ('au', 'FW'), ('contenu', 'NN'), ('orbitair', 'NN'), ('ct', 'NN'), ('show', 'VBP'), ('small', 'JJ'), ('bowel', 'NN'), ('dome', 'NN'), ('anterior', 'JJ'), ('bladder', 'NN'), ('wall', 'NN'), ('.', '.')]
[('chest', 'VB'), ('x-ray', 'JJ'), ('3', 'CD'), ('month', 'NN'), ('show', 'NN'), ('elev', 'RB'), ('right', 'JJ'), ('hemidiaphragm', 'NN'), ('associ', 'NN'), ('basal', 'NN'), ('atelectasi', 'RB'), ('right', 'JJ'), ('lower', 'JJR'), ('lobe', 'NN'), ('pleural', 'JJ'), ('effus', 'NN'), ('.', '.')]
[('fundu', 'NN'), ('photograph', 'NN'), ('case', 'NN'), ('show', 'NN'), ('choroid', 'VBZ'), ('neovascular', 'JJ'), ('membran', 'NN'), ('peripapillari', 'NN'), ('atrophi', 'NN'), ('.', '.')]
[('vilkki', 'JJ'), ('metatarsal-phalang', 'JJ'), ('transfer', 'NN'), ('.', '.')]
[('upright', 'JJ'), ('posteroanterior', 'JJ'), ('chest', 'NN'), ('radiograph', 'NN'), ('.', '.')]
[('free', 'JJ'), ('subdiaphragmat', 'NN'), ('air', 'NN'), ('bilat', 'JJ'), ('clear', 'JJ'), ('note', 'NN'), ('right', 'JJ'), ('side', 'NN'), ('(', '('), ('white', 'JJ'), ('arrow', 'NN'), (')', ')'), ('.', '.')]
[('ct', 'NN'), ('(', '('), ('sagitt', 'JJ'), ('view', 'NN'), (')', ')'), ('cervic', 'NN'), ('region', 'NN'), ('show', 'NN'), ('normal', 'JJ'), ('post-op', 'JJ'), ('chang', 'NN'), ('.', '.')]
[('coil', 'JJ'), ('central', 'JJ'), ('venou', 'NN'), ('cathet', 'NN'), ('axial', 'JJ'), ('t1', 'NN'), ('weight', 'VBD'), ('contrast-enhanc', 'NN'), ('mri', 'NN'), ('imag', 'NN'), ('show', 'NN'), ('left', 'VBD'), ('oropharyng', 'JJ'), ('mass', 'NN'), ('.', '.')]
[('axial', 'JJ'), ('tse', 'NN'), ('t2', 'NN'), ('mr', 'NN'), ('imag', 'NN'), (';', ':'), ('slight', 'JJ'), ('heterogen', 'NN'), ('hyperinten', 'NN'), ('lesion', 'NN'), ('seen', 'VBN'), ('level', 'NN'), ('t2–t3', 'NN'), ('.', '.')]
[('endobronchi', 'JJ'), ('ultrasonographi', 'JJ'), ('anthracofibrosi', 'NN'), ('protrud', 'NN'), ('bronchial', 'JJ'), ('lumen', 'NNS'), ('.', '.')]
[('note', 'NN'), ('hyperecho', 'NN'), ('nodul', 'NN'), ('insid', 'NN'), ('lesion', 'NN'), ('.', '.')]
[('complet', 'NN'), ('disrupt', 'VB'), ('facial', 'JJ'), ('complex', 'JJ'), ('cranium', 'NN'), (',', ','), ('consist', 'JJ'), ('lefort', 'NN'), (',', ','), ('ii', 'JJ'), ('iii', 'NN'), ('fractur', 'NN'), ('epidurogram', 'JJ'), ('reveal', 'NN'), ('unilat', 'JJ'), ('spread', 'NN'), ('contrast', 'NN'), ('medium', 'NN'), ('.', '.')]
[('non-contrast', 'JJ'), ('t1-weight', 'JJ'), ('sagitt', 'NN'), ('mr', 'NN'), ('imag', 'NN'), ('show', 'NN'), ('mild', 'JJ'), ('diffus', 'NN'), ('hyperinten', 'VB'), ('right', 'JJ'), ('basal', 'NN'), ('ganglia', 'NNS'), ('.', '.')]
[('long', 'RB'), ('segment', 'NN'), ('stenosi', 'NN'), ('right', 'JJ'), ('cervic', 'NN'), ('ica', 'NN'), ('mid', 'NN'), ('distal', 'JJ'), ('portion', 'NN'), ('.', '.')]
[('sever', 'RB'), ('stenosi', 'JJ'), ('lumin', 'NN'), ('narrow', 'JJ'), ('greater', 'JJR'), ('80', 'CD'), ('%', 'NN'), ('.', '.')]
[('mild', 'JJ'), ('lumin', 'NN'), ('irregular', 'NN'), ('mid', 'NN'), ('distal', 'JJ'), ('left', 'VBD'), ('cervic', 'JJ'), ('ica', 'JJ'), ('50', 'CD'), ('%', 'NN'), ('stenosi', 'NN'), ('.', '.')]
[('fluoroscop', 'NN'), ('imag', 'NN'), ('axio', 'JJ'), ('stent', 'NN'), ('creat', 'NN'), ('cholecystoenterostomi', 'NN'), ('.', '.')]
[('46-year-old', 'JJ'), ('femal', 'JJ'), ('spindle-cel', 'JJ'), ('sarcoma', 'NN'), ('heart', 'NN'), ('.', '.')]
[('axial', 'JJ'), ('ct', 'NN'), ('angiographi', 'NN'), ('imag', 'NN'), ('show', 'NN'), ('larg', 'JJ'), ('mass', 'NN'), ('(', '('), ('asterisk', 'NN'), (')', ')'), ('region', 'NN'), ('left', 'VBD'), ('ventricl', 'NN'), ('.', '.')]
[('incid', 'JJ'), ('note', 'NN'), ('also', 'RB'), ('small', 'JJ'), ('right', 'RB'), ('pleural', 'JJ'), ('effus', 'RB'), ('right', 'JJ'), ('breast', 'NN'), ('implant', 'NN'), ('.', '.')]
[('magnet', 'NN'), ('reson', 'NN'), ('imag', 'NN'), ('cervic', 'JJ'), ('spine', 'NN'), ('showr', 'NN'), ('syrinx', 'VBD'), ('spinal', 'JJ'), ('cord', 'NN'), ('.', '.')]
[('anom', 'RB'), ('origin', 'NN'), ('circumflex', 'JJ'), ('arteri', 'RB'), ('right', 'JJ'), ('coronari', 'NN'), ('sinu', 'NN'), (',', ','), ('benign', 'JJ'), ('cour', 'NN'), ('.', '.')]
[('axial', 'JJ'), ('coronari', 'NN'), ('comput', 'NN'), ('tomographi', 'NN'), ('angiographi', 'IN'), ('mip', 'NN'), ('show', 'NN'), ('anom', 'VBZ'), ('origin', 'JJ'), ('circumflex', 'JJ'), ('arteri', 'NN'), ('(', '('), ('cx', 'NN'), (')', ')'), ('right', 'NN'), ('coronari', 'NN'), ('sinu', 'NN'), ('(', '('), ('scd', 'NN'), (')', ')'), (',', ','), ('retroaort', 'VB'), ('cour', 'NNS'), ('ascend', 'VBP'), ('aorta', 'NN'), ('(', '('), ('ao', 'JJ'), ('asc', 'NN'), (')', ')'), (',', ','), ('anterior', 'RB'), (',', ','), ('left', 'VBD'), ('atrium', 'NN'), ('(', '('), ('ae', 'NN'), (')', ')'), (',', ','), ('posterior', 'RB'), ('.', '.')]
[('right', 'RB'), ('coronari', 'NN'), ('arteri', 'NN'), ('(', '('), ('cd', 'NN'), (')', ')'), ('anterior', 'RB'), ('descend', 'VBP'), ('arteri', 'NN'), ('(', '('), ('da', 'NN'), (')', ')'), ('normal', 'JJ'), ('origin', 'NN'), ('right', 'NN'), ('left', 'VBD'), ('coronari', 'JJ'), ('sinus', 'NN'), (',', ','), ('respect', 'NN'), ('.', '.')]
[('curvilinear', 'JJ'), ('reform', 'NN'), ('reconstruct', 'NN'), ('patient', 'NN'), ('follow', 'JJ'), ('endovascular', 'JJ'), ('repair', 'NN'), ('abdomin', 'JJ'), ('aortic', 'JJ'), ('aneurysm', 'NN'), ('.', '.')]
[('aortic', 'JJ'), ('branch', 'NN'), (',', ','), ('stent', 'NN'), ('graft', 'NN'), ('aneurysm', 'NN'), ('sac', 'NN'), ('shown', 'VBN'), ('altogeth', 'JJ'), ('figur', 'NN'), ('.', '.')]
[('anteroposterior', 'JJ'), ('12-year', 'JJ'), ('old', 'JJ'), ('patient', 'NN'), ('show', 'NN'), ('radioluc', 'VBZ'), ('alter', 'RB'), ('apex', 'JJ'), ('left', 'VBD'), ('medial', 'JJ'), ('malleolu', 'NN'), ('.', '.')]
[('rest', 'NN'), ('ankl', 'NN'), ('joint', 'NN'), ('normal', 'JJ'), ('.', '.')]
[('comput', 'NN'), ('tomographi', 'NN'), ('thorax', 'NN'), ('demonstr', 'NN'), ('small', 'JJ'), ('(', '('), ('5', 'CD'), ('mm', 'RB'), ('diamet', 'NN'), (')', ')'), ('subpleur', 'NN'), ('nodul', 'NN'), ('within', 'IN'), ('anterior', 'JJ'), ('left', 'FW'), ('upper', 'JJ'), ('lobe', 'NN'), (',', ','), ('remain', 'VBP'), ('unchang', 'JJ'), ('sinc', 'NN'), ('previou', 'NN'), ('scan', 'JJ'), ('anteroposteriorradiograph', 'NN'), ('left', 'VBD'), ('hand', 'NN'), ('show', 'NN'), ('acroosteolysi', 'IN'), ('distal', 'JJ'), ('phalang', 'NN'), ('middl', 'NN'), ('phalang', 'NN'), ('.', '.')]
[('dental', 'JJ'), ('stone', 'NN'), ('model', 'NN'), ('left', 'VBD'), ('hand', 'NN'), ('amput', 'NN'), ('thumb', 'NN'), ('exten', 'VBP'), ('air', 'NN'), ('densiti', 'JJ'), ('space', 'NN'), ('suprahyoid', 'NN'), ('neck', 'NN'), ('region', 'NN'), ('.', '.')]
[('brain', 'NN'), ('comput', 'NN'), ('tomographi', 'JJ'), ('scan', 'JJ'), ('patient', 'NN'), ('present', 'NN'), ('.', '.')]
[('neonat', 'JJ'), ('chest', 'JJS'), ('x-ray', 'JJ'), ('show', 'NN'), ('cathet', 'NN'), ('esophagu', 'NN'), ('t6', 'NN'), ('vertebr', 'FW'), ('level', 'NN'), ('intrathorac', 'NN'), ('gastric', 'JJ'), ('bubbl', 'NN'), ('mediastinum', 'NN'), ('score', 'VBD'), ('0', 'CD'), ('select', 'JJ'), ('axial', 'JJ'), ('ct', 'NN'), ('imag', 'NN'), ('show', 'NN'), ('bilat', 'JJ'), ('effus', 'JJ'), ('reticular', 'JJ'), ('ground-glass', 'NN'), ('opac', 'NN'), ('bullou', 'NN'), ('format', 'NN'), ('.', '.')]
[('comput', 'NN'), ('tomographi', 'NN'), ('chest', 'NN'), ('whole', 'JJ'), ('lung', 'NN'), ('lavag', 'NN'), ('opg', 'NN'), ('pl', 'NN'), ('patient', 'NN'), ('show', 'NN'), ('dental', 'JJ'), ('abnorm', 'JJ'), ('characterist', 'NN'), ('‘', 'IN'), ('floating-', 'JJ'), ('in-', 'JJ'), ('air', 'NN'), ('appear', 'VBP'), ('’', 'JJ'), ('parastern', 'JJ'), ('five', 'CD'), ('chamber', 'NN'), ('view', 'NN'), ('section', 'NN'), ('reveal', 'NN'), ('correl', 'NN'), ('intermin', 'NN'), ('anterior', 'JJ'), ('tricuspid', 'JJ'), ('valv', 'NN'), ('attach', 'NN'), ('point', 'NN'), ('chorda', 'NN'), ('tendinea', 'NN'), ('right', 'RB'), ('ventricular', 'JJ'), ('septal', 'JJ'), ('defect', 'NN'), ('.', '.')]
[('la', 'NN'), (',', ','), ('left', 'VBD'), ('atrium', 'NN'), (';', ':'), ('ra', 'NN'), (',', ','), ('right', 'JJ'), ('atrium', 'NN'), (';', ':'), ('rv', 'NN'), (',', ','), ('right', 'JJ'), ('ventricl', 'NN'), (';', ':'), ('rvot', 'NN'), (',', ','), ('right', 'JJ'), ('ventricular', 'NN'), ('outflow', 'IN'), ('tract', 'NN'), ('.', '.')]
[('arrow', 'NN'), ('indic', 'JJ'), ('correl', 'NN'), ('.', '.')]
[('3-dimens', 'JJ'), ('reconstruct', 'NN'), ('ct', 'NN'), ('imag', 'NN'), ('show', 'NN'), ('maxillomandibular', 'JJ'), ('osteotomi', 'JJ'), ('simultan', 'NN'), ('genioplasti', 'NN'), ('fixat', 'VBD'), ('u-ha/plla', 'JJ'), ('composit', 'NN'), ('bioabsorb', 'NN'), ('devic', 'JJ'), ('femal', 'JJ'), ('patient', 'NN'), ('mandibular', 'JJ'), ('prognath', 'NN'), ('.', '.')]
[('maxillari', 'NNS'), ('osteosynthesi', 'VBP'), ('perform', 'VB'), ('four', 'CD'), ('l-type', 'JJ'), ('mini-', 'JJ'), ('plate', 'NN'), (',', ','), ('mandibular', 'JJ'), ('osteosynthesi', 'NN'), ('perform', 'NN'), ('use', 'NN'), ('bioabsorb', 'NN'), ('mesh', 'JJ'), ('monocort', 'NN'), ('screw', 'NN'), ('.', '.')]
[('sagitt', 'JJ'), ('reformat', 'NN'), ('imag', 'NN'), ('chest', 'NN'), ('ct', 'NN'), ('show', 'NN'), ('mediastin', 'JJ'), ('goiter', 'NN'), ('posterior', 'JJ'), ('trachea', 'NN'), ('endotrach', 'NN'), ('tube', 'NN'), ('.', '.')]
[('repar', 'NN'), ('regen', 'NN'), ('subtyp', 'VBD'), ('17-year-old', 'JJ'), ('patient', 'NN'), ('crohn', 'NN'), ("'s", 'POS'), ('disea', 'NN'), ('.', '.')]
[('axial', 'JJ'), ('contrast-enhanc', 'JJ'), ('fat-suppress', 'JJ'), ('t1-weight', 'JJ'), ('imag', 'NN'), ('show', 'NN'), ('non-enhanc', 'JJ'), ('ovoid', 'JJ'), ('nodular', 'JJ'), ('lesion', 'NN'), ('(', '('), ('arrow', 'NN'), (')', ')'), ('within', 'IN'), ('ascend', 'NN'), ('colon', 'NN'), (',', ','), ('indic', 'JJ'), ('regen', 'NN'), ('polyp', 'NN'), ('.', '.')]
[('panoram', 'NN'), ('view', 'NN'), ('show', 'VBP'), ('lesion', 'NN'), ('.', '.')]
[('sagitt', 'JJ'), ('view', 'NN'), ('urach', 'JJ'), ('cyst', 'NN'), ('bladder', 'NN'), ('.', '.')]
[('ct', 'NN'), ('coron', 'NN'), ('reconstruct', 'NN'), ('reveal', 'NN'), ('presenc', 'NN'), ('diffus', 'NN'), ('left', 'VBD'), ('cervic', 'JJ'), ('lymphadenopathi', 'NN'), ('.', '.')]

In [46]:
words=nltk.word_tokenize(captions)

In [47]:
nltk.download("maxent_ne_chunker")
nltk.download("words")

[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.

True

In [48]:
from nltk import ne_chunk

In [49]:
nltk.download('maxent_ne_chunker_tab')

[nltk_data] Downloading package maxent_ne_chunker_tab to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping chunkers/maxent_ne_chunker_tab.zip.

True

In [50]:
words

['coronal',
 'plain',
 'computed',
 'tomography',
 'image',
 'showing',
 'multiple',
 'large',
 'tumor',
 'masses',
 'with',
 'edge',
 'enhancement',
 'inside',
 'the',
 'abdominal',
 'cavity',
 'and',
 'liver',
 '.',
 'axial',
 'source',
 'image',
 'from',
 'an',
 'intracranial',
 'magnetic',
 'resonance',
 'angiogram',
 'reveals',
 'abnormal',
 'arterial',
 'signal',
 'elevation',
 'in',
 'the',
 'left',
 'more',
 'than',
 'right',
 'cavernous',
 'sinuses',
 'consistent',
 'with',
 'a',
 'carotid',
 'cavernous',
 'fistula',
 ',',
 'as',
 'indicated',
 'by',
 'the',
 'arrow',
 '.',
 'the',
 'apical',
 'height',
 ',',
 'homogeneity',
 ',',
 'and',
 'the',
 'thickness',
 'of',
 'mineral',
 'trioxide',
 'aggregate',
 'plug',
 'cto',
 'of',
 'rca',
 '(',
 'closure',
 'in',
 'the',
 '2nd',
 'segment',
 ')',
 'venography',
 'shows',
 'a',
 'large',
 'amount',
 'of',
 'thrombogenesis',
 'in',
 'the',
 'femoropoplitea',
 'vein',
 'before',
 'thrombolysis',
 '.',
 'postoperative',
 'decreased',
 'size',
 'of',
 'the',
 'cyst',
 'fetal',
 'aortic',
 'arch',
 '.',
 'the',
 'solid',
 'arrow',
 'represents',
 'the',
 'ascending',
 'aorta',
 'while',
 'the',
 'dotted',
 'arrow',
 'represents',
 'the',
 'aortic',
 'arch',
 'distal',
 'to',
 'the',
 'ductus',
 'arteriosus',
 '.',
 'note',
 'the',
 'aliasing',
 'in',
 'the',
 'ductal',
 'arch',
 'reflecting',
 'turbulent',
 'blood',
 'flow',
 'as',
 'a',
 'result',
 'of',
 'external',
 'compression',
 'due',
 'to',
 'mass-effect',
 '.',
 'abdominal',
 'computed',
 'tomography',
 'scan',
 '.',
 'arrow',
 'points',
 'to',
 'the',
 'likely',
 'cholecystocutaneous',
 'fistulous',
 'track',
 '.',
 'distension',
 'digestive',
 'avec',
 'niveaux',
 'hydro-aériques',
 'coliques',
 'et',
 'vacuité',
 'pelvienne',
 'panoramic',
 'x',
 'ray',
 'taken',
 'four',
 'years',
 'later',
 'showing',
 'a',
 'unilocular',
 'radiolucent',
 'area',
 'in',
 'the',
 'left',
 'ramus',
 '.',
 'anteroposterior',
 'radiograph',
 'of',
 'pelvis',
 'at',
 'most',
 'recent',
 'follow',
 'up',
 '.',
 'immediate',
 'postinjury',
 'magnetic',
 'resonance',
 'image',
 'demonstrating',
 'intact',
 'spinal',
 'cord',
 'canal',
 'with',
 'cerebrospinal',
 'fluid',
 'signal',
 'surrounding',
 'the',
 'spinal',
 'cord',
 'at',
 'all',
 'levels',
 '.',
 'arterial',
 'phase',
 'dynamic',
 'ct',
 'shows',
 'homogenous',
 'enhancement',
 'of',
 'the',
 'mass',
 '(',
 'arrow',
 ')',
 '.',
 'in',
 'the',
 'other',
 'level',
 ',',
 'normal',
 'right',
 'side',
 'adrenal',
 'gland',
 'was',
 'visualized',
 '.',
 'angiogram',
 'showing',
 'pseudoaneurysm',
 '(',
 'arrow',
 ')',
 'formation',
 'in',
 'proximal',
 'left',
 'superficial',
 'femoral',
 'artery',
 '.',
 'image',
 'from',
 'ct',
 'fluoroscopic',
 'guidance',
 'rhizotomy',
 'demonstrates',
 'the',
 'radiofrequency',
 'cannular',
 'tip',
 'in',
 'the',
 'junction',
 'of',
 'superior',
 'articular',
 'process',
 'and',
 'transverse',
 'process',
 '.',
 'bileteral',
 'styloid',
 'process',
 'elongation',
 'in',
 'a',
 'subject',
 'on',
 'a',
 'panoramic',
 'radiography',
 '.',
 'solid-cystic',
 'lesion',
 'with',
 'thickened',
 'hyperechoic',
 'wall',
 '.',
 'in',
 'the',
 'region',
 'of',
 'the',
 'polycyclic',
 'solid',
 'structure',
 'and',
 'in',
 'the',
 'wall',
 'of',
 'the',
 'lesion',
 ',',
 'color',
 'doppler',
 '(',
 'cdus',
 ')',
 'shows',
 'tortuous',
 'arterial',
 'vessels',
 'initial',
 'chest',
 'x-ray',
 'showing',
 'a',
 'left',
 'tension',
 'pneumothorax',
 'with',
 'shift',
 'of',
 'the',
 'mediastinum',
 'to',
 'the',
 'right',
 ',',
 'pleural',
 'effusion',
 'left',
 ',',
 'basal',
 'dorsolateral',
 'rib',
 'fractures',
 '.',
 'there',
 "'s",
 'also',
 'air',
 'visible',
 'under',
 'the',
 'right',
 'diaphragm',
 '(',
 'arrow',
 ')',
 '.',
 'a',
 'large',
 'subcutaneous',
 'tributary',
 'pierces',
 'the',
 'superficial',
 'fascia',
 'to',
 'join',
 'the',
 'lsv',
 'in',
 'the',
 'thigh',
 'region',
 '.',
 'brain',
 'magnetic',
 'resonance',
 'imaging',
 '(',
 'mri',
 ')',
 'after',
 'gadolinium',
 'injection',
 'showed',
 'an',
 'image',
 'in',
 'the',
 'axial',
 '(',
 'flair',
 'sequence',
 ')',
 'showing',
 'hyper-intensity',
 'lesions',
 'in',
 'the',
 'white',
 'matter',
 'of',
 'the',
 'frontal',
 'lobes',
 '.',
 'there',
 'is',
 'no',
 'signal',
 'abnormality',
 'of',
 'the',
 'cortex',
 '.',
 'note',
 'that',
 'there',
 'is',
 'no',
 'mass',
 'effect',
 'on',
 'the',
 'ventricular',
 'cavities',
 'or',
 'midline',
 'structures',
 '.',
 'dosimetric',
 'results',
 'obtained',
 'with',
 'rapidarc',
 '.',
 'barium',
 'small',
 'bowel',
 'meal',
 'and',
 'follow',
 'through',
 'showing',
 'normal',
 'small',
 'and',
 'large',
 'bowel',
 '.',
 'ct',
 'axial',
 'section',
 'shows',
 'multilocular',
 'expansile',
 'lytic',
 'lesion',
 'in',
 'body',
 'of',
 'mandible',
 'right',
 'side',
 'with',
 'significant',
 'enhancing',
 'soft',
 'tissue',
 'matrix',
 'computed',
 'tomography',
 'obtained',
 '3',
 'weeks',
 'before',
 'admission',
 'with',
 'diagnosis',
 'of',
 'aspiration',
 'pneumonia',
 'showed',
 'no',
 'hepatic',
 'portal',
 'venous',
 'gas',
 'and',
 'no',
 'gas',
 'within',
 'the',
 'wall',
 'of',
 'stomach',
 'in',
 'the',
 'visualized',
 'portions',
 'of',
 'the',
 'upper',
 'abdomen',
 'postoperative',
 'day',
 '1',
 'chest',
 'radiograph',
 'reveals',
 'large',
 'left',
 'pneumothorax',
 '.',
 'left',
 'upper',
 'lobe',
 'squamous',
 'cell',
 'cancer',
 'showing',
 'a',
 'broad',
 ',',
 'convex',
 'margin',
 'with',
 'the',
 'mediastinum',
 'at',
 'ct',
 '(',
 'arrow',
 ')',
 ';',
 'there',
 'was',
 'no',
 'mediastinal',
 'or',
 'pleural',
 'invasion',
 'at',
 'surgery',
 'or',
 'pathology',
 '(',
 't2',
 'tumor',
 ')',
 '.',
 'ct',
 'scan',
 'of',
 'the',
 'thorax',
 'demonstrating',
 'necrotic',
 'paratracheal',
 'node',
 '.',
 'enhanced',
 'axial',
 'ct',
 'scan',
 'of',
 'the',
 'thorax',
 ',',
 'mediastinal',
 'window',
 ',',
 'in',
 'a',
 '58-year-old',
 'female',
 'who',
 'presented',
 'with',
 'bilateral',
 'vocal',
 'cord',
 'immobility',
 'of',
 'unknown',
 'etiology',
 '.',
 'the',
 'positive',
 'serum',
 'anti-hu',
 'antibody',
 ',',
 'which',
 'is',
 'highly',
 'associated',
 'with',
 'small',
 'cell',
 'lung',
 'carcinoma',
 ',',
 'led',
 'to',
 'this',
 'repeat',
 'ct',
 'scan',
 '.',
 'the',
 'arrow',
 'demonstrates',
 'an',
 'enlarged',
 'level',
 '4r',
 'paratracheal',
 'lymph',
 'node',
 'with',
 'central',
 'necrosis',
 '.',
 'see',
 'figure',
 '2',
 'for',
 'the',
 'pathologic',
 'description',
 'of',
 'a',
 'biopsy',
 'from',
 'this',
 'node',
 '.',
 'cortical',
 'bone',
 'changes',
 'in',
 'rheumatoid',
 'arthritis',
 'on',
 'classical',
 'radiography',
 'showing',
 'striation',
 'and',
 'lamellation',
 'of',
 'cortical',
 'bone',
 'of',
 'the',
 'phalanx',
 '.',
 'twelve-year-old',
 'boy',
 'presented',
 'with',
 'nasopharyngeal',
 'angiofi',
 'broma',
 'diagnosed',
 'with',
 'unilateral',
 'meningo-ophthalmic',
 'artery',
 'anomaly',
 '.',
 'computed',
 'tomography',
 'scan',
 'shows',
 'midline',
 'nasopharyngeal',
 'angiofi',
 'broma',
 '(',
 'black',
 'arrow',
 ')',
 ',',
 'with',
 'prominent',
 'right-side',
 'infiltration',
 'into',
 'the',
 'infratemporal',
 'fossa',
 '(',
 'white',
 'arrow',
 ')',
 '.',
 'pelvis',
 'arthrogram',
 'showed',
 'defective',
 'ossification',
 'of',
 'the',
 'lateral',
 'acetabular',
 'corner',
 ',',
 'leaving',
 'a',
 'significant',
 'cartilaginous',
 'anlage',
 'left',
 'anterior',
 'oblique',
 'of',
 'the',
 'common',
 'coronary',
 'artery',
 'and',
 'its',
 'branches',
 'with',
 'critical',
 'disease',
 'the',
 'proximal',
 'rca',
 ',',
 'and',
 'mid/distal',
 'anomalous',
 'lcx',
 '.',
 'calculation',
 'of',
 'inferior',
 'vena',
 'cava',
 'collapsibility',
 'index',
 '(',
 '[',
 'a–b',
 ']',
 '/b',
 ')',
 '(',
 '%',
 ')',
 'using',
 'ultrasonography',
 'ct',
 'guided',
 'core',
 'biopsy',
 'of',
 'infracolic',
 'omental',
 'cake',
 '.',
 'initial',
 'radiograph',
 'shows',
 'a',
 'right',
 'femoral',
 'neck',
 'fracture',
 'with',
 'sclerotic',
 'superior',
 'cortex',
 'and',
 'an',
 'undisplaced',
 'linear',
 'pattern',
 '.',
 't2-weighted',
 'mr',
 'sagittal',
 'image',
 'shows',
 'an',
 'isointense',
 'schwannoma',
 'with',
 'cauda',
 'equina',
 'compression',
 'at',
 'the',
 's3',
 'level',
 '.',
 'magnetic',
 'resonance',
 'angiography',
 'at',
 'presentation',
 'showing',
 'the',
 'giant',
 'intracranial',
 'aneurysm',
 'and',
 'onset',
 'ectasia',
 'of',
 'the',
 'left',
 'carotid',
 'siphon',
 '.',
 'mri',
 'of',
 'the',
 'right',
 'elbow',
 '(',
 't2',
 'image',
 ')',
 'demonstrates',
 'fusion',
 'of',
 'the',
 'proximal',
 'one-third',
 'of',
 'the',
 'ulna',
 'and',
 'radius',
 '.',
 'note',
 'the',
 'anterior',
 'dislocation',
 'of',
 'the',
 'radial',
 'head',
 ',',
 'joint',
 'fluid',
 'effusion',
 ',',
 'tension',
 'of',
 'anterior',
 'capsule',
 ',',
 'and',
 'edema',
 'signal',
 'in',
 'the',
 'anterior',
 'soft',
 'tissue',
 '.',
 'anteroposterior',
 'chest',
 'radiograph',
 'showing',
 'cardiomegaly',
 'as',
 'well',
 'as',
 'an',
 'irregular',
 'contour',
 'to',
 'the',
 'lateral',
 'margin',
 'of',
 'the',
 'descending',
 'thoracic',
 'aorta',
 '(',
 'arrows',
 ')',
 '.',
 'the',
 'chest',
 'x-ray',
 'showed',
 'mild',
 'increase',
 'of',
 'transverse',
 'cardiac',
 'diameter',
 '.',
 'the',
 'left',
 'cardiac',
 'border',
 'protruded',
 'left',
 'mildly',
 '.',
 'computerized',
 'tomography',
 'reveals',
 'dilated',
 'intrahepatic',
 'biliary',
 'ducts',
 '.',
 'pneumocystis',
 'pneumonia',
 'in',
 'an',
 'aids',
 'patient',
 '.',
 'hrct',
 'at',
 'the',
 'level',
 'of',
 'the',
 'upper',
 'lobes',
 'reveals',
 'a',
 'mixed',
 '“',
 'ground-glass',
 'and',
 'cystic',
 'pattern',
 '”',
 'characterised',
 'by',
 'the',
 'presence',
 'of',
 'diffuse',
 'areas',
 'of',
 'ground-glass',
 'opacity',
 'and',
 'a',
 'few',
 'thin-walled',
 'multilocular',
 'cysts',
 'failed',
 'consolidation',
 'after',
 'treatment',
 'with',
 'nailing',
 'alone',
 '.',
 'elastic',
 'stable',
 'intramedullary',
 'nailing',
 'in',
 'combination',
 'with',
 'orthoss®',
 'and',
 'gps®',
 'after',
 'earlier',
 'failed',
 'treatment',
 '.',
 'radiograph',
 'three',
 'months',
 'following',
 'the',
 'initial',
 'gps®/orthoss®',
 'treatment',
 'resulting',
 'in',
 'bone',
 'mineralization',
 '.',
 'ct',
 ...]

In [52]:
from nltk import pos_tag
tags=pos_tag(words)

In [53]:
import nltk
from nltk import word_tokenize, pos_tag, ne_chunk
nltk.download('punkt')
nltk.download('maxent_ne_chunker')
nltk.download('words')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!

True

In [54]:
tokens = word_tokenize(captions)
tags = pos_tag(tokens)
ner_tree = ne_chunk(tags)
print(ner_tree)

(S
  coronal/JJ
  plain/NN
  computed/VBD
  tomography/JJ
  image/NN
  showing/VBG
  multiple/JJ
  large/JJ
  tumor/NN
  masses/NNS
  with/IN
  edge/NN
  enhancement/NN
  inside/IN
  the/DT
  abdominal/JJ
  cavity/NN
  and/CC
  liver/NN
  ./.
  axial/JJ
  source/NN
  image/NN
  from/IN
  an/DT
  intracranial/JJ
  magnetic/JJ
  resonance/NN
  angiogram/NN
  reveals/NNS
  abnormal/JJ
  arterial/JJ
  signal/NN
  elevation/NN
  in/IN
  the/DT
  left/NN
  more/JJR
  than/IN
  right/RB
  cavernous/JJ
  sinuses/NNS
  consistent/JJ
  with/IN
  a/DT
  carotid/NN
  cavernous/JJ
  fistula/NN
  ,/,
  as/IN
  indicated/VBN
  by/IN
  the/DT
  arrow/NN
  ./.
  the/DT
  apical/JJ
  height/NN
  ,/,
  homogeneity/NN
  ,/,
  and/CC
  the/DT
  thickness/NN
  of/IN
  mineral/JJ
  trioxide/NN
  aggregate/NN
  plug/NN
  cto/NN
  of/IN
  rca/NN
  (/(
  closure/NN
  in/IN
  the/DT
  2nd/CD
  segment/NN
  )/)
  venography/NN
  shows/VBZ
  a/DT
  large/JJ
  amount/NN
  of/IN
  thrombogenesis/NN
  in/IN
  the/DT
  femoropoplitea/NN
  vein/NN
  before/IN
  thrombolysis/NN
  ./.
  postoperative/JJ
  decreased/JJ
  size/NN
  of/IN
  the/DT
  cyst/NN
  fetal/JJ
  aortic/JJ
  arch/NN
  ./.
  the/DT
  solid/JJ
  arrow/NN
  represents/VBZ
  the/DT
  ascending/VBG
  aorta/NN
  while/IN
  the/DT
  dotted/JJ
  arrow/NN
  represents/VBZ
  the/DT
  aortic/JJ
  arch/NN
  distal/NN
  to/TO
  the/DT
  ductus/NN
  arteriosus/NN
  ./.
  note/VB
  the/DT
  aliasing/NN
  in/IN
  the/DT
  ductal/JJ
  arch/NN
  reflecting/VBG
  turbulent/JJ
  blood/NN
  flow/NN
  as/IN
  a/DT
  result/NN
  of/IN
  external/JJ
  compression/NN
  due/JJ
  to/TO
  mass-effect/JJ
  ./.
  abdominal/JJ
  computed/VBD
  tomography/JJ
  scan/JJ
  ./.
  arrow/NN
  points/NNS
  to/TO
  the/DT
  likely/JJ
  cholecystocutaneous/JJ
  fistulous/JJ
  track/NN
  ./.
  distension/NN
  digestive/JJ
  avec/NN
  niveaux/JJ
  hydro-aériques/NNS
  coliques/NNS
  et/VBP
  vacuité/JJ
  pelvienne/NN
  panoramic/JJ
  x/NN
  ray/NN
  taken/VBN
  four/CD
  years/NNS
  later/RB
  showing/VBG
  a/DT
  unilocular/JJ
  radiolucent/NN
  area/NN
  in/IN
  the/DT
  left/NN
  ramus/NN
  ./.
  anteroposterior/JJ
  radiograph/NN
  of/IN
  pelvis/NN
  at/IN
  most/RBS
  recent/JJ
  follow/VB
  up/RP
  ./.
  immediate/JJ
  postinjury/NN
  magnetic/JJ
  resonance/NN
  image/NN
  demonstrating/VBG
  intact/JJ
  spinal/JJ
  cord/NN
  canal/NN
  with/IN
  cerebrospinal/JJ
  fluid/JJ
  signal/NN
  surrounding/VBG
  the/DT
  spinal/JJ
  cord/NN
  at/IN
  all/DT
  levels/NNS
  ./.
  arterial/JJ
  phase/NN
  dynamic/JJ
  ct/NN
  shows/VBZ
  homogenous/JJ
  enhancement/NN
  of/IN
  the/DT
  mass/NN
  (/(
  arrow/NN
  )/)
  ./.
  in/IN
  the/DT
  other/JJ
  level/NN
  ,/,
  normal/JJ
  right/JJ
  side/NN
  adrenal/JJ
  gland/NN
  was/VBD
  visualized/VBN
  ./.
  angiogram/JJ
  showing/NN
  pseudoaneurysm/NN
  (/(
  arrow/NN
  )/)
  formation/NN
  in/IN
  proximal/JJ
  left/JJ
  superficial/JJ
  femoral/JJ
  artery/NN
  ./.
  image/NN
  from/IN
  ct/JJ
  fluoroscopic/NN
  guidance/NN
  rhizotomy/NN
  demonstrates/VBZ
  the/DT
  radiofrequency/NN
  cannular/JJ
  tip/NN
  in/IN
  the/DT
  junction/NN
  of/IN
  superior/JJ
  articular/JJ
  process/NN
  and/CC
  transverse/NN
  process/NN
  ./.
  bileteral/JJ
  styloid/JJ
  process/NN
  elongation/NN
  in/IN
  a/DT
  subject/NN
  on/IN
  a/DT
  panoramic/JJ
  radiography/NN
  ./.
  solid-cystic/JJ
  lesion/NN
  with/IN
  thickened/JJ
  hyperechoic/NN
  wall/NN
  ./.
  in/IN
  the/DT
  region/NN
  of/IN
  the/DT
  polycyclic/JJ
  solid/JJ
  structure/NN
  and/CC
  in/IN
  the/DT
  wall/NN
  of/IN
  the/DT
  lesion/NN
  ,/,
  color/NN
  doppler/NN
  (/(
  cdus/NN
  )/)
  shows/VBZ
  tortuous/JJ
  arterial/JJ
  vessels/NNS
  initial/JJ
  chest/JJS
  x-ray/JJ
  showing/VBG
  a/DT
  left/JJ
  tension/NN
  pneumothorax/NN
  with/IN
  shift/NN
  of/IN
  the/DT
  mediastinum/NN
  to/TO
  the/DT
  right/NN
  ,/,
  pleural/JJ
  effusion/NN
  left/VBD
  ,/,
  basal/JJ
  dorsolateral/JJ
  rib/NN
  fractures/NNS
  ./.
  there/EX
  's/VBZ
  also/RB
  air/NN
  visible/JJ
  under/IN
  the/DT
  right/JJ
  diaphragm/NN
  (/(
  arrow/NN
  )/)
  ./.
  a/DT
  large/JJ
  subcutaneous/JJ
  tributary/JJ
  pierces/NNS
  the/DT
  superficial/JJ
  fascia/NN
  to/TO
  join/VB
  the/DT
  lsv/NN
  in/IN
  the/DT
  thigh/JJ
  region/NN
  ./.
  brain/NN
  magnetic/JJ
  resonance/NN
  imaging/NN
  (/(
  mri/NN
  )/)
  after/IN
  gadolinium/NN
  injection/NN
  showed/VBD
  an/DT
  image/NN
  in/IN
  the/DT
  axial/JJ
  (/(
  flair/JJ
  sequence/NN
  )/)
  showing/VBG
  hyper-intensity/JJ
  lesions/NNS
  in/IN
  the/DT
  white/JJ
  matter/NN
  of/IN
  the/DT
  frontal/JJ
  lobes/NN
  ./.
  there/EX
  is/VBZ
  no/DT
  signal/JJ
  abnormality/NN
  of/IN
  the/DT
  cortex/NN
  ./.
  note/NN
  that/IN
  there/EX
  is/VBZ
  no/DT
  mass/NN
  effect/NN
  on/IN
  the/DT
  ventricular/JJ
  cavities/NNS
  or/CC
  midline/JJ
  structures/NNS
  ./.
  dosimetric/JJ
  results/NNS
  obtained/VBD
  with/IN
  rapidarc/NN
  ./.
  barium/NN
  small/JJ
  bowel/NN
  meal/NN
  and/CC
  follow/VB
  through/IN
  showing/VBG
  normal/JJ
  small/JJ
  and/CC
  large/JJ
  bowel/NN
  ./.
  ct/JJ
  axial/JJ
  section/NN
  shows/NNS
  multilocular/VBP
  expansile/JJ
  lytic/JJ
  lesion/NN
  in/IN
  body/NN
  of/IN
  mandible/JJ
  right/JJ
  side/NN
  with/IN
  significant/JJ
  enhancing/VBG
  soft/JJ
  tissue/NN
  matrix/NN
  computed/VBD
  tomography/NN
  obtained/VBD
  3/CD
  weeks/NNS
  before/IN
  admission/NN
  with/IN
  diagnosis/NN
  of/IN
  aspiration/NN
  pneumonia/NN
  showed/VBD
  no/DT
  hepatic/JJ
  portal/NN
  venous/JJ
  gas/NN
  and/CC
  no/DT
  gas/NN
  within/IN
  the/DT
  wall/NN
  of/IN
  stomach/NN
  in/IN
  the/DT
  visualized/JJ
  portions/NNS
  of/IN
  the/DT
  upper/JJ
  abdomen/NNS
  postoperative/JJ
  day/NN
  1/CD
  chest/NN
  radiograph/NN
  reveals/NNS
  large/JJ
  left/VBD
  pneumothorax/NN
  ./.
  left/VBN
  upper/JJ
  lobe/NN
  squamous/JJ
  cell/NN
  cancer/NN
  showing/VBG
  a/DT
  broad/JJ
  ,/,
  convex/JJ
  margin/NN
  with/IN
  the/DT
  mediastinum/NN
  at/IN
  ct/NN
  (/(
  arrow/NN
  )/)
  ;/:
  there/EX
  was/VBD
  no/DT
  mediastinal/JJ
  or/CC
  pleural/JJ
  invasion/NN
  at/IN
  surgery/NN
  or/CC
  pathology/NN
  (/(
  t2/JJ
  tumor/NN
  )/)
  ./.
  ct/JJ
  scan/NN
  of/IN
  the/DT
  thorax/NN
  demonstrating/VBG
  necrotic/JJ
  paratracheal/NN
  node/NN
  ./.
  enhanced/VBN
  axial/JJ
  ct/NN
  scan/NN
  of/IN
  the/DT
  thorax/NN
  ,/,
  mediastinal/JJ
  window/NN
  ,/,
  in/IN
  a/DT
  58-year-old/JJ
  female/NN
  who/WP
  presented/VBD
  with/IN
  bilateral/JJ
  vocal/JJ
  cord/NN
  immobility/NN
  of/IN
  unknown/JJ
  etiology/NN
  ./.
  the/DT
  positive/JJ
  serum/NN
  anti-hu/JJ
  antibody/NN
  ,/,
  which/WDT
  is/VBZ
  highly/RB
  associated/VBN
  with/IN
  small/JJ
  cell/NN
  lung/NN
  carcinoma/NN
  ,/,
  led/VBN
  to/TO
  this/DT
  repeat/NN
  ct/JJ
  scan/JJ
  ./.
  the/DT
  arrow/NN
  demonstrates/VBZ
  an/DT
  enlarged/JJ
  level/NN
  4r/CD
  paratracheal/NN
  lymph/NN
  node/NN
  with/IN
  central/JJ
  necrosis/NN
  ./.
  see/VB
  figure/JJ
  2/CD
  for/IN
  the/DT
  pathologic/JJ
  description/NN
  of/IN
  a/DT
  biopsy/NN
  from/IN
  this/DT
  node/NN
  ./.
  cortical/JJ
  bone/NN
  changes/NNS
  in/IN
  rheumatoid/NN
  arthritis/NN
  on/IN
  classical/JJ
  radiography/NN
  showing/VBG
  striation/NN
  and/CC
  lamellation/NN
  of/IN
  cortical/JJ
  bone/NN
  of/IN
  the/DT
  phalanx/NN
  ./.
  twelve-year-old/JJ
  boy/NN
  presented/VBN
  with/IN
  nasopharyngeal/JJ
  angiofi/JJ
  broma/NN
  diagnosed/VBN
  with/IN
  unilateral/JJ
  meningo-ophthalmic/JJ
  artery/NN
  anomaly/NN
  ./.
  computed/VBN
  tomography/NN
  scan/NN
  shows/VBZ
  midline/JJ
  nasopharyngeal/JJ
  angiofi/NN
  broma/NN
  (/(
  black/JJ
  arrow/NN
  )/)
  ,/,
  with/IN
  prominent/JJ
  right-side/JJ
  infiltration/NN
  into/IN
  the/DT
  infratemporal/JJ
  fossa/NN
  (/(
  white/JJ
  arrow/NN
  )/)
  ./.
  pelvis/NN
  arthrogram/NN
  showed/VBD
  defective/JJ
  ossification/NN
  of/IN
  the/DT
  lateral/JJ
  acetabular/JJ
  corner/NN
  ,/,
  leaving/VBG
  a/DT
  significant/JJ
  cartilaginous/JJ
  anlage/NN
  left/VBD
  anterior/JJ
  oblique/NN
  of/IN
  the/DT
  common/JJ
  coronary/JJ
  artery/NN
  and/CC
  its/PRP$
  branches/NNS
  with/IN
  critical/JJ
  disease/NN
  the/DT
  proximal/JJ
  rca/NN
  ,/,
  and/CC
  mid/distal/JJ
  anomalous/JJ
  lcx/NN
  ./.
  calculation/NN
  of/IN
  inferior/JJ
  vena/FW
  cava/NN
  collapsibility/NN
  index/NN
  (/(
  [/JJ
  a–b/NN
  ]/NNP
  /b/NNP
  )/)
  (/(
  %/NN
  )/)
  using/VBG
  ultrasonography/JJ
  ct/NN
  guided/VBD
  core/NN
  biopsy/NN
  of/IN
  infracolic/JJ
  omental/JJ
  cake/NN
  ./.
  initial/JJ
  radiograph/NN
  shows/VBZ
  a/DT
  right/JJ
  femoral/JJ
  neck/NN
  fracture/NN
  with/IN
  sclerotic/JJ
  superior/JJ
  cortex/NN
  and/CC
  an/DT
  undisplaced/JJ
  linear/JJ
  pattern/NN
  ./.
  t2-weighted/JJ
  mr/NN
  sagittal/JJ
  image/NN
  shows/VBZ
  an/DT
  isointense/JJ
  schwannoma/NN
  with/IN
  cauda/JJ
  equina/JJ
  compression/NN
  at/IN
  the/DT
  s3/JJ
  level/NN
  ./.
  magnetic/JJ
  resonance/NN
  angiography/NN
  at/IN
  presentation/NN
  showing/VBG
  the/DT
  giant/JJ
  intracranial/JJ
  aneurysm/NN
  and/CC
  onset/JJ
  ectasia/NN
  of/IN
  the/DT
  left/NN
  carotid/NN
  siphon/NN
  ./.
  mri/NN
  of/IN
  the/DT
  right/JJ
  elbow/NN
  (/(
  t2/JJ
  image/NN
  )/)
  demonstrates/VBZ
  fusion/NN
  of/IN
  the/DT
  proximal/JJ
  one-third/NN
  of/IN
  the/DT
  ulna/NN
  and/CC
  radius/NN
  ./.
  note/VB
  the/DT
  anterior/JJ
  dislocation/NN
  of/IN
  the/DT
  radial/JJ
  head/NN
  ,/,
  joint/JJ
  fluid/NN
  effusion/NN
  ,/,
  tension/NN
  of/IN
  anterior/JJ
  capsule/NN
  ,/,
  and/CC
  edema/JJ
  signal/NN
  in/IN
  the/DT
  anterior/JJ
  soft/JJ
  tissue/NN
  ./.
  anteroposterior/JJ
  chest/NN
  radiograph/NN
  showing/VBG
  cardiomegaly/NN
  as/RB
  well/RB
  as/IN
  an/DT
  irregular/JJ
  contour/NN
  to/TO
  the/DT
  lateral/JJ
  margin/NN
  of/IN
  the/DT
  descending/VBG
  thoracic/NN
  aorta/NN
  (/(
  arrows/NNS
  )/)
  ./.
  the/DT
  chest/JJS
  x-ray/JJ
  showed/VBD
  mild/JJ
  increase/NN
  of/IN
  transverse/JJ
  cardiac/JJ
  diameter/NN
  ./.
  the/DT
  left/JJ
  cardiac/JJ
  border/NN
  protruded/VBD
  left/VBD
  mildly/RB
  ./.
  computerized/JJ
  tomography/NN
  reveals/NNS
  dilated/VBD
  intrahepatic/JJ
  biliary/JJ
  ducts/NNS
  ./.
  pneumocystis/NN
  pneumonia/NN
  in/IN
  an/DT
  aids/JJ
  patient/NN
  ./.
  hrct/NN
  at/IN
  the/DT
  level/NN
  of/IN
  the/DT
  upper/JJ
  lobes/NN
  reveals/VBZ
  a/DT
  mixed/JJ
  “/JJ
  ground-glass/NN
  and/CC
  cystic/JJ
  pattern/NN
  ”/NNS
  characterised/VBN
  by/IN
  the/DT
  presence/NN
  of/IN
  diffuse/NN
  areas/NNS
  of/IN
  ground-glass/NN
  opacity/NN
  and/CC
  a/DT
  few/JJ
  thin-walled/JJ
  multilocular/JJ
  cysts/NNS
  failed/VBD
  consolidation/NN
  after/IN
  treatment/NN
  with/IN
  nailing/VBG
  alone/RB
  ./.
  elastic/JJ
  stable/JJ
  intramedullary/JJ
  nailing/NN
  in/IN
  combination/NN
  with/IN
  orthoss®/NN
  and/CC
  gps®/NN
  after/IN
  earlier/JJR
  failed/VBD
  treatment/NN
  ./.
  radiograph/VB
  three/CD
  months/NNS
  following/VBG
  the/DT
  initial/JJ
  gps®/orthoss®/NN
  treatment/NN
  resulting/VBG
  in/IN
  bone/NN
  mineralization/NN
  ./.
  ct/JJ
  scan/JJ
  showing/VBG
  a/DT
  large/JJ
  left/NN
  ovarian/JJ
  cyst/NN
  an/DT
  hc/NN
  with/IN
  a/DT
  diameter/NN
  of/IN
  0.37/CD
  cm/NN
  in/IN
  the/DT
  left/NN
  hippocampus/NN
  is/VBZ
  noted/VBN
  in/IN
  the/DT
  t1-weighted/JJ
  image/NN
  at/IN
  the/DT
  level/NN
  of/IN
  the/DT
  hippocampus/NN
  fragmented/VBD
  humeral/JJ
  head/NN
  stepping/VBG
  over/IN
  thoracic/JJ
  aorta/NN
  (/(
  black/JJ
  arrow/NN
  )/)
  ultrasound/IN
  image/NN
  of/IN
  bovine/NN
  liver/NN
  depicts/VBZ
  the/DT
  tips/NNS
  (/(
  arrows/NNS
  )/)
  of/IN
  two/CD
  cannulae/NN
  inserted/VBD
  using/VBG
  introducer/NN
  sets/NNS
  prior/RB
  to/TO
  rf/VB
  ablation/NN
  ./.
  on/IN
  two/CD
  hyperechoic/JJ
  tips/NNS
  ,/,
  posterior/JJ
  acoustic/JJ
  shadowing/NN
  is/VBZ
  visible/JJ
  ./.
  the/DT
  aortic/JJ
  root/NN
  demonstrating/VBG
  the/DT
  linear/JJ
  measurements/NNS
  of/IN
  the/DT
  patient/NN
  that/WDT
  suffered/VBD
  a/DT
  dissection/NN
  ./.
  (/(
  case/NN
  #/#
  2/CD
  )/)
  computed/VBD
  tomography/NN
  of/IN
  the/DT
  abdomen/NNS
  showing/VBG
  right/JJ
  upper/JJ
  quadrant/JJ
  abdominal/JJ
  pseudocyst/NN
  (/(
  arrow/NN
  )/)
  near/IN
  the/DT
  gastric/JJ
  outlet/NN
  renal/JJ
  manifestations/NNS
  on/IN
  ct/JJ
  abdomen/NNS
  ./.
  bilateral/JJ
  nephromegaly/NN
  (/(
  greater/JJR
  than/IN
  2/CD
  standard/JJ
  deviation/NN
  for/IN
  age/NN
  )/)
  ,/,
  and/CC
  nephrocalcinosis/NN
  (/(
  in/IN
  red/JJ
  box/NN
  )/)
  ./.
  abdominal/JJ
  ct/NN
  finding/VBG
  reveals/NNS
  a/DT
  remained/JJ
  round/JJ
  foreign/JJ
  body/NN
  in/IN
  appendix/NN
  ,/,
  dilated/VBD
  appendix/NN
  ./.
  mri/JJ
  findings/NNS
  ./.
  the/DT
  cystic/JJ
  duct/NN
  was/VBD
  not/RB
  seen/VBN
  ./.
  six/CD
  weeks/NNS
  after/IN
  partial/JJ
  medial/JJ
  meniscectomy/NN
  ,/,
  coronal/JJ
  fat-saturated/JJ
  t2-weighted/JJ
  image/NN
  shows/VBZ
  a/DT
  subchondral/JJ
  fracture/NN
  of/IN
  the/DT
  medial/JJ
  femoral/JJ
  condyle/NN
  (/(
  large/JJ
  arrow/NN
  )/)
  with/IN
  marked/VBN
  surrounding/VBG
  marrow/NN
  edema/NN
  pattern/NN
  as/RB
  well/RB
  as/IN
  a/DT
  smaller/JJR
  subchondral/JJ
  fracture/NN
  of/IN
  the/DT
  central/JJ
  aspect/NN
  of/IN
  the/DT
  lateral/JJ
  femoral/JJ
  condyle/NN
  (/(
  small/JJ
  arrow/NN
  )/)
  with/IN
  less/RBR
  extensive/JJ
  adjacent/JJ
  marrow/NN
  edema/NN
  pattern/NN
  ./.
  this/DT
  case/NN
  is/VBZ
  unusual/JJ
  given/VBN
  subchondral/JJ
  fractures/NNS
  in/IN
  both/DT
  compartments/NNS
  ;/:
  usually/RB
  ,/,
  the/DT
  fracture/NN
  occurs/VBZ
  in/IN
  the/DT
  compartment/NN
  where/WRB
  there/EX
  has/VBZ
  been/VBN
  prior/RB
  partial/JJ
  meniscectomy/NN
  or/CC
  where/WRB
  there/EX
  is/VBZ
  a/DT
  radial/JJ
  split/NN
  or/CC
  complex/JJ
  tear/NN
  of/IN
  the/DT
  posterior/JJ
  horn/JJ
  root/NN
  ./.
  ct/JJ
  scan/JJ
  with/IN
  images/NNS
  of/IN
  opacification/NN
  of/IN
  the/DT
  bladder/NN
  demonstrating/VBG
  extra-peritoneal/JJ
  extravasations/NNS
  of/IN
  the/DT
  infused/JJ
  contrast/NN
  from/IN
  the/DT
  posterior/JJ
  aspect/NN
  of/IN
  the/DT
  bladder/NN
  radiographic/JJ
  appearance/NN
  after/IN
  6/CD
  months/NNS
  showed/VBD
  the/DT
  lesion/NN
  disappeared/VBD
  ./.
  abdominal/JJ
  mri/NN
  demonstrates/VBZ
  the/DT
  cyst/NN
  (/(
  asterisk/NN
  )/)
  intimately/RB
  related/VBN
  to/TO
  the/DT
  left/JJ
  lobe/NN
  of/IN
  liver/NN
  (/(
  l/NN
  )/)
  ,/,
  spleen/JJ
  (/(
  s/NN
  )/)
  and/CC
  gastric/JJ
  body/NN
  (/(
  g/NN
  )/)
  ,/,
  still/RB
  without/IN
  a/DT
  clearly/RB
  demonstrable/JJ
  plane/NN
  between/IN
  the/DT
  structures/NNS
  ./.
  transoesophageal/JJ
  echocardiogram/JJ
  demonstrating/VBG
  a/DT
  mass/NN
  (/(
  fibroelastoma/NN
  )/)
  of/IN
  the/DT
  left/NN
  ventricular/JJ
  outflow/JJ
  tract/NN
  immediate/NN
  after/IN
  surgery/NN
  :/:
  enucleation/NN
  of/IN
  cyst/NN
  &/CC
  fixation/NN
  of/IN
  bended/JJ
  8-hole/JJ
  plate/NN
  and/CC
  five/CD
  screws/NNS
  ;/:
  extraction/NN
  of/IN
  #/#
  26./CD
  radiograph/NN
  of/IN
  the/DT
  chest/JJS
  revealing/JJ
  bilateral/JJ
  pleural/JJ
  effusion/NN
  ./.
  felis/NN
  catus/NN
  ,/,
  adult/NN
  ,/,
  longitudinal/JJ
  section/NN
  through/IN
  the/DT
  middle/JJ
  ear/NN
  generated/VBN
  by/IN
  avizo®7/NN
  from/IN
  ct/NN
  data/NNS
  [/$
  42/CD
  ]/NNP
  (/(
  see/VB
  text/NN
  for/IN
  methods/NNS
  )/)
  .seam/VBP
  between/IN
  tympanic/JJ
  plate/NN
  of/IN
  mallear/JJ
  rostral/JJ
  process/NN
  and/CC
  ectotympanic/NN
  is/VBZ
  marked/VBN
  by/IN
  carets/NNS
  ./.
  scale/NN
  =/VBD
  2/CD
  mm/NN
  ./.
  abbreviations/NNS
  :/:
  ecto/NN
  ,/,
  ectotympanic/JJ
  ;/:
  en/FW
  ,/,
  ectotympanic/JJ
  notch/NN
  ;/:
  hm/NN
  ,/,
  head/NN
  of/IN
  malleus/NN
  ;/:
  i/NN
  ,/,
  incus/NN
  ;/:
  mh/CC
  ,/,
  mallear/JJ
  hook/NN
  ;/:
  ol/CC
  ,/,
  osseous/JJ
  lamina/NN
  ;/:
  pet/NN
  ,/,
  petrosal/NN
  ;/:
  tp/CC
  ,/,
  tympanic/JJ
  plate/NN
  of/IN
  rostral/JJ
  process/NN
  ./.
  axial/JJ
  section/NN
  of/IN
  cect/JJ
  abdomen/NNS
  showing/VBG
  enlarged/JJ
  left/JJ
  psoas/NN
  muscle/NN
  with/IN
  ill-defined/JJ
  hypodense/NN
  areas/NNS
  (/(
  star/NN
  )/)
  and/CC
  retroperitoneal/JJ
  fat/NN
  stranding/NN
  (/(
  solid/JJ
  arrow/NN
  )/)
  ./.
  fluid/JJ
  collection/NN
  with/IN
  multiple/JJ
  air/NN
  pockets/NNS
  are/VBP
  seen/VBN
  in/IN
  the/DT
  left/NN
  posterior/JJ
  preperitoneal/JJ
  space/NN
  (/(
  hollow/JJ
  arrow/NN
  )/)
  ./.
  ct/NN
  after/IN
  treatment/NN
  demonstrates/VBZ
  packing/VBG
  coil/NN
  seated/VBN
  in/IN
  right/JJ
  acc/NN
  to/TO
  hypoglossal/VB
  canal/JJ
  (/(
  treated/JJ
  5/CD
  years/NNS
  ago/RB
  )/)
  and/CC
  in/IN
  left/JJ
  acc/NN
  ./.
  computed/VBN
  tomography/NN
  showing/VBG
  large/JJ
  bilateral/JJ
  adrenal/JJ
  masses/NNS
  schematic/JJ
  representation/NN
  of/IN
  the/DT
  method/NN
  used/VBN
  to/TO
  measure/VB
  interradicular/JJ
  spaces/NNS
  ./.
  first/RB
  ,/,
  the/DT
  cemento-enamel/JJ
  junction/NN
  (/(
  cej/NN
  )/)
  of/IN
  the/DT
  two/CD
  adjacent/JJ
  teeth/NNS
  was/VBD
  identified/VBN
  ./.
  starting/VBG
  from/IN
  the/DT
  cej/NN
  ,/,
  a/DT
  ruler/NN
  was/VBD
  scrolled/VBN
  down/RB
  toward/IN
  the/DT
  root/NN
  apex/NN
  until/IN
  3/CD
  mm/NNS
  of/IN
  horizontal/JJ
  interradicular/JJ
  space/NN
  was/VBD
  found/VBN
  ;/:
  then/RB
  ,/,
  the/DT
  distance/NN
  from/IN
  the/DT
  cej/NN
  was/VBD
  measured/VBN
  as/RB
  well/RB
  as/IN
  the/DT
  total/JJ
  root/NN
  length/NN
  from/IN
  the/DT
  cej/NN
  to/TO
  the/DT
  apex/NN
  ./.
  bullet/NN
  localization/NN
  intraoperatively/RB
  by/IN
  portable/JJ
  imaging/NN
  system/NN
  (/(
  c-arm/NN
  )/)
  longitudinal/JJ
  section/NN
  –/NNP
  intercostal/JJ
  space/NN
  (/(
  “/JJ
  bat/NN
  sign/NN
  ”/NN
  )/)
  :/:
  f/JJ
  –/NNP
  subcutaneous/JJ
  fat/NN
  ./.
  ice/NN
  –external/JJ
  intercostal/JJ
  muscle/NN
  ,/,
  r/NN
  –/NNP
  ribs/NN
  ,/,
  horizontal/JJ
  arrows/NNS
  –/VBP
  internal/JJ
  intercostal/JJ
  muscle/NN
  ,/,
  upwards/NNS
  arrow/VBP
  –/JJ
  pleura/NN
  other/JJ
  parameters/NNS
  to/TO
  evaluate/VB
  airway/RB
  ./.
  abdominal/JJ
  computed/JJ
  tomography/NN
  (/(
  ct/NN
  )/)
  scan/NN
  of/IN
  retroperitoneal/JJ
  recurrence/NN
  mri/JJ
  abdomen/NNS
  :/:
  no/DT
  lymph/NN
  node/NN
  or/CC
  distant/JJ
  metastasis/NN
  ./.
  a/DT
  fetus/NN
  in/IN
  the/DT
  uterus/NN
  can/MD
  be/VB
  seen/VBN
  ./.
  three-dimensional/JJ
  reconstruction/NN
  of/IN
  the/DT
  maxilla/NN
  ,/,
  with/IN
  transposition/NN
  of/IN
  the/DT
  left/JJ
  canine/NN
  and/CC
  first/JJ
  premolar/NN
  ./.
  antenatal/JJ
  ultrasound/JJ
  image/NN
  at/IN
  20/CD
  weeks/NNS
  gestation/NN
  ,/,
  illustrating/VBG
  megalourethra/NN
  which/WDT
  is/VBZ
  a/DT
  cystic/JJ
  structure/NN
  ballooning/VBG
  distally/RB
  to/TO
  the/DT
  penile/JJ
  portion/NN
  of/IN
  the/DT
  urethra/NN
  ./.
  obs/$
  600/CD
  –automatic/JJ
  sorting/NN
  machine/NN
  for/IN
  waste/NN
  portable/JJ
  batteries.source/NN
  :/:
  optisort/NN
  ./.
  chest/JJS
  radiograph/JJ
  showing/VBG
  left-sided/JJ
  pleural/JJ
  effusion/NN
  shortly/RB
  after/IN
  admission/NN
  ./.
  post/NN
  mortem/NN
  ct/NN
  shows/VBZ
  hydrocephalus/NN
  (/(
  asterisk/NN
  )/)
  and/CC
  multicystic/JJ
  encephalomalacia/NN
  (/(
  arrow/NN
  )/)
  axial/JJ
  ct/NN
  demonstrating/VBG
  a/DT
  well-defined/JJ
  lesion/NN
  with/IN
  the/DT
  expansion/NN
  of/IN
  buccal/JJ
  and/CC
  lingual/JJ

In [57]:
import spacy
from spacy import displacy
nlp=spacy.load("en_core_web_sm")
text="Apple is looking at buying UK startup for $ 1billion"
doc=nlp(text)
displacy.render(doc,style="ent",jupyter=True)

In [58]:
sentences=sentences[:2]

In [59]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=100,binary=True)

In [60]:
sentences=["this is a NLP+CV project","Hi everyone NLP+CV"]

In [61]:
X=cv.fit_transform(sentences)
X.toarray()

array([[1, 0, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 0]])

In [62]:
cv.get_feature_names_out()

array(['cv', 'everyone', 'hi', 'is', 'nlp', 'project', 'this'],
      dtype=object)

In [63]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=100,binary=True,ngram_range=(2,3))

In [64]:
X=cv.fit_transform(sentences)

In [65]:
X.toarray()

array([[1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0]])

In [66]:
cv.get_feature_names_out()

array(['cv project', 'everyone nlp', 'everyone nlp cv', 'hi everyone',
       'hi everyone nlp', 'is nlp', 'is nlp cv', 'nlp cv',
       'nlp cv project', 'this is', 'this is nlp'], dtype=object)

In [67]:
cv.vocabulary_

{'this is': 9,
 'is nlp': 5,
 'nlp cv': 7,
 'cv project': 0,
 'this is nlp': 10,
 'is nlp cv': 6,
 'nlp cv project': 8,
 'hi everyone': 3,
 'everyone nlp': 1,
 'hi everyone nlp': 4,
 'everyone nlp cv': 2}

In [83]:
sentences = ["This is the first document.", "This document is the second document.", "And this is the third one."]

In [84]:
sentences=sentences[:3]

In [85]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [86]:
tfidf=TfidfVectorizer(max_features=100)
X=tfidf.fit_transform(sentences).toarray()

In [87]:
sentences

['This is the first document.',
 'This document is the second document.',
 'And this is the third one.']

In [88]:
X

array([[0.        , 0.46941728, 0.61722732, 0.3645444 , 0.        ,
        0.        , 0.3645444 , 0.        , 0.3645444 ],
       [0.        , 0.7284449 , 0.        , 0.28285122, 0.        ,
        0.47890875, 0.28285122, 0.        , 0.28285122],
       [0.49711994, 0.        , 0.        , 0.29360705, 0.49711994,
        0.        , 0.29360705, 0.49711994, 0.29360705]])

In [89]:
tfidf.vocabulary_

{'this': 8,
 'is': 3,
 'the': 6,
 'first': 2,
 'document': 1,
 'second': 5,
 'and': 0,
 'third': 7,
 'one': 4}

In [90]:
!pip install gensim

Requirement already satisfied: gensim in /usr/local/lib/python3.10/dist-packages (4.3.3)
Requirement already satisfied: numpy<2.0,>=1.18.5 in /usr/local/lib/python3.10/dist-packages (from gensim) (1.26.4)
Requirement already satisfied: scipy<1.14.0,>=1.7.0 in /usr/local/lib/python3.10/dist-packages (from gensim) (1.13.1)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.10/dist-packages (from gensim) (7.0.5)
Requirement already satisfied: wrapt in /usr/local/lib/python3.10/dist-packages (from smart-open>=1.8.1->gensim) (1.16.0)

In [91]:
from gensim.models import Word2Vec,KeyedVectors

In [95]:
import gensim.downloader as api
wv=api.load("word2vec-google-news-300")

[==================================================] 100.0% 1662.8/1662.8MB downloaded

In [96]:
veec_king=wv["king"]
veec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  2.01416016e-02, -1.63085938e-01,  1.35803223e-03,
       -1.44531250e-01, -5.68847656e-02,  4.29687500e-02, -2.46582031e-02,
        1.85546875e-01,  4.47265625e-01,  9.58251953e-03,  1.31835938e-01,
        9.86328125e-02, -1.85546875e-01, -1.00097656e-01, -1.33789062e-01,
       -1.25000000e-01,  2.83203125e-01,  1.23046875e-01,  5.32226562e-02,
       -1.77734375e-01,  8.59375000e-02, -2.18505859e-02,  2.05078125e-02,
       -1.39648438e-01,  2.51464844e-02,  1.38671875e-01, -1.05468750e-01,
        1.38671875e-01,  8.88671875e-02, -7.51953125e-02, -2.13623047e-02,
        1.72851562e-01,  4.63867188e-02, -2.65625000e-01,  8.91113281e-03,
        1.49414062e-01,  3.78417969e-02,  2.38281250e-01, -1.24511719e-01,
       -2.17773438e-01, -1.81640625e-01,  2.97851562e-02,  5.71289062e-02,
       -2.89306641e-02,  1.24511719e-02,  9.66796875e-02, -2.31445312e-01,
        5.81054688e-02,  6.68945312e-02,  7.08007812e-02, -3.08593750e-01,
       -2.14843750e-01,  1.45507812e-01, -4.27734375e-01, -9.39941406e-03,
        1.54296875e-01, -7.66601562e-02,  2.89062500e-01,  2.77343750e-01,
       -4.86373901e-04, -1.36718750e-01,  3.24218750e-01, -2.46093750e-01,
       -3.03649902e-03, -2.11914062e-01,  1.25000000e-01,  2.69531250e-01,
        2.04101562e-01,  8.25195312e-02, -2.01171875e-01, -1.60156250e-01,
       -3.78417969e-02, -1.20117188e-01,  1.15234375e-01, -4.10156250e-02,
       -3.95507812e-02, -8.98437500e-02,  6.34765625e-03,  2.03125000e-01,
        1.86523438e-01,  2.73437500e-01,  6.29882812e-02,  1.41601562e-01,
       -9.81445312e-02,  1.38671875e-01,  1.82617188e-01,  1.73828125e-01,
        1.73828125e-01, -2.37304688e-01,  1.78710938e-01,  6.34765625e-02,
        2.36328125e-01, -2.08984375e-01,  8.74023438e-02, -1.66015625e-01,
       -7.91015625e-02,  2.43164062e-01, -8.88671875e-02,  1.26953125e-01,
       -2.16796875e-01, -1.73828125e-01, -3.59375000e-01, -8.25195312e-02,
       -6.49414062e-02,  5.07812500e-02,  1.35742188e-01, -7.47070312e-02,
       -1.64062500e-01,  1.15356445e-02,  4.45312500e-01, -2.15820312e-01,
       -1.11328125e-01, -1.92382812e-01,  1.70898438e-01, -1.25000000e-01,
        2.65502930e-03,  1.92382812e-01, -1.74804688e-01,  1.39648438e-01,
        2.92968750e-01,  1.13281250e-01,  5.95703125e-02, -6.39648438e-02,
        9.96093750e-02, -2.72216797e-02,  1.96533203e-02,  4.27246094e-02,
       -2.46093750e-01,  6.39648438e-02, -2.25585938e-01, -1.68945312e-01,
        2.89916992e-03,  8.20312500e-02,  3.41796875e-01,  4.32128906e-02,
        1.32812500e-01,  1.42578125e-01,  7.61718750e-02,  5.98144531e-02,
       -1.19140625e-01,  2.74658203e-03, -6.29882812e-02, -2.72216797e-02,
       -4.82177734e-03, -8.20312500e-02, -2.49023438e-02, -4.00390625e-01,
       -1.06933594e-01,  4.24804688e-02,  7.76367188e-02, -1.16699219e-01,
        7.37304688e-02, -9.22851562e-02,  1.07910156e-01,  1.58203125e-01,
        4.24804688e-02,  1.26953125e-01,  3.61328125e-02,  2.67578125e-01,
       -1.01074219e-01, -3.02734375e-01, -5.76171875e-02,  5.05371094e-02,
        5.26428223e-04, -2.07031250e-01, -1.38671875e-01, -8.97216797e-03,
       -2.78320312e-02, -1.41601562e-01,  2.07031250e-01, -1.58203125e-01,
        1.27929688e-01,  1.49414062e-01, -2.24609375e-02, -8.44726562e-02,
        1.22558594e-01,  2.15820312e-01, -2.13867188e-01, -3.12500000e-01,
       -3.73046875e-01,  4.08935547e-03,  1.07421875e-01,  1.06933594e-01,
        7.32421875e-02,  8.97216797e-03, -3.88183594e-02, -1.29882812e-01,
        1.49414062e-01, -2.14843750e-01, -1.83868408e-03,  9.91210938e-02,
        1.57226562e-01, -1.14257812e-01, -2.05078125e-01,  9.91210938e-02,
        3.69140625e-01, -1.97265625e-01,  3.54003906e-02,  1.09375000e-01,
        1.31835938e-01,  1.66992188e-01,  2.35351562e-01,  1.04980469e-01,
       -4.96093750e-01, -1.64062500e-01, -1.56250000e-01, -5.22460938e-02,
        1.03027344e-01,  2.43164062e-01, -1.88476562e-01,  5.07812500e-02,
       -9.37500000e-02, -6.68945312e-02,  2.27050781e-02,  7.61718750e-02,
        2.89062500e-01,  3.10546875e-01, -5.37109375e-02,  2.28515625e-01,
        2.51464844e-02,  6.78710938e-02, -1.21093750e-01, -2.15820312e-01,
       -2.73437500e-01, -3.07617188e-02, -3.37890625e-01,  1.53320312e-01,
        2.33398438e-01, -2.08007812e-01,  3.73046875e-01,  8.20312500e-02,
        2.51953125e-01, -7.61718750e-02, -4.66308594e-02, -2.23388672e-02,
        2.99072266e-02, -5.93261719e-02, -4.66918945e-03, -2.44140625e-01,
       -2.09960938e-01, -2.87109375e-01, -4.54101562e-02, -1.77734375e-01,
       -2.79296875e-01, -8.59375000e-02,  9.13085938e-02,  2.51953125e-01],
      dtype=float32)

In [97]:
wv.most_similar("king")

[('kings', 0.7138045430183411),
 ('queen', 0.6510956883430481),
 ('monarch', 0.6413194537162781),
 ('crown_prince', 0.6204220056533813),
 ('prince', 0.6159993410110474),
 ('sultan', 0.5864824056625366),
 ('ruler', 0.5797567367553711),
 ('princes', 0.5646552443504333),
 ('Prince_Paras', 0.5432944297790527),
 ('throne', 0.5422105193138123)]

In [98]:
wv.most_similar("car")

[('vehicle', 0.7821096181869507),
 ('cars', 0.7423831224441528),
 ('SUV', 0.7160962224006653),
 ('minivan', 0.6907036900520325),
 ('truck', 0.6735789775848389),
 ('Car', 0.6677608489990234),
 ('Ford_Focus', 0.667320191860199),
 ('Honda_Civic', 0.6626849174499512),
 ('Jeep', 0.651133120059967),
 ('pickup_truck', 0.6441438794136047)]

In [99]:
sentences

['This is the first document.',
 'This document is the second document.',
 'And this is the third one.']

In [100]:
words=[]
for i in range(len(sentences)):
    words_=nltk.word_tokenize(sentences[i])
    words.append(words_)

In [101]:
words

[['This', 'is', 'the', 'first', 'document', '.'],
 ['This', 'document', 'is', 'the', 'second', 'document', '.'],
 ['And', 'this', 'is', 'the', 'third', 'one', '.']]

In [103]:
cbow_model=Word2Vec(words,vector_size=10,min_count=1,sg=0)
skipgram_model=Word2Vec(words,vector_size=10,min_count=1,sg=1)

In [105]:
cbow_model.wv["document"]

array([ 0.07380296, -0.01532174, -0.04537598,  0.06552566, -0.04859179,
       -0.01815982,  0.0287764 ,  0.00991656, -0.0828639 , -0.09448527],
      dtype=float32)

In [107]:
cbow_model.wv.most_similar("document")

[('.', 0.5435577034950256),
 ('the', 0.3294057548046112),
 ('this', 0.2324611097574234),
 ('And', 0.03525553643703461),
 ('first', 0.03377028554677963),
 ('third', -0.17989817261695862),
 ('is', -0.21131564676761627),
 ('one', -0.3819473087787628),
 ('second', -0.5145915746688843),
 ('This', -0.5381641983985901)]

In [108]:
skipgram_model.wv["document"]

array([ 0.0737975 , -0.01532629, -0.04537274,  0.06553396, -0.04859476,
       -0.01816242,  0.02877441,  0.00991514, -0.08285948, -0.09447918],
      dtype=float32)

In [110]:
skipgram_model.wv.most_similar("document")

[('.', 0.5435900092124939),
 ('the', 0.3293773829936981),
 ('this', 0.23230676352977753),
 ('And', 0.03525340184569359),
 ('first', 0.03377976268529892),
 ('third', -0.1802682727575302),
 ('is', -0.21132346987724304),
 ('one', -0.38193345069885254),
 ('second', -0.5145905017852783),
 ('This', -0.5381653904914856)]